'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { createSupabaseBrowserClient } from '@/lib/supabase'
import { chooseAdaptiveSkill } from '@/lib/adaptiveEngine'
import { evaluateSpanishWriting, generateSpanishWritingTask, spanishWritingSkillIds, type SpanishWritingTask, type WritingEvaluation } from '@/lib/spanishWritingTasks'
import { userFacingError } from '@/lib/userFacingError'

const SESSION_LENGTH = 10
const MODE = 'spanish_writing'
const NETWORK_TIMEOUT_MS = 12_000
const RECENT_PROMPT_WINDOW = 80
const WRITING_SKILL_IDS = new Set(spanishWritingSkillIds())

type SkillRow = { id: string; name: string; generator_key: string; unit_id: string }
type SkillState = { skill_id: string; mastery: number; confidence: number; difficulty: number; priority: number; last_practiced_at?: string | null }
type PracticeOpenResult = { data: unknown; error: { message?: string } | null }
type ActiveTask = SpanishWritingTask & { difficulty: number; seed: number; label: string }

async function withTimeout<T>(operation: PromiseLike<T>, label: string, timeoutMs = NETWORK_TIMEOUT_MS): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined
  try { return await Promise.race([Promise.resolve(operation), new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error(`${label} agotó el tiempo de espera`)), timeoutMs) })]) }
  finally { if (timer) clearTimeout(timer) }
}
function hashText(value: string) { let hash = 2166136261; for (let i = 0; i < value.length; i += 1) { hash ^= value.charCodeAt(i); hash = Math.imul(hash, 16777619) } return hash >>> 0 }
function template(prompt: string) { return prompt.toLowerCase().replace(/\d+(?:[.,]\d+)?/g, '#').replace(/\s+/g, ' ').trim() }
function errorMessage(error: unknown, fallback: string) { return error instanceof Error && error.message ? `${fallback} ${error.message}.` : fallback }
function FreePracticeLink() { return <Link className="btn dark" href="/zone/language/writing/replay">PRÁCTICA LIBRE</Link> }

export default function SpanishWritingSession() {
  const [playerId, setPlayerId] = useState<string | null>(null), [sessionId, setSessionId] = useState<string | null>(null)
  const [skills, setSkills] = useState<SkillRow[]>([]), [states, setStates] = useState<Record<string, SkillState>>({}), [task, setTask] = useState<ActiveTask | null>(null)
  const [response, setResponse] = useState(''), [evaluation, setEvaluation] = useState<WritingEvaluation | null>(null), [index, setIndex] = useState(0), [correct, setCorrect] = useState(0), [xp, setXp] = useState(0)
  const [answered, setAnswered] = useState(false), [feedback, setFeedback] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState(''), [completed, setCompleted] = useState(false), [completedToday, setCompletedToday] = useState(false), [closing, setClosing] = useState(false)
  const recentTemplates = useRef<string[]>([]), recentSkillIds = useRef<string[]>([]), recentUnitIds = useRef<string[]>([]), sessionUnitCounts = useRef<Record<string, number>>({}), taskStarted = useRef(Date.now())
  const seedBase = useMemo(() => hashText(sessionId ?? playerId ?? MODE), [sessionId, playerId])

  useEffect(() => { let active = true; ;(async () => { try {
    const id = localStorage.getItem('levelup_player_id'); if (!id) throw new Error('No hay un jugador seleccionado'); if (!active) return; setPlayerId(id)
    const supabase = createSupabaseBrowserClient(); if (!supabase) throw new Error('Supabase no está configurado')
    const openPractice = supabase.rpc.bind(supabase) as unknown as (name: 'open_levelup_practice_session', args: { p_player_id: string; p_mode: string }) => PromiseLike<PracticeOpenResult>
    const { data: opened, error: openError } = await withTimeout(openPractice('open_levelup_practice_session', { p_player_id: id, p_mode: MODE }), 'La apertura de Sala de cronistas'); if (!active) return
    if (openError) { if ((openError.message ?? '').toLowerCase().includes('practice already completed today')) { setCompletedToday(true); return } throw new Error(userFacingError(openError, 'No se pudo abrir Sala de cronistas.')) }
    const openedId = String((opened as { session_id?: string } | null)?.session_id ?? ''); if (!openedId) throw new Error('El servidor no devolvió un identificador de sesión'); setSessionId(openedId)
    const [unitsResult, statesResult, attemptsResult, historyResult] = await Promise.all([
      withTimeout(supabase.from('curriculum_units').select('id').eq('subject_id', 'spanish').eq('active', true).order('sort_order'), 'La carga del currículo de Lengua'),
      withTimeout(supabase.from('player_skill_state').select('skill_id,mastery,confidence,difficulty,priority,last_practiced_at').eq('player_id', id), 'La carga del progreso de Lengua'),
      withTimeout(supabase.from('attempts').select('correct,xp_awarded,skill_id,prompt_snapshot,created_at').eq('session_id', openedId).order('created_at', { ascending: true }), 'La recuperación de Sala de cronistas'),
      withTimeout(supabase.from('attempts').select('skill_id,prompt_snapshot,created_at').eq('player_id', id).like('skill_id', 'L%').order('created_at', { ascending: false }).limit(RECENT_PROMPT_WINDOW), 'La carga del historial reciente de Lengua')])
    if (!active) return; if (unitsResult.error || !unitsResult.data?.length) throw new Error('No se pudo cargar el currículo activo de Lengua'); if (statesResult.error) throw new Error(userFacingError(statesResult.error, 'No se pudo cargar el progreso de Lengua.')); if (attemptsResult.error) throw new Error(userFacingError(attemptsResult.error, 'No se pudo recuperar Sala de cronistas.')); if (historyResult.error) throw new Error(userFacingError(historyResult.error, 'No se pudo cargar el historial reciente de Lengua.'))
    const unitIds = unitsResult.data.map((row) => String(row.id)); const { data: skillRows, error: skillsError } = await withTimeout(supabase.from('skills').select('id,name,generator_key,unit_id').eq('active', true).in('unit_id', unitIds), 'La carga de expresión escrita'); if (!active) return
    if (skillsError || !skillRows?.length) throw new Error('No hay habilidades activas de Lengua disponibles'); const loadedSkills = (skillRows as SkillRow[]).filter((skill) => WRITING_SKILL_IDS.has(skill.id)); if (!loadedSkills.length) throw new Error('No hay habilidades de expresión escrita disponibles'); setSkills(loadedSkills)
    const stateMap: Record<string, SkillState> = {}; for (const row of statesResult.data ?? []) { const skillId = typeof row.skill_id === 'string' ? row.skill_id : ''; if (!WRITING_SKILL_IDS.has(skillId)) continue; stateMap[skillId] = { skill_id: skillId, mastery: Number(row.mastery ?? 50), confidence: Number(row.confidence ?? 50), difficulty: Number(row.difficulty ?? 1), priority: Number(row.priority ?? 50), last_practiced_at: row.last_practiced_at } } setStates(stateMap)
    const skillToUnit = new Map(loadedSkills.map((skill) => [skill.id, skill.unit_id])); const attempts = attemptsResult.data ?? []; const counts: Record<string, number> = {}; for (const attempt of attempts) { const skillId = String(attempt.skill_id ?? ''), unitId = skillToUnit.get(skillId); if (!unitId) continue; counts[unitId] = (counts[unitId] ?? 0) + 1; recentSkillIds.current.unshift(skillId); recentUnitIds.current.unshift(unitId) }
    sessionUnitCounts.current = counts; recentSkillIds.current = recentSkillIds.current.slice(0, 5); recentUnitIds.current = recentUnitIds.current.slice(0, 3); recentTemplates.current = (historyResult.data ?? []).map((attempt) => template(String(attempt.prompt_snapshot ?? ''))).filter(Boolean).slice(0, RECENT_PROMPT_WINDOW); setIndex(Math.min(SESSION_LENGTH, attempts.length)); setCorrect(attempts.filter((attempt) => attempt.correct === true).length); setXp(attempts.reduce((sum, attempt) => sum + Number(attempt.xp_awarded ?? 0), 0))
  } catch (cause) { if (active) setError(errorMessage(cause, 'No se pudo abrir Sala de cronistas.')) } finally { if (active) setLoading(false) } })(); return () => { active = false } }, [])

  useEffect(() => {
    if (loading || error || task || !sessionId || !skills.length || index >= SESSION_LENGTH) return
    const baseSeed = (seedBase + Math.imul(index + 1, 0x9e3779b9)) >>> 0
    try {
      const unitIds = Array.from(new Set(skills.map((skill) => skill.unit_id)))
      let primarySkill: SkillRow | null = null
      try { primarySkill = chooseAdaptiveSkill({ skills, states, focusUnitIds: unitIds, reviewUnitIds: [], sessionUnitCounts: sessionUnitCounts.current, recentSkillIds: recentSkillIds.current, recentUnitIds: recentUnitIds.current, seed: seedBase, questionIndex: index }) }
      catch { primarySkill = null }
      primarySkill ??= skills[index % skills.length]
      const candidates = [primarySkill, ...skills.filter((skill) => skill.id !== primarySkill.id)]
      let selected: ActiveTask | null = null
      for (let c = 0; c < candidates.length && !selected; c += 1) {
        const candidate = candidates[c]; let seed = (baseSeed + Math.imul(c, 0x85ebca6b)) >>> 0
        for (let attempt = 0; attempt < 12; attempt += 1) { try { const nextTask = generateSpanishWritingTask(candidate.id, seed); if (!recentTemplates.current.includes(template(nextTask.prompt))) { selected = { ...nextTask, difficulty: states[candidate.id]?.difficulty ?? 1, seed, label: candidate.name }; break } } catch { break } seed = (seed + 2654435761) >>> 0 }
      }
      if (!selected) { const fallbackSkill = skills[index % skills.length]; const fallback = generateSpanishWritingTask(fallbackSkill.id, baseSeed); selected = { ...fallback, difficulty: states[fallbackSkill.id]?.difficulty ?? 1, seed: baseSeed, label: fallbackSkill.name } }
      recentTemplates.current = [template(selected.prompt), ...recentTemplates.current].slice(0, RECENT_PROMPT_WINDOW); setTask(selected); setResponse(''); setEvaluation(null); setAnswered(false); setFeedback(''); taskStarted.current = Date.now()
    } catch (cause) { setError(errorMessage(cause, 'No se pudo generar el siguiente encargo.')) }
  }, [loading, error, task, sessionId, skills, states, seedBase, index])

  useEffect(() => { if (!sessionId || index < SESSION_LENGTH || completed || closing) return; setClosing(true); ;(async () => { try { const supabase = createSupabaseBrowserClient(); if (!supabase) throw new Error('No se pudo conectar para cerrar la sala'); const { data, error: closeError } = await withTimeout(supabase.rpc('complete_levelup_session', { p_session_id: sessionId }), 'El cierre de Sala de cronistas'); if (closeError) throw new Error(userFacingError(closeError, 'No se pudo cerrar Sala de cronistas.')); const result = data as { completed?: boolean; attempts?: number; xp_earned?: number }; if (!result?.completed || Number(result.attempts) !== SESSION_LENGTH) throw new Error('El servidor no confirmó los 10 encargos de escritura'); setXp(Number(result.xp_earned ?? xp)); setCompleted(true) } catch (cause) { setError(errorMessage(cause, 'No se pudo cerrar Sala de cronistas.')) } finally { setClosing(false) } })() }, [index, sessionId, completed, closing, xp])

  async function submit() { if (answered || !task || !playerId || !sessionId) return; if (!response.trim()) { setFeedback('Escribe una respuesta antes de entregar.'); return } const resultEvaluation = evaluateSpanishWriting(task, response, task.difficulty); setAnswered(true); setEvaluation(resultEvaluation); try { const supabase = createSupabaseBrowserClient(); if (!supabase) throw new Error('No se pudo conectar'); const unmetTags = resultEvaluation.checks.filter((check) => !check.met).map((check) => `writing:${check.code}`); const { data, error: submitError } = await withTimeout(supabase.rpc('submit_levelup_attempt', { p_player_id: playerId, p_skill_id: task.skillId, p_correct: resultEvaluation.ok, p_response_ms: Math.min(3_600_000, Math.max(1, Date.now() - taskStarted.current)), p_difficulty: task.difficulty, p_seed: task.seed, p_prompt: task.prompt, p_session_id: sessionId, p_diagnostic_tags: ['spanish_writing', ...unmetTags] }), 'El guardado del texto'); if (submitError) throw new Error(userFacingError(submitError, 'No se pudo guardar el texto.')); const result = data as { xp_awarded?: number; mastery?: number; confidence?: number; difficulty?: number; priority?: number }; const unitId = skills.find((skill) => skill.id === task.skillId)?.unit_id; if (unitId) { sessionUnitCounts.current = { ...sessionUnitCounts.current, [unitId]: (sessionUnitCounts.current[unitId] ?? 0) + 1 }; recentSkillIds.current = [task.skillId, ...recentSkillIds.current.filter((id) => id !== task.skillId)].slice(0, 5); recentUnitIds.current = [unitId, ...recentUnitIds.current].slice(0, 3) } setStates((current) => ({ ...current, [task.skillId]: { skill_id: task.skillId, mastery: Number(result.mastery ?? 50), confidence: Number(result.confidence ?? 50), difficulty: Number(result.difficulty ?? 1), priority: Number(result.priority ?? 50), last_practiced_at: new Date().toISOString() } })); setXp((value) => value + Number(result.xp_awarded ?? 0)); if (resultEvaluation.ok) setCorrect((value) => value + 1); setFeedback((resultEvaluation.ok ? '✓ Crónica validada' : `↻ ${resultEvaluation.met}/${resultEvaluation.total} criterios cumplidos`) + ` · ${Number(result.xp_awarded ?? 0)} XP`) } catch (cause) { setAnswered(false); setEvaluation(null); setFeedback(errorMessage(cause, 'No se pudo guardar el texto.')) } }
  function next() { if (!answered || !feedback) return; setTask(null); setResponse(''); setEvaluation(null); setIndex((value) => value + 1) }

  if (loading) return <section className="card" role="status"><p className="muted">Abriendo Sala de cronistas…</p></section>
  if (completedToday) return <section className="card" style={{ textAlign: 'center', padding: 45 }}><div style={{ fontSize: 72 }}>✍️✅</div><span className="tag">SALA COMPLETADA HOY</span><h1>Práctica de escritura terminada</h1><p className="muted">Los 10 encargos, el progreso y las recompensas ya están guardados. Puedes seguir entrenando sin modificar recompensas ni progreso.</p><div className="action-row" style={{ justifyContent: 'center' }}><FreePracticeLink /><Link className="btn primary" href="/zone/language">VOLVER A LA BIBLIOTECA</Link><Link className="btn dark" href="/world">VOLVER AL MUNDO</Link></div></section>
  if (error) return <section className="card" role="alert"><span className="tag">SALA DE CRONISTAS</span><h1>No se puede continuar</h1><p className="muted">{error}</p><div className="action-row"><button className="btn primary" type="button" onClick={() => window.location.reload()}>REINTENTAR</button><Link className="btn dark" href="/zone/language">VOLVER A LA BIBLIOTECA</Link></div></section>
  if (index >= SESSION_LENGTH) { if (!completed) return <section className="card" role="status"><h1>{closing ? 'Validando los 10 textos…' : 'Confirmando resultados…'}</h1></section>; return <section className="card" style={{ textAlign: 'center', padding: 45 }}><div style={{ fontSize: 72 }}>✍️✨</div><span className="tag">SALA SUPERADA</span><h1>Crónicas archivadas</h1><p className="muted">10 encargos · {Math.round((correct / SESSION_LENGTH) * 100)}% validados · +{xp} XP</p><p className="muted">Puedes seguir practicando sin recompensas adicionales.</p><div className="action-row" style={{ justifyContent: 'center' }}><FreePracticeLink /><Link className="btn primary" href="/zone/language">VOLVER A LA BIBLIOTECA</Link><Link className="btn dark" href="/world">VOLVER AL MUNDO</Link></div></section> }
  if (!task) return <section className="card" role="status"><p className="muted">Preparando el siguiente encargo de escritura…</p></section>
  const progress = Math.min(SESSION_LENGTH, index + Number(answered && feedback))
  return <div className="mission-console"><section className="card mission-control"><div><span className="tag">📚 LENGUA · SALA DE CRONISTAS</span><h1>Encargo {index + 1} de {SESSION_LENGTH}</h1><p className="muted">Ortografía, narración, descripción y revisión guiadas por el progreso real.</p></div><Link className="btn dark mission-exit" href="/zone/language">SALIR A LA BIBLIOTECA</Link><div className="energy-track" role="progressbar" aria-valuemin={0} aria-valuemax={SESSION_LENGTH} aria-valuenow={progress}>{Array.from({ length: SESSION_LENGTH }, (_, position) => <span key={position} className={position < progress ? 'charged' : position === index ? 'active' : ''}>{position < progress ? '⚡' : position + 1}</span>)}</div></section><div className="mission-stage"><aside className="mission-core"><span className="mission-avatar">✍️</span><span className="core-city">📚</span><div className="core-orb">⚡</div><b>Archivo {Math.round((progress / SESSION_LENGTH) * 100)}%</b><span>{correct} validados · {xp} XP</span><small>10 textos para completar la colección</small></aside><section className="card mission-question"><span className="tag">{task.label} · dificultad {task.difficulty}/5</span><h2>{task.title}</h2><p style={{ fontSize: 22, fontWeight: 800 }}>{task.prompt}</p><p className="muted">💡 {task.hint}</p><div className="metric" style={{ marginTop: 14 }} aria-label="Criterios que debes cumplir"><b>🎯 Debes cumplir</b><ul>{task.criteria.map((criterion) => <li key={criterion.code}>{criterion.label}</li>)}</ul></div><textarea aria-label="Tu texto" value={response} disabled={answered} onChange={(event) => setResponse(event.target.value)} rows={8} maxLength={1800} placeholder="Escribe aquí tu respuesta…" style={{ width: '100%', resize: 'vertical', padding: 16, borderRadius: 14, font: 'inherit' }} />{!answered && <div className="action-row" style={{ marginTop: 14 }}><button className="btn primary" type="button" onClick={submit}>ENTREGAR TEXTO</button><span className="muted">{response.trim() ? `${response.trim().split(/\s+/).length} palabras` : 'Empieza a escribir para completar el encargo.'}</span></div>}{feedback && <div className="metric" style={{ marginTop: 16 }}><b>{feedback}</b></div>}{evaluation && <div className="metric" style={{ marginTop: 10 }}><b>📝 Revisión</b><p className="muted">{evaluation.wordCount} palabras · {evaluation.sentenceCount} oraciones</p><ul>{evaluation.checks.map((check) => <li key={check.code}>{check.met ? '✓' : '↻'} {check.label}</li>)}</ul></div>}{answered && feedback && <button className="btn primary" type="button" style={{ marginTop: 14 }} onClick={next}>{index + 1 === SESSION_LENGTH ? 'VALIDAR SALA' : 'SIGUIENTE ENCARGO'}</button>}</section></div></div>
}