-- ARCHIVO HISTÓRICO: NO EJECUTAR.
--
-- El esquema inicial que contenía este archivo dejó de representar la base
-- real de Level Up. Ejecutarlo en un proyecto nuevo produciría una instalación
-- incompleta y sin las políticas, columnas, funciones y datos curriculares
-- necesarios.
--
-- Los cambios vigentes están versionados en database/migrations/.
-- Antes de provisionar un Supabase nuevo debe incorporarse al repositorio un
-- baseline completo exportado y revisado desde la base actual.
