-- ARCHIVO HISTÓRICO: NO EJECUTAR.
--
-- Las dos habilidades del seed original son registros antiguos e inactivos.
-- El currículo vigente se administra en la base de producción y deberá formar
-- parte del futuro baseline completo antes de provisionar un proyecto nuevo.
