import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta = { id: string; name: string; generator_key: string }
type Card = { level: number; prompt: string; answer: string; distractors: [string,string,string]; solution: string }

const BANK: Record<string, Card[]> = {
  G01S01: [
    {level:1,prompt:'Un barco está a 30° N, 20° O. ¿En qué hemisferio respecto al ecuador se encuentra?',answer:'Hemisferio norte',distractors:['Hemisferio sur','Hemisferio oriental','No puede saberse'],solution:'La latitud 30° N sitúa el punto al norte del ecuador.'},
    {level:1,prompt:'Si avanzas hacia el este manteniendo la misma latitud, ¿qué coordenada cambia principalmente?',answer:'La longitud',distractors:['La latitud','La altitud','La escala'],solution:'Moverse este-oeste cambia la longitud respecto a Greenwich.'},
    {level:2,prompt:'Dos lugares tienen 40° N, pero uno está a 3° E y otro a 3° O. ¿Qué comparten?',answer:'La misma latitud',distractors:['La misma longitud','El mismo hemisferio este-oeste','La misma altitud'],solution:'Ambos están a 40° N, aunque a lados distintos de Greenwich.'},
    {level:2,prompt:'¿Qué coordenadas sitúan un punto al sur del ecuador y al este de Greenwich?',answer:'15° S, 25° E',distractors:['15° N, 25° E','15° S, 25° O','15° N, 25° O'],solution:'S indica hemisferio sur y E, este de Greenwich.'},
    {level:3,prompt:'Un punto A está a 10° N y otro B a 55° N, ambos sobre el mismo meridiano. ¿Cuál está más lejos del ecuador?',answer:'B',distractors:['A','Están a la misma distancia','No depende de la latitud'],solution:'Una latitud absoluta mayor implica mayor distancia angular al ecuador.'},
    {level:3,prompt:'¿Qué error hay en unas coordenadas escritas como 120° N, 40° E?',answer:'La latitud no puede superar 90°',distractors:['La longitud no puede superar 40°','No se puede usar E','Falta la altitud'],solution:'Las latitudes van de 0° a 90° N o S.'},
    {level:4,prompt:'Un explorador cruza el meridiano de Greenwich sin cambiar de latitud. ¿Qué cambia?',answer:'Pasa de longitud oeste a este o viceversa',distractors:['Cambia de hemisferio norte a sur','Su latitud se hace 0°','Su altitud se vuelve negativa'],solution:'Greenwich separa longitudes este y oeste; no afecta a la latitud.'},
    {level:4,prompt:'¿Por qué latitud y longitud permiten una localización absoluta?',answer:'Porque su combinación identifica una posición única sobre la superficie terrestre',distractors:['Porque indican siempre la altitud','Porque sustituyen cualquier mapa','Porque solo sirven dentro de una ciudad'],solution:'El cruce de un paralelo y un meridiano define una posición concreta.'},
  ],
  G01S02: [
    {level:1,prompt:'En un mapa 1:25 000, 1 cm representa 250 m. ¿Cuánto representan 4 cm?',answer:'1 km',distractors:['100 m','4 km','10 km'],solution:'4 × 250 m = 1000 m = 1 km.'},
    {level:1,prompt:'Si una escala gráfica indica 0—5 km y esa barra mide 2 cm, ¿qué representan 6 cm?',answer:'15 km',distractors:['3 km','10 km','30 km'],solution:'Cada 2 cm equivalen a 5 km; 6 cm son tres tramos, es decir 15 km.'},
    {level:2,prompt:'Una ruta mide 7 cm en un mapa donde 1 cm equivale a 3 km. ¿Cuál es la distancia real?',answer:'21 km',distractors:['10 km','14 km','28 km'],solution:'7 × 3 = 21 km.'},
    {level:2,prompt:'¿Qué mapa ofrece normalmente más detalle?',answer:'Uno a escala 1:5 000',distractors:['Uno a escala 1:500 000','Uno a escala 1:5 000 000','Todos ofrecen el mismo detalle'],solution:'Cuanto menor es el denominador, mayor es la escala y el detalle.'},
    {level:3,prompt:'Una carretera real de 36 km mide 9 cm en el mapa. ¿Cuántos km representa cada centímetro?',answer:'4 km',distractors:['2 km','9 km','45 km'],solution:'36 ÷ 9 = 4 km por cm.'},
    {level:3,prompt:'En dos mapas del mismo territorio, uno es 1:10 000 y otro 1:100 000. ¿Cuál muestra una calle con mayor longitud sobre el papel?',answer:'El de 1:10 000',distractors:['El de 1:100 000','Ambos igual','Depende solo del norte'],solution:'La escala 1:10 000 representa los objetos más grandes en el mapa.'},
    {level:4,prompt:'Una distancia de 2,5 cm a escala 1:80 000 equivale aproximadamente a…',answer:'2 km',distractors:['200 m','8 km','20 km'],solution:'2,5 × 80 000 cm = 200 000 cm = 2 km.'},
    {level:4,prompt:'¿Por qué una escala numérica puede dejar de ser válida si una imagen del mapa se amplía sin recalcularla?',answer:'Porque cambia la relación entre medida en la imagen y distancia real',distractors:['Porque cambia el norte geográfico','Porque desaparecen las coordenadas','Porque la Tierra cambia de tamaño'],solution:'Al redimensionar la imagen, las medidas sobre ella cambian aunque el número impreso no.'},
  ],
  G01S03: [
    {level:1,prompt:'Para estudiar fronteras y capitales, ¿qué tipo de mapa elegirías?',answer:'Político',distractors:['Físico','Climático','Geológico'],solution:'Un mapa político representa divisiones administrativas y capitales.'},
    {level:1,prompt:'Para localizar cordilleras y grandes ríos, ¿qué mapa es más adecuado?',answer:'Físico',distractors:['Electoral','Lingüístico','Catastral'],solution:'Los mapas físicos destacan relieve e hidrografía.'},
    {level:2,prompt:'Un mapa colorea cada provincia según su tasa de desempleo. ¿Qué tipo es?',answer:'Temático',distractors:['Físico','Plano urbano','Mapa topográfico exclusivamente'],solution:'Representa espacialmente una variable concreta: el desempleo.'},
    {level:2,prompt:'¿Qué representación usarías para seguir calles, plazas y edificios de un centro histórico?',answer:'Un plano urbano',distractors:['Un mapamundi físico','Un mapa climático continental','Un globo terráqueo'],solution:'El plano urbano ofrece gran detalle a escala local.'},
    {level:3,prompt:'Quieres analizar pendientes para planificar una ruta de montaña. ¿Qué mapa resulta más útil?',answer:'Topográfico',distractors:['Político','Electoral','De husos horarios'],solution:'Las curvas de nivel y cotas de un topográfico permiten interpretar pendientes.'},
    {level:3,prompt:'¿Qué ventaja tiene un mapa temático frente a uno general para estudiar población?',answer:'Destaca directamente la distribución de la variable estudiada',distractors:['Siempre tiene mayor escala','No necesita leyenda','Elimina cualquier simplificación'],solution:'Su diseño se centra en comunicar una variable específica.'},
    {level:4,prompt:'Un investigador compara uso del suelo en 1990 y 2025. ¿Qué serie cartográfica sería más útil?',answer:'Mapas temáticos del uso del suelo de ambas fechas',distractors:['Dos mapas políticos sin fechas','Un único mapa físico','Solo una fotografía de una calle'],solution:'Para analizar cambio temporal se necesitan representaciones comparables de la misma variable.'},
    {level:4,prompt:'¿Por qué ningún tipo de mapa sirve igualmente bien para todas las preguntas geográficas?',answer:'Porque cada mapa selecciona y simplifica información según su propósito',distractors:['Porque los mapas físicos son siempre exactos y los demás no','Porque la escala no influye nunca','Porque un mapa no puede representar datos'],solution:'La cartografía implica seleccionar variables, escala y simbología según la pregunta.'},
  ],
  G01S04: [
    {level:1,prompt:'En una leyenda, un círculo rojo significa hospital. ¿Qué indica un círculo rojo en el mapa?',answer:'Un hospital',distractors:['Una carretera','Una frontera','Una montaña'],solution:'La leyenda asigna significado a símbolos y colores.'},
    {level:1,prompt:'Si el norte está arriba, ¿dónde queda el oeste?',answer:'A la izquierda',distractors:['A la derecha','Abajo','Arriba'],solution:'Con orientación convencional, oeste queda a la izquierda.'},
    {level:2,prompt:'Un mapa usa tonos más oscuros para valores mayores. ¿Qué debes consultar para saber qué rango representa cada tono?',answer:'La leyenda',distractors:['La escala únicamente','El título únicamente','La latitud'],solution:'La leyenda explica la correspondencia entre tonos y valores.'},
    {level:2,prompt:'¿Qué dos elementos necesitas para interpretar un símbolo y convertir una distancia del mapa en kilómetros?',answer:'Leyenda y escala',distractors:['Título y fecha','Norte y latitud','Longitud y altitud'],solution:'La leyenda explica símbolos y la escala convierte distancias.'},
    {level:3,prompt:'Una flecha de norte está inclinada hacia la esquina superior derecha. ¿Qué debes hacer para orientarte?',answer:'Usar esa flecha como referencia y no asumir que arriba es norte',distractors:['Ignorarla y usar siempre la parte superior','Consultar solo la escala','Cambiar la leyenda'],solution:'La orientación real la marca el indicador de norte.'},
    {level:3,prompt:'Dos mapas usan el mismo color azul con significados distintos. ¿Cómo evitas confundirlos?',answer:'Leyendo la leyenda de cada mapa',distractors:['Suponiendo que azul siempre significa río','Usando solo el título','Comparando el tamaño del papel'],solution:'Los símbolos no son universales en todos los mapas; la leyenda del mapa manda.'},
    {level:4,prompt:'Un mapa temático no incluye unidades en la leyenda de colores. ¿Qué problema genera?',answer:'No se pueden interpretar cuantitativamente los valores representados',distractors:['No se puede saber dónde está el norte aunque haya flecha','La escala deja de existir','Las fronteras cambian de posición'],solution:'Sin unidades o rangos, la intensidad de los colores carece de significado cuantitativo claro.'},
    {level:4,prompt:'¿Por qué una buena simbología cartográfica debe ser consistente?',answer:'Para que el lector interprete de la misma forma elementos equivalentes',distractors:['Para evitar usar escala','Para que todos los mapas tengan los mismos colores','Para sustituir el título'],solution:'La consistencia reduce ambigüedad y errores de lectura.'},
  ],
  G02S01: [
    {level:1,prompt:'Una superficie elevada y relativamente llana es una…',answer:'Meseta',distractors:['Llanura','Valle','Delta'],solution:'La meseta combina poca pendiente con altitud elevada.'},
    {level:1,prompt:'Una depresión alargada entre montañas, a menudo recorrida por un río, es un…',answer:'Valle',distractors:['Cabo','Acantilado','Istmo'],solution:'Los valles ocupan zonas bajas entre relieves elevados.'},
    {level:2,prompt:'¿Qué forma costera penetra en el mar y está rodeada de agua por tres lados?',answer:'Península',distractors:['Golfo','Valle','Meseta'],solution:'Una península está unida al continente por una franja y rodeada de agua en gran parte.'},
    {level:2,prompt:'¿Qué diferencia básica existe entre una llanura y una meseta?',answer:'La meseta se sitúa a mayor altitud',distractors:['La llanura siempre tiene montañas','La meseta siempre está junto al mar','La llanura nunca tiene ríos'],solution:'Ambas pueden ser planas, pero difieren principalmente en altitud.'},
    {level:3,prompt:'Un relieve con fuertes pendientes, cumbres alineadas y gran desnivel corresponde mejor a una…',answer:'Cordillera',distractors:['Llanura','Delta','Depresión litoral'],solution:'Una cordillera reúne montañas enlazadas con fuertes desniveles.'},
    {level:3,prompt:'¿Qué proceso puede transformar lentamente una montaña reduciendo sus pendientes?',answer:'La erosión',distractors:['La fotosíntesis','La urbanización únicamente','La rotación terrestre'],solution:'La erosión desgasta y transporta materiales, modificando el relieve.'},
    {level:4,prompt:'Una costa rocosa presenta una pared casi vertical originada por erosión marina. ¿Qué forma es?',answer:'Acantilado',distractors:['Delta','Llanura aluvial','Meseta interior'],solution:'Los acantilados son escarpes abruptos junto al mar.'},
    {level:4,prompt:'¿Por qué la misma altitud no implica necesariamente la misma forma del relieve?',answer:'Porque importan también pendiente, extensión y relación con el entorno',distractors:['Porque la altitud nunca se mide','Porque todo relieve elevado es una cordillera','Porque las formas dependen solo del clima'],solution:'La clasificación del relieve considera varios rasgos morfológicos.'},
  ],
  G02S02: [
    {level:1,prompt:'¿Qué océano está al oeste de Europa y África?',answer:'Atlántico',distractors:['Índico','Pacífico','Ártico'],solution:'El Atlántico separa Europa-África de América.'},
    {level:1,prompt:'¿Qué continente ocupa el Polo Sur?',answer:'Antártida',distractors:['Asia','Europa','África'],solution:'La Antártida rodea el Polo Sur.'},
    {level:2,prompt:'¿Qué océano se extiende entre África, Asia y Australia?',answer:'Índico',distractors:['Atlántico','Ártico','Pacífico oriental'],solution:'El océano Índico ocupa esa gran cuenca intercontinental.'},
    {level:2,prompt:'¿Qué continente está al sur de Europa y separado en gran parte por el Mediterráneo?',answer:'África',distractors:['Asia','Oceanía','Antártida'],solution:'África se sitúa al sur de Europa.'},
    {level:3,prompt:'Viajas de la costa occidental de América hacia Asia por la ruta oceánica más directa. ¿Qué océano cruzas?',answer:'Pacífico',distractors:['Atlántico','Índico','Mediterráneo'],solution:'El Pacífico se sitúa entre América y Asia-Oceanía.'},
    {level:3,prompt:'¿Qué continente está atravesado por el ecuador y posee territorio en los hemisferios norte y sur?',answer:'África',distractors:['Europa','Antártida','Solo Oceanía'],solution:'El ecuador cruza África aproximadamente por su zona central.'},
    {level:4,prompt:'¿Por qué los límites entre Europa y Asia son menos evidentes físicamente que entre otros continentes?',answer:'Porque forman una gran masa terrestre continua y parte del límite es convencional',distractors:['Porque Europa es una isla','Porque Asia no tiene montañas','Porque no existen mares entre ambos'],solution:'Europa y Asia integran Eurasia y su separación combina criterios físicos e históricos.'},
    {level:4,prompt:'Un mapa centrado en el Pacífico puede hacer que América aparezca a la derecha y Asia a la izquierda. ¿Qué demuestra?',answer:'Que la posición visual depende de la proyección y del centro elegido',distractors:['Que los continentes cambian de lugar','Que el Pacífico desaparece','Que las coordenadas dejan de funcionar'],solution:'La representación plana puede centrarse en distintas longitudes sin alterar la geografía real.'},
  ],
  G02S03: [
    {level:1,prompt:'¿Cómo se llama un río que desemboca en otro mayor?',answer:'Afluente',distractors:['Delta','Acuífero','Estuario'],solution:'Un afluente aporta agua a un río principal.'},
    {level:1,prompt:'¿Qué es la desembocadura de un río?',answer:'El lugar donde vierte sus aguas',distractors:['El lugar donde nace','La línea que separa cuencas','La parte más alta de una montaña'],solution:'La desembocadura es el final del curso fluvial.'},
    {level:2,prompt:'¿Qué es una cuenca hidrográfica?',answer:'El territorio cuyas aguas drenan hacia un mismo sistema fluvial',distractors:['Solo el cauce principal','Una reserva subterránea aislada','Una isla entre dos mares'],solution:'Incluye todas las laderas y cursos que aportan agua al mismo río o salida.'},
    {level:2,prompt:'Si aumenta mucho la lluvia en la cabecera de una cuenca, ¿qué puede ocurrir aguas abajo?',answer:'Puede aumentar el caudal',distractors:['El río deja de tener desembocadura','La cuenca cambia de continente','El agua fluye cuesta arriba'],solution:'Más aportes en la cuenca pueden traducirse en mayor caudal río abajo.'},
    {level:3,prompt:'¿Qué diferencia básica hay entre delta y estuario?',answer:'El delta acumula sedimentos formando brazos; el estuario es una desembocadura ensanchada influida por el mar',distractors:['Son exactamente lo mismo','El estuario solo aparece en montañas','El delta es agua subterránea'],solution:'Son dos formas distintas de desembocadura condicionadas por sedimentos y dinámica marina.'},
    {level:3,prompt:'¿Por qué una divisoria de aguas suele seguir zonas elevadas?',answer:'Porque el agua fluye por gravedad hacia lados opuestos',distractors:['Porque los ríos suben montañas','Porque solo existe en costas','Porque marca fronteras políticas obligatoriamente'],solution:'Las crestas separan direcciones de escorrentía.'},
    {level:4,prompt:'Un acuífero se recarga lentamente y se extrae agua más rápido de lo que entra. ¿Qué riesgo existe?',answer:'Descenso progresivo de las reservas subterráneas',distractors:['Aumento ilimitado del caudal','Formación inmediata de una cordillera','Desaparición de la evaporación'],solution:'La extracción superior a la recarga provoca sobreexplotación.'},
    {level:4,prompt:'Una ciudad impermeabiliza grandes superficies de una cuenca. ¿Qué efecto puede aumentar durante lluvias intensas?',answer:'La escorrentía rápida y el riesgo de inundación',distractors:['La infiltración profunda','La recarga del acuífero necesariamente','La evaporación hasta eliminar toda lluvia'],solution:'El pavimento reduce infiltración y acelera el agua hacia los cauces.'},
  ],
  G02S04: [
    {level:1,prompt:'¿Por qué las llanuras suelen facilitar carreteras y ferrocarriles?',answer:'Porque tienen pendientes suaves',distractors:['Porque no existe suelo','Porque siempre están deshabitadas','Porque obligan a construir túneles'],solution:'Menores desniveles reducen dificultades técnicas de construcción.'},
    {level:1,prompt:'¿Qué ventaja histórica ofrecían muchos valles fluviales a los asentamientos?',answer:'Agua, suelos fértiles y vías de comunicación',distractors:['Ausencia total de inundaciones','Clima siempre idéntico','Falta de recursos'],solution:'Los valles concentran recursos y corredores naturales.'},
    {level:2,prompt:'Una ciudad crece sobre una llanura de inundación. ¿Qué riesgo debe considerar?',answer:'Desbordamientos del río',distractors:['Erupciones volcánicas por definición','Glaciaciones anuales','Ausencia de agua'],solution:'Las llanuras de inundación forman parte del espacio natural de expansión del río.'},
    {level:2,prompt:'¿Por qué un puerto natural protegido puede favorecer una ciudad?',answer:'Facilita transporte marítimo y abrigo de embarcaciones',distractors:['Impide cualquier comercio','Elimina la necesidad de vías terrestres','Garantiza que nunca haya temporales'],solution:'Un buen abrigo costero mejora operaciones portuarias.'},
    {level:3,prompt:'¿Qué decisión reduce mejor el riesgo de deslizamientos en una ladera urbanizada?',answer:'Evitar zonas inestables y conservar drenaje y vegetación',distractors:['Eliminar toda vegetación','Sobrecargar la pendiente sin estudio','Bloquear todos los cauces'],solution:'Planificación, drenaje y cubierta vegetal ayudan a estabilizar laderas.'},
    {level:3,prompt:'Una cordillera separa dos regiones. ¿Qué infraestructura puede reducir su efecto barrera?',answer:'Túneles y pasos de montaña bien planificados',distractors:['Deltas artificiales','Eliminar la escala de los mapas','Aumentar la pendiente'],solution:'Las rutas aprovechan pasos o atraviesan el relieve con túneles.'},
    {level:4,prompt:'¿Por qué la accesibilidad física puede influir en la densidad de población?',answer:'Porque condiciona transporte, costes, servicios y actividades económicas',distractors:['Porque determina por sí sola toda la población','Porque el relieve no influye nunca','Porque las montañas prohíben cualquier asentamiento'],solution:'El relieve es un factor entre varios que afecta a la facilidad de ocupación y conexión.'},
    {level:4,prompt:'Un valle fértil atrae agricultura intensiva, pero también sufre inundaciones. ¿Qué enfoque es más razonable?',answer:'Aprovechar suelos fértiles con ordenación que respete zonas de riesgo',distractors:['Construir sin considerar el río','Abandonar cualquier actividad humana','Canalizar todo el sistema sin evaluar impactos'],solution:'La gestión territorial debe equilibrar oportunidades y riesgos.'},
  ],
  G03S01: [
    {level:1,prompt:'“Esta tarde habrá tormentas” describe…',answer:'El tiempo atmosférico',distractors:['El clima','La latitud','La altitud'],solution:'Es una condición prevista para un momento concreto.'},
    {level:1,prompt:'“Los inviernos suelen ser suaves y lluviosos” describe…',answer:'El clima',distractors:['El tiempo de hoy','Una coordenada','Una escala'],solution:'Habla de un patrón habitual a largo plazo.'},
    {level:2,prompt:'¿Qué variable se mide con un termómetro?',answer:'Temperatura',distractors:['Precipitación','Velocidad del viento','Presión únicamente en mapas'],solution:'El termómetro mide temperatura del aire.'},
    {level:2,prompt:'¿Por qué un día frío no contradice necesariamente un clima cálido?',answer:'Porque el clima se define con patrones de muchos años, no con un día aislado',distractors:['Porque clima y tiempo son idénticos','Porque la temperatura no importa','Porque los días fríos no existen'],solution:'La variabilidad diaria puede incluir episodios alejados de la media climática.'},
    {level:3,prompt:'Una estación meteorológica registra 20 años de datos. ¿Qué puede estudiarse mejor con esa serie?',answer:'Patrones climáticos y su variabilidad',distractors:['Solo el tiempo de mañana','La longitud geográfica','La edad de las rocas'],solution:'Las series largas permiten calcular medias, extremos y tendencias.'},
    {level:3,prompt:'¿Qué combinación describe mejor el tiempo actual?',answer:'Temperatura, precipitación, viento y nubosidad observados ahora',distractors:['Media de 30 años únicamente','Latitud y longitud','Población y relieve'],solution:'El tiempo es el estado de la atmósfera en un momento dado.'},
    {level:4,prompt:'¿Por qué una tendencia de varias décadas es más relevante para clima que un récord de un solo día?',answer:'Porque el clima se evalúa mediante patrones persistentes y estadísticos',distractors:['Porque los récords diarios nunca son reales','Porque el clima no usa temperatura','Porque una década equivale a un día'],solution:'Las tendencias sostenidas distinguen cambio climático de variabilidad puntual.'},
    {level:4,prompt:'Dos ciudades tienen la misma temperatura hoy. ¿Se puede concluir que tienen el mismo clima?',answer:'No, hacen falta patrones de temperatura, precipitación y otras variables durante años',distractors:['Sí, una medida basta','Sí, si están en el mismo país','No, porque el clima solo depende de la altitud'],solution:'Un dato puntual no caracteriza el clima completo.'},
  ],
  G03S02: [
    {level:1,prompt:'¿Qué factor suele hacer más frescas las zonas altas?',answer:'La altitud',distractors:['La escala','La leyenda','La longitud del nombre'],solution:'La temperatura suele disminuir con la altitud.'},
    {level:1,prompt:'¿Qué factor explica que las costas tengan temperaturas más moderadas?',answer:'La influencia del mar',distractors:['La ausencia de atmósfera','La escala cartográfica','El color del suelo únicamente'],solution:'El agua se calienta y enfría lentamente y suaviza extremos térmicos.'},
    {level:2,prompt:'¿Por qué cerca del ecuador suele recibirse más energía solar anual?',answer:'Los rayos llegan más perpendiculares',distractors:['La Tierra está más cerca del Sol allí','No existe noche','La altitud siempre es mayor'],solution:'La geometría de incidencia concentra más energía por unidad de superficie.'},
    {level:2,prompt:'Dos pueblos están a igual latitud; uno está junto al mar y otro en el interior. ¿Cuál suele tener menor amplitud térmica?',answer:'El costero',distractors:['El interior','Ambos siempre igual','El que esté más al este'],solution:'La influencia marina modera máximas y mínimas.'},
    {level:3,prompt:'Una montaña obliga a ascender aire húmedo. ¿Qué puede ocurrir en la ladera de barlovento?',answer:'Más nubosidad y precipitación',distractors:['Desaparece toda humedad','Aumenta siempre la temperatura','No existe efecto del relieve'],solution:'El aire ascendente se enfría y puede condensar vapor de agua.'},
    {level:3,prompt:'¿Qué combinación suele producir un clima más frío?',answer:'Mayor latitud y mayor altitud',distractors:['Menor latitud y menor altitud','Proximidad al ecuador y al nivel del mar','Solo una longitud occidental'],solution:'Alejarse del ecuador y ascender suelen reducir temperaturas.'},
    {level:4,prompt:'Dos valles cercanos tienen precipitaciones muy distintas a ambos lados de una cordillera. ¿Qué fenómeno puede explicarlo?',answer:'Sombra pluviométrica',distractors:['Cambio de huso horario','Escala del mapa','Movimiento de rotación únicamente'],solution:'La ladera de sotavento puede recibir aire más seco tras precipitar en barlovento.'},
    {level:4,prompt:'¿Por qué la latitud no basta para predecir el clima de un lugar?',answer:'Porque también influyen altitud, mar, relieve y circulación atmosférica',distractors:['Porque la latitud no se puede medir','Porque todos los lugares de igual latitud tienen idéntico clima','Porque el clima depende solo de la longitud'],solution:'El clima resulta de varios factores que interactúan.'},
  ],
  G03S03: [
    {level:1,prompt:'En un climograma, ¿qué suelen mostrar las barras?',answer:'Precipitación',distractors:['Latitud','Población','Altitud'],solution:'Convencionalmente las barras representan precipitación mensual.'},
    {level:1,prompt:'En un climograma, ¿qué suele mostrar la línea?',answer:'Temperatura media mensual',distractors:['Fronteras','Densidad de población','Caudal exacto de un río'],solution:'La línea representa normalmente la evolución térmica mensual.'},
    {level:2,prompt:'Si las barras son muy bajas en julio y agosto, ¿qué indica?',answer:'Precipitaciones escasas en esos meses',distractors:['Temperaturas necesariamente bajas','Altitud creciente','Más horas de noche por definición'],solution:'La altura de las barras refleja cantidad de precipitación.'},
    {level:2,prompt:'Una línea térmica alcanza su máximo en julio. ¿Qué puede deducirse directamente?',answer:'Julio es el mes con mayor temperatura media del gráfico',distractors:['Julio es el mes más lluvioso','La ciudad está en el ecuador','Nunca llueve en invierno'],solution:'El máximo de la línea corresponde al mayor valor térmico mensual.'},
    {level:3,prompt:'Un climograma muestra lluvias todo el año y poca diferencia térmica entre estaciones. ¿Qué rasgo destaca?',answer:'Regularidad de precipitaciones y baja amplitud térmica',distractors:['Sequía estival extrema','Gran amplitud térmica','Ausencia de clima'],solution:'La lectura combina distribución de lluvias y variación de temperaturas.'},
    {level:3,prompt:'¿Cómo se calcula aproximadamente la amplitud térmica anual de un climograma?',answer:'Restando la temperatura media del mes más frío a la del más cálido',distractors:['Sumando todas las precipitaciones','Dividiendo latitud entre longitud','Restando lluvia máxima y mínima'],solution:'La amplitud térmica mide la diferencia entre extremos térmicos mensuales.'},
    {level:4,prompt:'Dos climogramas tienen la misma precipitación anual, pero uno concentra casi toda la lluvia en invierno. ¿Son climáticamente equivalentes?',answer:'No, la distribución estacional también importa',distractors:['Sí, el total anual es lo único relevante','Sí, si tienen la misma escala','No, porque la lluvia anual no se puede sumar'],solution:'La estacionalidad de las precipitaciones es un rasgo climático fundamental.'},
    {level:4,prompt:'¿Qué error supone comparar dos climogramas sin mirar las escalas de los ejes?',answer:'Podrías interpretar como iguales o distintas variaciones que están representadas con escalas diferentes',distractors:['La latitud cambiaría','Los meses se ordenarían solos','Las barras dejarían de representar lluvia'],solution:'La escala visual condiciona la percepción de magnitudes y variabilidad.'},
  ],
  G03S04: [
    {level:1,prompt:'¿Qué medida ayuda a reducir vulnerabilidad ante una sequía?',answer:'Usar el agua de forma eficiente y planificar reservas',distractors:['Aumentar fugas','Eliminar embalses sin alternativa','Impermeabilizar todo el suelo'],solution:'La eficiencia y planificación reducen presión sobre recursos escasos.'},
    {level:1,prompt:'¿Qué riesgo aumenta durante una ola de calor intensa?',answer:'Problemas de salud por estrés térmico',distractors:['Congelación de ríos por definición','Glaciaciones inmediatas','Ausencia total de evaporación'],solution:'El calor extremo puede afectar especialmente a personas vulnerables.'},
    {level:2,prompt:'¿Qué acción urbana puede reducir temperaturas locales durante episodios calurosos?',answer:'Aumentar sombra y vegetación urbana',distractors:['Eliminar árboles','Cubrir todo con asfalto oscuro','Reducir zonas verdes'],solution:'Sombra y evapotranspiración ayudan a moderar el calor urbano.'},
    {level:2,prompt:'Una zona costera espera subida del nivel del mar. ¿Qué medida es adaptación?',answer:'Planificar usos del suelo y proteger o retirar infraestructuras vulnerables',distractors:['Aumentar emisiones','Construir sin evaluar cotas','Eliminar sistemas de alerta'],solution:'Adaptarse implica reducir exposición y daños esperados.'},
    {level:3,prompt:'¿Qué diferencia hay entre mitigación y adaptación climática?',answer:'Mitigación reduce causas del cambio; adaptación reduce sus impactos',distractors:['Son exactamente lo mismo','Mitigación solo actúa tras desastres','Adaptación elimina todas las emisiones'],solution:'Son estrategias complementarias con objetivos distintos.'},
    {level:3,prompt:'¿Por qué una ciudad con mucha superficie impermeable puede sufrir más inundaciones repentinas?',answer:'Porque el agua infiltra menos y escurre más rápido',distractors:['Porque deja de llover','Porque el suelo absorbe más','Porque disminuye todo caudal'],solution:'La impermeabilización acelera la escorrentía superficial.'},
    {level:4,prompt:'Una región depende de un único cultivo sensible a sequías. ¿Qué estrategia aumenta resiliencia?',answer:'Diversificar cultivos y mejorar gestión de agua y suelo',distractors:['Depender aún más de una sola variedad','Eliminar toda cobertura del suelo','Ignorar previsiones climáticas'],solution:'La diversificación reduce exposición a un único fallo climático.'},
    {level:4,prompt:'¿Por qué el riesgo climático no depende solo del fenómeno físico?',answer:'También depende de exposición y vulnerabilidad de población e infraestructuras',distractors:['Porque el clima no produce riesgos','Porque solo importa la riqueza','Porque toda población responde igual'],solution:'Riesgo combina amenaza, exposición y vulnerabilidad.'},
  ],
}

const FRAMES = [
  (p:string)=>p,
  (p:string)=>`Analiza el mapa o la situación: ${p}`,
  (p:string)=>`Aplica tus conocimientos de geografía: ${p}`,
  (p:string)=>`Reto geográfico: ${p}`,
] as const

function rotate<T>(items:T[], shift:number){ const n=((shift%items.length)+items.length)%items.length; return items.slice(n).concat(items.slice(0,n)) }

export function generateGeographyLongTermVariant(skill: SkillMeta, difficulty: number, seed: number): GeneratedQuestion | null {
  const cards = BANK[skill.id]
  if (!cards?.length) return null
  const eligible = cards.filter(card => Math.abs(card.level - difficulty) <= 1)
  const pool = eligible.length ? eligible : cards
  const normalized = seed >>> 0
  const card = pool[normalized % pool.length]
  const frame = FRAMES[Math.floor(normalized / pool.length) % FRAMES.length]
  const options = rotate([card.answer, ...card.distractors], normalized + difficulty)
  return { skillId: skill.id, label: skill.name, difficulty, seed, prompt: frame(card.prompt), options, answerIndex: options.indexOf(card.answer), solution: card.solution, tags:[skill.generator_key,'geography_history','geography_long_term'] }
}

export function geographyLongTermSkillIds(){ return Object.keys(BANK) }
export function geographyLongTermVariantCount(skillId:string){ return (BANK[skillId]?.length ?? 0) * FRAMES.length }
