export type GeologyDepthCard = {
  level: number
  prompt: string
  answer: string
  distractors: [string, string, string]
  solution: string
}

const SUPPLEMENT: Record<string, GeologyDepthCard[]> = {
  B02S01: [
    { level: 1, prompt: 'Una nube está formada por pequeñas gotas de agua suspendidas en el aire. ¿Qué dos sistemas terrestres aparecen de forma directa?', answer: 'Atmósfera e hidrosfera', distractors: ['Geosfera y biosfera', 'Geosfera y núcleo', 'Biosfera y manto'], solution: 'El aire pertenece a la atmósfera y las gotas de agua forman parte de la hidrosfera.' },
    { level: 1, prompt: 'Un pez vive en un lago. ¿Qué sistemas se relacionan de forma más evidente?', answer: 'Biosfera e hidrosfera', distractors: ['Atmósfera y geosfera', 'Geosfera y manto', 'Atmósfera y núcleo'], solution: 'El pez es un ser vivo de la biosfera y el lago pertenece a la hidrosfera.' },
    { level: 1, prompt: 'El suelo mineral de una ladera pertenece principalmente a…', answer: 'La geosfera', distractors: ['La atmósfera', 'La hidrosfera', 'La biosfera'], solution: 'El suelo contiene materiales minerales derivados de la parte sólida de la Tierra.' },
    { level: 1, prompt: 'El oxígeno que respiramos forma parte de…', answer: 'La atmósfera', distractors: ['La geosfera', 'La hidrosfera', 'El manto'], solution: 'El oxígeno gaseoso del aire es un componente de la atmósfera.' },
    { level: 1, prompt: 'Un bosque con árboles, hongos y animales pertenece principalmente a…', answer: 'La biosfera', distractors: ['La geosfera', 'La atmósfera', 'La hidrosfera'], solution: 'La biosfera reúne los seres vivos y las zonas donde desarrollan su actividad.' },
    { level: 2, prompt: 'La lluvia se infiltra por grietas de una roca y alimenta un acuífero. ¿Qué interacción destaca?', answer: 'La hidrosfera circula a través de la geosfera', distractors: ['La biosfera sustituye a la atmósfera', 'La geosfera se convierte en hidrosfera', 'La atmósfera deja de intervenir en el ciclo del agua'], solution: 'El agua de la hidrosfera se mueve por poros y fracturas de materiales de la geosfera.' },
    { level: 2, prompt: 'Una duna avanza por acción del viento. ¿Qué sistemas interactúan directamente?', answer: 'Atmósfera y geosfera', distractors: ['Biosfera e hidrosfera', 'Hidrosfera y núcleo', 'Biosfera y manto'], solution: 'El viento es movimiento de aire de la atmósfera y desplaza arena de la geosfera.' },
    { level: 2, prompt: 'Las raíces absorben agua del suelo. ¿Qué tres sistemas aparecen de forma inmediata?', answer: 'Biosfera, hidrosfera y geosfera', distractors: ['Atmósfera, núcleo y manto', 'Solo biosfera e hidrosfera', 'Geosfera y atmósfera únicamente'], solution: 'La planta pertenece a la biosfera, el agua a la hidrosfera y el suelo mineral a la geosfera.' },
    { level: 2, prompt: 'El oleaje desgasta un acantilado. ¿Qué interacción explica el proceso?', answer: 'La hidrosfera erosiona materiales de la geosfera', distractors: ['La geosfera evapora la hidrosfera', 'La biosfera transforma el océano en roca', 'La atmósfera forma directamente magma'], solution: 'El agua marina y el oleaje actúan sobre roca de la costa y provocan erosión.' },
    { level: 2, prompt: 'La evaporación de un lago incorpora vapor de agua al aire. ¿Qué sistemas se conectan?', answer: 'Hidrosfera y atmósfera', distractors: ['Geosfera y biosfera', 'Manto y núcleo', 'Biosfera y geosfera únicamente'], solution: 'El agua pasa de la hidrosfera a la atmósfera en forma de vapor.' },
    { level: 3, prompt: 'Tras un incendio desaparece gran parte de la vegetación y una tormenta arrastra mucho más suelo. ¿Qué cadena causal es más razonable?', answer: 'Cambio en biosfera → mayor acción de hidrosfera sobre geosfera', distractors: ['Cambio en geosfera → desaparición de toda la atmósfera', 'Cambio en núcleo → lluvia inmediata', 'Cambio en hidrosfera → formación directa de seres vivos'], solution: 'La pérdida de cubierta vegetal deja el suelo más expuesto a la escorrentía y erosión.' },
    { level: 3, prompt: 'Una erupción submarina calienta agua cercana y libera gases. ¿Qué sistemas participan de forma directa?', answer: 'Geosfera, hidrosfera y atmósfera', distractors: ['Solo biosfera y geosfera', 'Núcleo y biosfera únicamente', 'Solo hidrosfera'], solution: 'La actividad volcánica procede de la geosfera, afecta al agua y libera gases que pueden alcanzar la atmósfera.' },
    { level: 3, prompt: 'En una marisma, sedimentos, agua salobre y plantas se influyen mutuamente. ¿Qué idea ilustra?', answer: 'Los sistemas terrestres intercambian materia y energía', distractors: ['Cada sistema funciona sin relación con los demás', 'La biosfera solo existe lejos del agua', 'La geosfera no cambia en la superficie'], solution: 'Sedimentos, agua y seres vivos pertenecen a sistemas distintos que interactúan continuamente.' },
    { level: 3, prompt: 'Una tormenta de polvo reduce la luz que reciben plantas de una región. ¿Qué secuencia conecta mejor los sistemas?', answer: 'Geosfera → atmósfera → biosfera', distractors: ['Hidrosfera → núcleo → biosfera', 'Biosfera → manto → atmósfera', 'Atmósfera → núcleo → geosfera'], solution: 'El polvo procede del suelo, pasa al aire y puede modificar las condiciones de los seres vivos.' },
    { level: 4, prompt: 'En una cuenca deforestada aumenta la escorrentía y el río transporta más sedimentos. ¿Qué explicación integra mejor el sistema?', answer: 'La pérdida de biosfera modifica la circulación de agua y acelera la erosión de la geosfera', distractors: ['La pérdida de árboles elimina la gravedad de la cuenca', 'Los sedimentos aparecen sin proceder del terreno', 'El río deja de pertenecer a la hidrosfera cuando lleva barro'], solution: 'La vegetación regula infiltración y estabilidad del suelo; al disminuir, cambian las interacciones entre biosfera, hidrosfera y geosfera.' },
    { level: 5, prompt: 'Un periodo de calentamiento reduce nieve estacional, adelanta el caudal de deshielo y altera la vegetación de montaña. ¿Qué interpretación sistémica es mejor?', answer: 'Una variación atmosférica puede propagarse por hidrosfera, biosfera y geosfera superficial', distractors: ['Solo cambia la atmósfera porque la nieve no pertenece a otro sistema', 'La vegetación cambia sin relación con agua o temperatura', 'La geosfera impide cualquier efecto en los demás sistemas'], solution: 'Los cambios de temperatura afectan al agua almacenada como nieve, al régimen de caudales, a los seres vivos y a procesos superficiales.' },
  ],
  B02S02: [
    { level: 1, prompt: 'Una muestra natural tiene estructura cristalina y composición química característica. ¿Cómo se clasifica?', answer: 'Como mineral', distractors: ['Como roca sedimentaria necesariamente', 'Como fósil', 'Como material artificial'], solution: 'Los minerales son sustancias naturales con composición y estructura características.' },
    { level: 1, prompt: 'Una roca formada por cuarzo, feldespato y mica contiene…', answer: 'Varios minerales', distractors: ['Un solo elemento químico', 'Solo restos orgánicos', 'Únicamente vidrio artificial'], solution: 'Una roca puede ser un agregado de diferentes minerales.' },
    { level: 1, prompt: '¿Qué propiedad describe la resistencia de un mineral a ser rayado?', answer: 'Dureza', distractors: ['Brillo', 'Color', 'Exfoliación'], solution: 'La dureza compara la resistencia de un mineral frente al rayado.' },
    { level: 1, prompt: '¿Qué propiedad se observa al ver si una superficie mineral parece metálica, vítrea o mate?', answer: 'Brillo', distractors: ['Dureza', 'Raya', 'Magnetismo'], solution: 'El brillo describe cómo refleja la luz la superficie del mineral.' },
    { level: 1, prompt: 'El color del polvo que deja un mineral al frotarlo sobre una placa se llama…', answer: 'Raya', distractors: ['Brillo', 'Exfoliación', 'Densidad'], solution: 'La raya es el color del polvo del mineral y puede ser más diagnóstica que su color externo.' },
    { level: 2, prompt: 'Una muestra raya el vidrio pero no puede ser rayada fácilmente con una moneda. ¿Qué podemos inferir?', answer: 'Tiene una dureza relativamente alta', distractors: ['Tiene brillo necesariamente metálico', 'Es una roca sedimentaria por definición', 'Carece de estructura cristalina'], solution: 'La capacidad de rayar materiales y resistir el rayado permite estimar dureza.' },
    { level: 2, prompt: 'Un mineral se separa repetidamente en láminas planas. ¿Qué propiedad destaca?', answer: 'Exfoliación', distractors: ['Raya', 'Densidad atmosférica', 'Erosión'], solution: 'La exfoliación es la tendencia a romperse según planos definidos de la estructura cristalina.' },
    { level: 2, prompt: 'Dos muestras tienen el mismo color, pero una raya el vidrio y la otra no. ¿Qué conclusión es más prudente?', answer: 'Pueden ser minerales distintos y conviene comparar más propiedades', distractors: ['Son necesariamente el mismo mineral', 'El color invalida la prueba de dureza', 'Ambas son rocas porque tienen distinto comportamiento'], solution: 'El color no basta para identificar; la dureza aporta evidencia adicional.' },
    { level: 2, prompt: 'Una roca presenta capas con granos de arena cementados. ¿Qué origen es más probable?', answer: 'Sedimentario', distractors: ['Ígneo por enfriamiento de lava', 'Metamórfico por recristalización completa', 'Artificial por fabricación'], solution: 'La acumulación y cementación de sedimentos forma muchas rocas sedimentarias.' },
    { level: 2, prompt: 'Una roca volcánica tiene pequeños cristales porque se enfrió rápidamente. ¿A qué grupo pertenece?', answer: 'Ígneas o magmáticas', distractors: ['Sedimentarias', 'Metamórficas', 'Rocas exclusivamente orgánicas'], solution: 'Las rocas ígneas se originan al solidificarse magma o lava.' },
    { level: 3, prompt: 'Una roca muestra bandas minerales orientadas y no se observan sedimentos sueltos. ¿Qué proceso puede explicarlo?', answer: 'Metamorfismo por presión y temperatura', distractors: ['Evaporación del agua de lluvia', 'Sedimentación reciente sin enterramiento', 'Enfriamiento de lava en la superficie únicamente'], solution: 'La presión y temperatura pueden reorganizar minerales y producir foliación o bandeado metamórfico.' },
    { level: 3, prompt: 'Para distinguir calcita de cuarzo, ¿qué plan de identificación es mejor?', answer: 'Combinar dureza y otras pruebas características', distractors: ['Usar solo el tamaño de la muestra', 'Elegir por el lugar donde se encontró sin examinarla', 'Mirar únicamente si parece bonita'], solution: 'Una identificación fiable usa varias propiedades físicas y, cuando procede, pruebas específicas.' },
    { level: 3, prompt: 'Una muestra tiene cristales grandes visibles y encajados entre sí. ¿Qué historia es compatible?', answer: 'Enfriamiento lento de magma en profundidad', distractors: ['Sedimentación instantánea de arena en superficie', 'Formación a partir de hojas de árboles sin mineralización', 'Disolución completa de la roca en aire seco'], solution: 'El enfriamiento lento permite crecer cristales grandes en rocas ígneas plutónicas.' },
    { level: 3, prompt: 'Una roca contiene fósiles y estratos bien definidos. ¿Qué origen es el más coherente?', answer: 'Sedimentario', distractors: ['Ígneo intrusivo', 'Metamórfico de alto grado', 'Magma sin solidificar'], solution: 'Los fósiles y estratos suelen conservarse en rocas sedimentarias formadas por deposición y litificación.' },
    { level: 4, prompt: 'Una muestra negra se parece visualmente a otra, pero tiene distinta dureza, densidad y raya. ¿Qué conclusión científica es mejor?', answer: 'El parecido de color no basta para considerarlas el mismo mineral', distractors: ['El color negro demuestra que su composición es idéntica', 'La densidad no aporta información en minerales', 'Si se encontraron juntas deben ser el mismo material'], solution: 'La identificación se apoya en un conjunto de propiedades, no en una apariencia aislada.' },
    { level: 5, prompt: 'Se identifican minerales de una roca y se observa su textura antes de clasificarla. ¿Por qué es un método sólido?', answer: 'Porque composición y textura aportan evidencias complementarias sobre origen e historia', distractors: ['Porque cualquier roca con cristales tiene exactamente el mismo origen', 'Porque la textura sustituye siempre a todas las demás observaciones', 'Porque conocer un único color determina el tipo de roca'], solution: 'La clasificación de rocas mejora cuando se combinan composición mineralógica y rasgos texturales.' },
  ],
  B02S03: [
    { level: 1, prompt: 'La lava se enfría en la superficie y se solidifica. ¿Qué tipo de roca puede formarse?', answer: 'Ígnea volcánica', distractors: ['Sedimentaria detrítica', 'Metamórfica por presión', 'Sedimento sin consolidar'], solution: 'La solidificación rápida de lava en superficie origina rocas ígneas volcánicas.' },
    { level: 1, prompt: 'Arena y barro se depositan, se compactan y se cementan. ¿Qué roca se forma?', answer: 'Sedimentaria', distractors: ['Ígnea', 'Magma', 'Metamórfica por fusión'], solution: 'La compactación y cementación de sedimentos produce roca sedimentaria.' },
    { level: 1, prompt: 'Una roca cambia por presión y temperatura sin fundirse. ¿Qué transformación ocurre?', answer: 'Metamorfismo', distractors: ['Sedimentación', 'Cristalización de lava', 'Evaporación'], solution: 'El metamorfismo altera una roca en estado sólido por presión, temperatura y fluidos.' },
    { level: 1, prompt: '¿Qué material se obtiene cuando una roca se funde?', answer: 'Magma', distractors: ['Sedimento', 'Suelo vegetal', 'Roca sedimentaria ya cementada'], solution: 'La fusión transforma material rocoso sólido en magma.' },
    { level: 1, prompt: '¿Qué proceso produce fragmentos que pueden convertirse después en sedimentos?', answer: 'Meteorización', distractors: ['Solidificación del magma', 'Metamorfismo profundo', 'Cristalización en una cámara magmática'], solution: 'La meteorización descompone o altera rocas en la superficie y genera partículas.' },
    { level: 2, prompt: 'Una roca ígnea queda expuesta, se erosiona y sus fragmentos se depositan en un lago. ¿Cuál es el siguiente paso para formar roca sedimentaria?', answer: 'Compactación y cementación', distractors: ['Fusión inmediata', 'Metamorfismo antes de enterrarse', 'Evaporación de los minerales'], solution: 'Los sedimentos depositados deben litificarse mediante compactación y cementación.' },
    { level: 2, prompt: 'Una roca sedimentaria se entierra a gran profundidad, aumenta la presión y no llega a fundirse. ¿En qué puede transformarse?', answer: 'En roca metamórfica', distractors: ['En magma necesariamente', 'En sedimento suelto', 'En agua subterránea'], solution: 'Presión y temperatura sin fusión pueden producir metamorfismo.' },
    { level: 2, prompt: 'El magma asciende y se enfría lentamente antes de llegar a la superficie. ¿Qué resultado es probable?', answer: 'Una roca ígnea plutónica con cristales relativamente grandes', distractors: ['Una roca sedimentaria con fósiles recientes', 'Una duna de arena', 'Una roca sin minerales'], solution: 'El enfriamiento lento en profundidad favorece el crecimiento de cristales grandes.' },
    { level: 2, prompt: 'Una roca metamórfica aflora por levantamiento tectónico. ¿Qué proceso superficial puede iniciar su camino hacia sedimentos?', answer: 'Meteorización y erosión', distractors: ['Fusión del núcleo', 'Cristalización de magma sin fundirse', 'Compactación antes de fragmentarse'], solution: 'Una vez expuesta, cualquier roca puede meteorizase y erosionarse.' },
    { level: 2, prompt: '¿Qué secuencia conduce correctamente de sedimento a roca metamórfica?', answer: 'Compactación y cementación → enterramiento → presión y temperatura', distractors: ['Fusión → evaporación → fotosíntesis', 'Erosión → magma → lluvia', 'Solidificación → deshielo → combustión'], solution: 'Primero el sedimento forma roca sedimentaria y después puede metamorfizarse al enterrarse.' },
    { level: 3, prompt: 'Una roca ígnea se metamorfiza, luego se funde y finalmente el magma se solidifica. ¿Qué demuestra?', answer: 'El ciclo permite varias transformaciones sucesivas del mismo material', distractors: ['Una roca solo puede pertenecer a un tipo durante toda su historia', 'El metamorfismo impide la fusión posterior', 'La solidificación solo ocurre en rocas sedimentarias'], solution: 'El ciclo de las rocas conecta procesos y permite múltiples trayectorias.' },
    { level: 3, prompt: '¿Por qué la erosión no convierte por sí sola una roca en roca sedimentaria?', answer: 'Porque aún faltan deposición, compactación y cementación de los sedimentos', distractors: ['Porque la erosión produce siempre magma', 'Porque las rocas sedimentarias no contienen partículas', 'Porque la erosión solo ocurre bajo tierra'], solution: 'La erosión genera y transporta materiales, pero la litificación completa la formación de roca sedimentaria.' },
    { level: 3, prompt: 'Una roca se calienta mucho, cambia sus minerales, pero conserva estado sólido. ¿Qué frontera del ciclo no ha cruzado?', answer: 'La fusión hacia magma', distractors: ['La erosión hacia sedimento', 'La sedimentación en un río', 'La evaporación del agua'], solution: 'Mientras no se funda, sigue dentro de procesos metamórficos y no pasa a magma.' },
    { level: 3, prompt: 'Dos rocas ígneas se forman del mismo magma, una en profundidad y otra en superficie. ¿Qué diferencia puede esperarse?', answer: 'La de profundidad suele desarrollar cristales mayores por enfriarse más lentamente', distractors: ['La de superficie siempre contiene fósiles', 'La de profundidad no contiene minerales', 'Ambas deben tener exactamente la misma textura'], solution: 'La velocidad de enfriamiento influye en el tamaño de los cristales.' },
    { level: 4, prompt: 'Un sedimento se litifica, se metamorfiza y después se funde. ¿Qué tres estados o productos aparecen en orden?', answer: 'Roca sedimentaria → roca metamórfica → magma', distractors: ['Magma → sedimento → roca ígnea', 'Roca metamórfica → fósil → atmósfera', 'Roca ígnea → agua → sedimento'], solution: 'La litificación forma roca sedimentaria; el metamorfismo la transforma y la fusión produce magma.' },
    { level: 5, prompt: '¿Por qué el ciclo de las rocas se representa mejor como una red de rutas que como una rueda con un único camino?', answer: 'Porque un mismo tipo de roca puede seguir procesos distintos según las condiciones', distractors: ['Porque todos los procesos ocurren siempre a la vez', 'Porque ninguna roca puede volver a un estado anterior', 'Porque solo las rocas ígneas participan en el ciclo'], solution: 'Las condiciones geológicas determinan rutas diferentes entre meteorización, sedimentación, metamorfismo, fusión y solidificación.' },
  ],
  B02S04: [
    { level: 1, prompt: 'El agua de lluvia entra en grietas, se congela y ensancha la roca. ¿Qué proceso es?', answer: 'Meteorización física', distractors: ['Sedimentación', 'Metamorfismo', 'Cristalización de magma'], solution: 'La congelación y expansión del agua rompe roca sin cambiar su composición química.' },
    { level: 1, prompt: 'Un río transporta arena corriente abajo. ¿Qué proceso está ocurriendo?', answer: 'Transporte de sedimentos', distractors: ['Metamorfismo', 'Fusión', 'Cristalización profunda'], solution: 'La corriente mueve materiales previamente erosionados.' },
    { level: 1, prompt: 'La arena se acumula donde un río pierde velocidad. ¿Qué proceso domina?', answer: 'Sedimentación', distractors: ['Fusión', 'Metamorfismo', 'Meteorización química exclusivamente'], solution: 'Al disminuir la energía del agua, los materiales pueden depositarse.' },
    { level: 1, prompt: 'El oleaje arranca fragmentos de un acantilado. ¿Qué proceso destaca?', answer: 'Erosión marina', distractors: ['Sedimentación eólica', 'Metamorfismo regional', 'Solidificación magmática'], solution: 'El oleaje desgasta y retira materiales de la costa.' },
    { level: 1, prompt: 'El viento levanta y desplaza arena en una zona seca. ¿Qué agente geológico actúa?', answer: 'El viento', distractors: ['El magma', 'La presión metamórfica', 'La cementación'], solution: 'El viento puede erosionar, transportar y depositar partículas.' },
    { level: 2, prompt: 'Un meandro erosiona con más fuerza la orilla exterior y deposita sedimentos en la interior. ¿Qué explica la diferencia?', answer: 'La velocidad del agua cambia dentro de la curva', distractors: ['La gravedad desaparece en la orilla interior', 'El río deja de transportar sedimentos en las curvas', 'La roca exterior se convierte directamente en magma'], solution: 'La corriente suele ser más rápida en el exterior del meandro y más lenta en el interior.' },
    { level: 2, prompt: '¿Por qué una playa puede perder arena durante un temporal?', answer: 'El oleaje de alta energía puede erosionarla y transportar sedimento mar adentro o a lo largo de la costa', distractors: ['La arena se transforma químicamente en aire', 'Las olas solo depositan y no transportan', 'La marea convierte arena en roca metamórfica'], solution: 'Las condiciones energéticas controlan el balance entre erosión, transporte y deposición.' },
    { level: 2, prompt: 'Tras lluvias intensas, una ladera sin vegetación forma pequeños surcos. ¿Qué combinación de procesos es más probable?', answer: 'Escorrentía y erosión hídrica', distractors: ['Fusión y cristalización', 'Metamorfismo y sedimentación profunda', 'Evaporación y formación de magma'], solution: 'El agua que fluye por la superficie puede concentrarse y arrancar suelo formando surcos.' },
    { level: 2, prompt: 'Un abanico aluvial aparece al pie de una montaña. ¿Por qué se depositan allí muchos sedimentos?', answer: 'La corriente pierde velocidad al salir a una zona más llana', distractors: ['La gravedad aumenta bruscamente', 'Los sedimentos se funden al llegar al llano', 'El agua deja de pertenecer a la hidrosfera'], solution: 'Al disminuir la pendiente y la velocidad, la corriente pierde capacidad de transporte.' },
    { level: 2, prompt: 'En un desierto, granos de arena chocan contra una roca durante años. ¿Qué efecto pueden producir?', answer: 'Desgaste por abrasión eólica', distractors: ['Metamorfismo de alto grado', 'Cementación de magma', 'Formación de fósiles por presión'], solution: 'Partículas transportadas por el viento pueden pulir y desgastar superficies rocosas.' },
    { level: 3, prompt: 'Un río lleva más carga de sedimentos después de una fuerte deforestación de su cuenca. ¿Qué relación es más plausible?', answer: 'Menos vegetación deja suelo expuesto y aumenta la erosión', distractors: ['Los árboles producían directamente los sedimentos minerales', 'La deforestación detiene la escorrentía', 'La falta de raíces convierte el río en magma'], solution: 'La cubierta vegetal protege el suelo y sus raíces ayudan a estabilizarlo.' },
    { level: 3, prompt: 'Una carretera corta una ladera muy inclinada y después de lluvias aparecen grietas y desplazamientos. ¿Qué riesgo aumenta?', answer: 'Movimientos de ladera o deslizamientos', distractors: ['Erupciones volcánicas por el asfalto', 'Formación inmediata de glaciares', 'Desaparición de la erosión'], solution: 'Modificar la pendiente y saturar materiales con agua puede reducir la estabilidad de una ladera.' },
    { level: 3, prompt: 'Un delta crece donde un río entra en un mar tranquilo. ¿Qué balance domina?', answer: 'La deposición supera a la retirada de sedimentos', distractors: ['La fusión supera a la solidificación', 'El metamorfismo supera a la erosión', 'La evaporación convierte sedimentos en magma'], solution: 'Cuando el río pierde velocidad y los sedimentos no son retirados al mismo ritmo, se acumulan y construyen el delta.' },
    { level: 3, prompt: 'Una cueva caliza aumenta lentamente de tamaño por agua ligeramente ácida. ¿Qué proceso interviene?', answer: 'Meteorización química por disolución', distractors: ['Meteorización física por congelación exclusivamente', 'Metamorfismo por alta presión', 'Solidificación de lava'], solution: 'El agua con dióxido de carbono puede disolver carbonatos y ensanchar fracturas y cavidades.' },
    { level: 4, prompt: 'Dos cuencas reciben la misma tormenta; una está cubierta de vegetación y otra tiene suelo desnudo compactado. ¿Dónde es esperable mayor escorrentía superficial?', answer: 'En la cuenca con suelo desnudo y compactado', distractors: ['En la vegetada porque las raíces expulsan toda el agua', 'Exactamente igual en ambas sin importar el suelo', 'Solo puede haber escorrentía si existe nieve'], solution: 'La vegetación y un suelo permeable favorecen infiltración, mientras la compactación y falta de cubierta aumentan escorrentía.' },
    { level: 5, prompt: 'Para reducir riesgo de inundación aguas abajo, ¿qué medida trabaja con los procesos de la cuenca en vez de limitarse al cauce?', answer: 'Conservar zonas de infiltración y vegetación que retengan y ralenticen el agua', distractors: ['Impermeabilizar toda la cuenca', 'Eliminar llanuras de inundación mediante relleno sin estudiar efectos', 'Acelerar toda la escorrentía hacia el río'], solution: 'Retener agua, favorecer infiltración y reducir picos de escorrentía puede disminuir caudales máximos aguas abajo.' },
  ],
}

export function getGeologyCourseDepthSupplement(skillId: string): GeologyDepthCard[] {
  return SUPPLEMENT[skillId] ?? []
}

export function geologyCourseDepthSupplementSkillIds() {
  return Object.keys(SUPPLEMENT)
}
