import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta = { id: string; name: string; generator_key: string }
type Card = { level: number; prompt: string; answer: string; distractors: [string,string,string]; solution: string }

const BANK: Record<string, Card[]> = {
  G04S01: [
    { level:1, prompt:'¿Qué unidad cronológica equivale a cien años?', answer:'Un siglo', distractors:['Una década','Un milenio','Un bienio'], solution:'Un siglo reúne cien años.' },
    { level:1, prompt:'¿Cuál de estas fechas es más reciente?', answer:'250 d. C.', distractors:['900 a. C.','500 a. C.','50 a. C.'], solution:'Las fechas d. C. son posteriores a las fechas a. C. indicadas.' },
    { level:2, prompt:'¿A qué siglo pertenece el año 1492?', answer:'Siglo XV', distractors:['Siglo XIV','Siglo XVI','Siglo XIII'], solution:'Los años 1401-1500 pertenecen al siglo XV.' },
    { level:2, prompt:'¿Cuál es el orden correcto de más antiguo a más reciente?', answer:'2000 a. C. → 500 a. C. → 300 d. C.', distractors:['500 a. C. → 2000 a. C. → 300 d. C.','300 d. C. → 500 a. C. → 2000 a. C.','2000 a. C. → 300 d. C. → 500 a. C.'], solution:'En a. C., los números mayores son más antiguos; después llegan las fechas d. C.' },
    { level:3, prompt:'Un proceso empieza en 350 a. C. y termina en 50 a. C. ¿Cuánto dura aproximadamente?', answer:'300 años', distractors:['400 años','50 años','350 años'], solution:'Entre 350 a. C. y 50 a. C. transcurren unos 300 años.' },
    { level:3, prompt:'¿Qué ventaja tiene dividir la historia en periodos?', answer:'Ayuda a organizar cambios y continuidades en el tiempo', distractors:['Elimina la necesidad de usar fuentes','Hace que todos los periodos duren lo mismo','Permite saber el futuro'], solution:'La periodización es una herramienta para organizar e interpretar procesos históricos.' },
    { level:4, prompt:'Dos historiadores proponen fechas distintas para el final de una etapa. ¿Qué conclusión es razonable?', answer:'Las periodizaciones pueden variar según el criterio empleado', distractors:['Una de las dos fechas debe ser siempre falsa','Los periodos históricos son leyes naturales exactas','No se pueden usar fechas en historia'], solution:'Los periodos son convenciones analíticas y pueden cambiar según el fenómeno estudiado.' },
    { level:4, prompt:'¿Por qué es útil distinguir entre cambio rápido y proceso de larga duración?', answer:'Porque algunos hechos ocurren en poco tiempo y otros transforman sociedades durante siglos', distractors:['Porque todo cambio histórico dura exactamente un año','Porque los procesos largos no tienen causas','Porque los hechos breves no tienen consecuencias'], solution:'La escala temporal ayuda a comprender ritmos distintos de transformación histórica.' },
  ],
  G04S02: [
    { level:1, prompt:'¿Qué modo de vida caracteriza a muchos grupos paleolíticos?', answer:'Caza, pesca, recolección y movilidad', distractors:['Agricultura intensiva y ciudades','Industria mecanizada','Comercio ferroviario'], solution:'Las sociedades paleolíticas dependían de recursos silvestres y se desplazaban para obtenerlos.' },
    { level:1, prompt:'¿Qué herramienta encaja mejor con el Paleolítico?', answer:'Un bifaz de piedra tallada', distractors:['Un arado de hierro','Una imprenta','Una máquina de vapor'], solution:'La piedra tallada es característica de muchas tecnologías paleolíticas.' },
    { level:2, prompt:'¿Por qué el fuego supuso una ventaja importante?', answer:'Permitió cocinar, calentarse, iluminar y protegerse', distractors:['Sustituyó todas las herramientas','Creó la escritura automáticamente','Hizo innecesario buscar alimento'], solution:'El control del fuego mejoró alimentación, seguridad y vida cotidiana.' },
    { level:2, prompt:'¿Qué evidencia indicaría ocupación repetida de una cueva?', answer:'Hogares superpuestos, herramientas y restos de alimento', distractors:['Una carretera moderna cercana','Una señal de tráfico','Una fotografía reciente'], solution:'La acumulación de restos en distintos niveles puede mostrar usos sucesivos del lugar.' },
    { level:3, prompt:'En una zona escasean grandes animales pero abundan peces y plantas silvestres. ¿Qué cabría esperar?', answer:'Una dieta adaptada a los recursos locales', distractors:['La misma dieta exacta en todas las regiones','Abandono obligatorio de toda herramienta','Agricultura intensiva inmediata'], solution:'Los grupos cazadores-recolectores ajustaban su subsistencia al medio disponible.' },
    { level:3, prompt:'¿Qué explica mejor la movilidad estacional?', answer:'Seguir recursos que cambian según estaciones y territorios', distractors:['No conocer ningún refugio','Carecer siempre de organización social','Tener prohibido permanecer en un lugar'], solution:'La disponibilidad estacional de animales, agua y plantas influía en los desplazamientos.' },
    { level:4, prompt:'Un yacimiento contiene herramientas especializadas para cortar carne y trabajar pieles. ¿Qué puede inferirse con prudencia?', answer:'Existía una organización técnica de distintas tareas', distractors:['Con certeza había escritura','Con certeza era una ciudad','No utilizaban recursos animales'], solution:'La diversidad funcional de útiles puede reflejar actividades diferenciadas, sin demostrar por sí sola urbanismo o escritura.' },
    { level:4, prompt:'¿Por qué no debe describirse el Paleolítico como una etapa sin innovación?', answer:'Porque hubo cambios tecnológicos, sociales y simbólicos durante un periodo muy largo', distractors:['Porque ya existían motores','Porque todas las herramientas eran de metal','Porque no cambió nada durante milenios'], solution:'El Paleolítico incluye una larga evolución de técnicas, estrategias y expresiones culturales.' },
  ],
  G04S03: [
    { level:1, prompt:'¿Qué novedad económica define el Neolítico?', answer:'La producción de alimentos mediante agricultura y ganadería', distractors:['La navegación a vapor','La fabricación industrial','La desaparición de asentamientos'], solution:'Agricultura y ganadería transformaron la forma de obtener alimentos.' },
    { level:1, prompt:'¿Qué cambio favoreció el sedentarismo?', answer:'Cultivar campos y cuidar rebaños cerca del poblado', distractors:['Depender solo de caza migratoria','Eliminar el almacenamiento','Abandonar toda domesticación'], solution:'La producción de alimentos vinculó a las comunidades con territorios concretos.' },
    { level:2, prompt:'¿Qué utilidad tuvo almacenar cereal?', answer:'Reservar excedentes para consumo, intercambio o épocas difíciles', distractors:['Impedir toda especialización','Eliminar la necesidad de cosechar','Sustituir la cerámica'], solution:'El almacenamiento permitía gestionar producción sobrante a lo largo del tiempo.' },
    { level:2, prompt:'¿Qué consecuencia social puede relacionarse con los excedentes?', answer:'Mayor especialización de tareas', distractors:['Desaparición de artesanos','Fin de los intercambios','Nomadismo obligatorio'], solution:'Los excedentes permiten que algunas personas dediquen tiempo a actividades distintas de producir alimentos.' },
    { level:3, prompt:'Un poblado construye silos, cercados y viviendas duraderas. ¿Qué cambio refleja?', answer:'Mayor permanencia y planificación comunitaria', distractors:['Retorno a una vida exclusivamente nómada','Ausencia de agricultura','Uso industrial de electricidad'], solution:'Infraestructuras permanentes indican asentamiento estable y gestión colectiva.' },
    { level:3, prompt:'¿Por qué la domesticación no fue solo “capturar animales”?', answer:'Implicó seleccionar y reproducir especies durante generaciones', distractors:['Consistió únicamente en cazarlos','Eliminó toda selección humana','No modificó relación alguna con los animales'], solution:'La domesticación es un proceso prolongado de control reproductivo y selección.' },
    { level:4, prompt:'¿Qué efecto pudo tener una cosecha abundante varios años seguidos?', answer:'Aumentar reservas, población e intercambios, aunque también desigualdades', distractors:['Eliminar cualquier riesgo para siempre','Hacer innecesaria toda organización','Impedir el crecimiento de poblados'], solution:'Los excedentes pueden sostener crecimiento y especialización, pero también diferencias de acceso a recursos.' },
    { level:4, prompt:'¿Por qué la “revolución neolítica” no ocurrió igual ni al mismo tiempo en todas partes?', answer:'Porque distintos territorios adoptaron agricultura y ganadería a ritmos y formas diferentes', distractors:['Porque solo existió en una única aldea','Porque todas las regiones cambiaron el mismo año','Porque no hubo sociedades cazadoras-recolectoras después'], solution:'La transición fue diversa y escalonada según ambientes, especies y contactos culturales.' },
  ],
  G04S04: [
    { level:1, prompt:'Una punta de flecha hallada en excavación es un ejemplo de…', answer:'Fuente material', distractors:['Fuente oral actual','Fuente estadística moderna','Predicción'], solution:'Los objetos fabricados y usados por personas son fuentes materiales.' },
    { level:1, prompt:'¿Qué disciplina estudia restos materiales de sociedades antiguas?', answer:'Arqueología', distractors:['Meteorología','Astronomía','Demografía actual'], solution:'La arqueología analiza objetos, estructuras y contextos del pasado.' },
    { level:2, prompt:'¿Por qué importa el contexto de un hallazgo?', answer:'Relaciona el objeto con capa, lugar y otros restos', distractors:['Porque garantiza conocer a su propietario','Porque sustituye cualquier análisis','Porque hace innecesaria la datación'], solution:'El contexto permite interpretar mejor cronología y función.' },
    { level:2, prompt:'¿Qué puede aportar el análisis de polen antiguo?', answer:'Información sobre vegetación y ambiente del pasado', distractors:['El nombre exacto de cada habitante','Una ley escrita inexistente','La fecha de mañana'], solution:'El polen conservado ayuda a reconstruir paisajes y condiciones ambientales.' },
    { level:3, prompt:'Dos objetos similares aparecen en capas separadas por muchos sedimentos. ¿Qué debe evitarse?', answer:'Suponer sin más que son exactamente contemporáneos', distractors:['Registrar la profundidad','Comparar materiales','Analizar el contexto'], solution:'La estratigrafía puede indicar diferencias cronológicas aunque los objetos se parezcan.' },
    { level:3, prompt:'¿Qué combinación ofrece una interpretación más sólida de un enterramiento?', answer:'Restos humanos, ajuar, posición y contexto de la tumba', distractors:['Solo el objeto más llamativo','Una leyenda sin relación con el lugar','Una fotografía moderna del paisaje'], solution:'Cruzar varias evidencias reduce interpretaciones arbitrarias.' },
    { level:4, prompt:'¿Por qué una reconstrucción arqueológica puede cambiar con nuevos hallazgos?', answer:'Porque las explicaciones históricas se revisan cuando aparece nueva evidencia', distractors:['Porque toda evidencia es inútil','Porque nunca se documentan excavaciones','Porque las fechas cambian físicamente'], solution:'La investigación histórica es revisable y depende del conjunto de pruebas disponibles.' },
    { level:4, prompt:'Un objeto aparece fuera de su capa original por una excavación antigua mal registrada. ¿Qué problema genera?', answer:'Se pierde parte de la información necesaria para interpretarlo', distractors:['El objeto deja de existir','Se conoce mejor su fecha automáticamente','Ya no hace falta compararlo con nada'], solution:'Sin contexto estratigráfico disminuye la capacidad de relacionarlo con otros restos y fecharlo.' },
  ],
  G05S01: [
    { level:1, prompt:'¿Dónde se desarrollaron importantes ciudades mesopotámicas?', answer:'Entre los ríos Tigris y Éufrates', distractors:['En el valle del Rin','En los Andes','En la península escandinava'], solution:'Mesopotamia significa “tierra entre ríos” y se asocia al Tigris y Éufrates.' },
    { level:1, prompt:'¿Qué sistema de escritura se asocia a Mesopotamia?', answer:'Cuneiforme', distractors:['Jeroglífica egipcia exclusivamente','Alfabeto latino medieval','Código Morse'], solution:'La escritura cuneiforme se marcaba sobre tablillas, a menudo de arcilla.' },
    { level:2, prompt:'¿Por qué los canales eran importantes en Mesopotamia?', answer:'Permitían distribuir agua y reducir la irregularidad de las crecidas', distractors:['Eliminaban toda necesidad de agricultura','Servían únicamente como murallas','Impedían el transporte de agua'], solution:'El regadío sostenía cultivos en un ambiente donde el agua debía gestionarse.' },
    { level:2, prompt:'¿Qué caracteriza a una ciudad-Estado?', answer:'Una ciudad con territorio, autoridades e instituciones propias', distractors:['Una aldea sin organización','Una provincia industrial moderna','Un continente entero'], solution:'Ciudades como Ur o Uruk actuaban como unidades políticas independientes.' },
    { level:3, prompt:'¿Qué relación existe entre excedentes agrícolas y crecimiento urbano?', answer:'Los excedentes podían sostener artesanos, administradores y comerciantes', distractors:['Los excedentes impedían la especialización','Las ciudades no dependían de alimentos','La agricultura hacía imposible el comercio'], solution:'Una producción superior al consumo inmediato permite mantener población no agrícola.' },
    { level:3, prompt:'¿Por qué registrar tributos en tablillas era útil para el poder?', answer:'Facilitaba controlar entregas, deudas y recursos', distractors:['Hacía innecesaria toda administración','Eliminaba el intercambio','Impedía contar productos'], solution:'La escritura aumentó la capacidad de gestión de instituciones y templos.' },
    { level:4, prompt:'Una ciudad controla un canal del que dependen varias aldeas. ¿Qué consecuencia política es plausible?', answer:'El control del agua puede reforzar autoridad y negociación sobre el territorio', distractors:['El agua deja de tener valor económico','Las aldeas se vuelven independientes del río','Toda autoridad desaparece'], solution:'Gestionar infraestructuras esenciales puede concentrar poder y obligaciones.' },
    { level:4, prompt:'¿Por qué no puede explicarse Mesopotamia solo por la fertilidad del suelo?', answer:'Porque también importaron organización, tecnología hidráulica, comercio y conflictos', distractors:['Porque el suelo nunca influyó','Porque no existían ríos','Porque todas las ciudades surgieron sin agricultura'], solution:'El medio ofrecía oportunidades y riesgos que las sociedades gestionaron mediante instituciones y tecnología.' },
  ],
  G05S02: [
    { level:1, prompt:'¿Qué río estructuró gran parte de la vida del antiguo Egipto?', answer:'El Nilo', distractors:['El Tíber','El Danubio','El Támesis'], solution:'El valle y delta del Nilo concentraron agricultura y población.' },
    { level:1, prompt:'¿Quién ocupaba la cúspide del poder político egipcio?', answer:'El faraón', distractors:['El cónsul romano','El estratega ateniense','El dux medieval'], solution:'El faraón concentraba autoridad política y una fuerte dimensión religiosa.' },
    { level:2, prompt:'¿Por qué eran valiosos los limos de las crecidas?', answer:'Renovaban la fertilidad de los campos', distractors:['Convertían el valle en desierto','Destruían siempre las cosechas','Impedían cualquier cultivo'], solution:'Los sedimentos aportados por el río favorecían la agricultura.' },
    { level:2, prompt:'¿Qué función tenían muchos escribas?', answer:'Registrar impuestos, cosechas, obras y asuntos administrativos', distractors:['Dirigir únicamente ejércitos','Construir todas las pirámides personalmente','Sustituir a campesinos en el campo'], solution:'La administración estatal requería personas capaces de leer, escribir y calcular.' },
    { level:3, prompt:'¿Qué revela una tumba con ajuar abundante?', answer:'Puede indicar diferencias de estatus y creencias funerarias', distractors:['Que toda la población tenía la misma riqueza','Que no existían creencias religiosas','Que el enterrado era necesariamente faraón'], solution:'El ajuar informa sobre prácticas y desigualdades, pero no permite afirmaciones absolutas sin más datos.' },
    { level:3, prompt:'¿Por qué la previsión del ciclo del Nilo era importante?', answer:'Ayudaba a organizar cultivos, impuestos y trabajos hidráulicos', distractors:['Permitía evitar toda sequía para siempre','Eliminaba la necesidad de medir tierras','Hacía inútil la administración'], solution:'La agricultura dependía del calendario agrícola y del comportamiento del río.' },
    { level:4, prompt:'Si una crecida era excepcionalmente baja, ¿qué problema podía aparecer?', answer:'Menor producción agrícola y presión sobre reservas e impuestos', distractors:['Aumento automático de cosechas','Desaparición de toda autoridad','Más suelo fértil sin límite'], solution:'Menos agua y limo podían reducir cosechas y tensionar la economía.' },
    { level:4, prompt:'¿Por qué las pirámides también informan sobre organización social?', answer:'Su construcción exigió movilizar recursos, especialistas y trabajo coordinado', distractors:['Porque fueron hechas por una sola persona','Porque no necesitaron planificación','Porque no estaban vinculadas al poder'], solution:'Las obras monumentales reflejan capacidad de organización y concentración de recursos.' },
  ],
  G05S03: [
    { level:1, prompt:'¿Qué ventaja ofrece una ley escrita frente a una norma solo oral?', answer:'Puede conservarse y consultarse de forma más estable', distractors:['Evita automáticamente todo conflicto','Hace innecesarios jueces y autoridades','Impide que existan cambios legales'], solution:'La escritura permite fijar y difundir normas con mayor permanencia.' },
    { level:1, prompt:'¿Para qué servían muchos registros administrativos antiguos?', answer:'Controlar impuestos, bienes, trabajadores y entregas', distractors:['Registrar únicamente leyendas','Eliminar el comercio','Sustituir los cultivos'], solution:'La administración compleja necesita información organizada sobre recursos y obligaciones.' },
    { level:2, prompt:'¿Qué relación hay entre excedentes y administración?', answer:'Cuantos más recursos se concentran, más necesario es registrarlos y redistribuirlos', distractors:['Los excedentes eliminan toda gestión','La administración solo existe sin agricultura','Los registros impiden almacenar'], solution:'La gestión de almacenes, tributos y pagos impulsa sistemas administrativos.' },
    { level:2, prompt:'¿Por qué la escritura pudo reforzar el poder estatal?', answer:'Permitió transmitir órdenes y conservar información a mayor escala', distractors:['Hizo desaparecer las instituciones','Impidió organizar territorios','Sustituyó por completo al ejército'], solution:'Los textos ayudan a coordinar personas, recursos y decisiones en territorios amplios.' },
    { level:3, prompt:'Un documento registra raciones entregadas a trabajadores. ¿Qué tipo de información aporta?', answer:'Información económica y administrativa', distractors:['Solo información religiosa','Una predicción climática','Una fuente sin valor histórico'], solution:'Las listas de raciones muestran organización del trabajo y distribución de recursos.' },
    { level:3, prompt:'¿Qué riesgo tiene interpretar un código legal como descripción exacta de la vida cotidiana?', answer:'Las leyes muestran normas deseadas, no necesariamente todo lo que ocurría', distractors:['Las leyes nunca sirven como fuente','Toda ley describe cada caso real','Los textos legales no pertenecen a la historia'], solution:'Debe distinguirse entre norma, práctica y aplicación real.' },
    { level:4, prompt:'¿Por qué los archivos son una herramienta de poder?', answer:'Quien controla registros puede gestionar deudas, propiedad, tributos y decisiones', distractors:['Porque los archivos eliminan toda desigualdad','Porque no contienen información económica','Porque impiden conservar memoria'], solution:'La información administrativa puede ser clave para controlar recursos y derechos.' },
    { level:4, prompt:'¿Qué muestra la aparición de escribas especializados?', answer:'Una sociedad con división del trabajo y necesidades administrativas complejas', distractors:['Ausencia de instituciones','Economía exclusivamente cazadora','Desaparición de ciudades'], solution:'La escritura profesional requiere aprendizaje y responde a tareas específicas de gestión.' },
  ],
  G05S04: [
    { level:1, prompt:'¿Qué rasgo compartieron Mesopotamia y Egipto?', answer:'Agricultura vinculada a grandes ríos', distractors:['Democracia ateniense','Uso de ferrocarriles','Industria mecanizada'], solution:'Ambas civilizaciones dependieron de sistemas fluviales para agricultura y asentamientos.' },
    { level:1, prompt:'¿Qué diferencia básica existía entre Mesopotamia y Egipto en su organización política?', answer:'Mesopotamia tuvo varias ciudades-Estado y reinos; Egipto tendió a una mayor unidad territorial', distractors:['Egipto no tuvo autoridades','Mesopotamia fue siempre un único imperio estable','Ambas carecieron de administración'], solution:'La trayectoria política fue distinta: fragmentación frecuente en Mesopotamia y mayor centralización egipcia.' },
    { level:2, prompt:'¿Qué comparación sobre escritura es correcta?', answer:'Mesopotamia usó cuneiforme y Egipto desarrolló sistemas jeroglíficos', distractors:['Ambas usaron exclusivamente alfabeto latino','Ninguna civilización escribió','Egipto usó solo cuneiforme'], solution:'Cada región desarrolló tradiciones gráficas propias.' },
    { level:2, prompt:'¿Qué elemento común muestra la importancia de la religión?', answer:'Templos, sacerdotes y monumentos vinculados al poder', distractors:['Ausencia de rituales','Separación total entre poder y religión','Prohibición de construcciones religiosas'], solution:'Las instituciones religiosas tuvieron peso económico, social y político en ambas áreas.' },
    { level:3, prompt:'¿Por qué los ríos no tuvieron exactamente el mismo efecto en ambas civilizaciones?', answer:'Sus ritmos de crecida y condiciones geográficas eran diferentes', distractors:['Porque uno de los territorios no tenía agricultura','Porque el agua no influye en sociedades','Porque ambos ríos se comportaban igual'], solution:'El Nilo era más predecible que Tigris y Éufrates, condicionando formas distintas de gestión.' },
    { level:3, prompt:'¿Qué comparación es más prudente sobre el poder?', answer:'Ambas tuvieron élites e instituciones, pero con estructuras y cambios históricos distintos', distractors:['Sus sistemas políticos fueron idénticos durante milenios','Ninguna tuvo diferencias sociales','Toda ciudad mesopotámica obedeció siempre al faraón'], solution:'Comparar exige reconocer semejanzas sin borrar diferencias temporales y regionales.' },
    { level:4, prompt:'Si dos sociedades tienen agricultura de regadío, ¿basta eso para afirmar que serán políticamente iguales?', answer:'No, porque instituciones, conflictos, comercio y cultura también influyen', distractors:['Sí, el medio determina por completo la política','Sí, todos los ríos producen el mismo Estado','No, porque el agua nunca importa'], solution:'El entorno condiciona posibilidades, pero no determina por sí solo una forma política única.' },
    { level:4, prompt:'¿Qué aporta comparar civilizaciones antiguas?', answer:'Permite distinguir patrones comunes y respuestas diferentes a problemas similares', distractors:['Demuestra que todas evolucionan igual','Evita estudiar cada caso concreto','Sustituye el análisis de fuentes'], solution:'La comparación ayuda a formular explicaciones sin asumir que todas las sociedades siguen el mismo camino.' },
  ],
  G06S01: [
    { level:1, prompt:'¿Qué era una polis griega?', answer:'Una comunidad política organizada alrededor de una ciudad y su territorio', distractors:['Una provincia romana','Un reino medieval','Una fábrica'], solution:'La polis era una unidad política con instituciones y ciudadanía propias.' },
    { level:1, prompt:'¿Dónde se desarrolló la democracia directa más conocida de la Grecia clásica?', answer:'Atenas', distractors:['Esparta exclusivamente','Roma imperial','Egipto faraónico'], solution:'Atenas desarrolló instituciones de participación directa de ciudadanos varones libres.' },
    { level:2, prompt:'¿Qué limitación tenía la ciudadanía ateniense?', answer:'Excluía a mujeres, esclavos y muchos extranjeros residentes', distractors:['Incluía a toda la población sin excepción','Solo podían participar niños','No existían ciudadanos'], solution:'La democracia ateniense participativa era amplia para sus ciudadanos, pero la ciudadanía era restringida.' },
    { level:2, prompt:'¿Qué institución permitía debatir y votar decisiones a ciudadanos atenienses?', answer:'La asamblea', distractors:['El Senado romano imperial','El faraonato','El monasterio'], solution:'La ekklesía reunía ciudadanos para deliberar y decidir sobre asuntos públicos.' },
    { level:3, prompt:'¿Por qué Atenas y Esparta no deben tratarse como el mismo modelo de polis?', answer:'Tenían instituciones, prioridades sociales y sistemas políticos diferentes', distractors:['Porque una de ellas no era griega','Porque compartían exactamente todas sus leyes','Porque ninguna tenía ejército'], solution:'Las polis podían compartir cultura griega y, a la vez, organizarse de forma distinta.' },
    { level:3, prompt:'¿Qué ventaja y qué riesgo tiene decidir por votación en una asamblea?', answer:'Amplía participación, pero las decisiones pueden depender de persuasión, mayorías y contexto', distractors:['Garantiza siempre la mejor decisión','Elimina cualquier conflicto','Impide debatir'], solution:'La participación no elimina desacuerdos ni asegura resultados perfectos.' },
    { level:4, prompt:'¿Por qué la democracia ateniense no equivale a una democracia representativa actual?', answer:'Porque muchos ciudadanos decidían directamente y la ciudadanía era mucho más limitada', distractors:['Porque Atenas tenía partidos modernos idénticos','Porque usaba sufragio universal','Porque no existían leyes'], solution:'Las instituciones y la definición de ciudadanía eran diferentes a las democracias modernas.' },
    { level:4, prompt:'¿Qué muestra el ostracismo sobre la política ateniense?', answer:'Que existían mecanismos para limitar poder considerado peligroso, aunque podían usarse políticamente', distractors:['Que no había conflictos políticos','Que todos los habitantes eran ciudadanos','Que la asamblea no tomaba decisiones'], solution:'El ostracismo buscaba prevenir concentraciones de poder pero formaba parte de luchas políticas reales.' },
  ],
  G06S02: [
    { level:1, prompt:'¿Qué disciplina desarrollaron pensadores griegos mediante debate racional sobre naturaleza y sociedad?', answer:'La filosofía', distractors:['La imprenta','La fotografía','La ingeniería informática'], solution:'La filosofía griega dejó una importante tradición de argumentación racional.' },
    { level:1, prompt:'¿Qué forma artística se desarrolló especialmente en festivales griegos?', answer:'El teatro', distractors:['El cine','La ópera barroca','La televisión'], solution:'Tragedia y comedia tuvieron un papel importante en la cultura cívica griega.' },
    { level:2, prompt:'¿Qué rasgo aparece en muchos templos griegos clásicos?', answer:'Órdenes arquitectónicos con columnas y proporciones', distractors:['Rascacielos de acero','Arcos góticos medievales exclusivamente','Hormigón pretensado moderno'], solution:'Los órdenes dórico, jónico y corintio influyeron en arquitectura posterior.' },
    { level:2, prompt:'¿Qué relación tuvo la mitología con la cultura griega?', answer:'Explicaba relatos sobre dioses, héroes y valores compartidos', distractors:['Era un código informático','Sustituía toda observación de la naturaleza','No aparecía en arte ni literatura'], solution:'Los mitos formaban parte de religión, literatura y representación cultural.' },
    { level:3, prompt:'¿Por qué los Juegos Olímpicos antiguos tenían significado más allá del deporte?', answer:'Se vinculaban a festivales religiosos y a una identidad cultural compartida', distractors:['Eran competiciones industriales','No tenían relación con religión','Participaban Estados modernos'], solution:'Los juegos combinaban competición, culto y contactos entre comunidades griegas.' },
    { level:3, prompt:'¿Qué legado griego aparece en muchas lenguas científicas actuales?', answer:'Numerosos términos y raíces de origen griego', distractors:['Únicamente palabras de origen vikingo','Ausencia total de vocabulario heredado','Solo números romanos'], solution:'El griego dejó una huella profunda en terminología científica, médica y filosófica.' },
    { level:4, prompt:'¿Por qué hablar de “legado griego” no significa copiar Grecia sin cambios?', answer:'Porque ideas y formas fueron reinterpretadas por sociedades posteriores', distractors:['Porque nada griego influyó después','Porque toda Europa fue una polis','Porque los textos antiguos nunca se conservaron'], solution:'La transmisión cultural implica selección, traducción y adaptación.' },
    { level:4, prompt:'¿Qué diferencia hay entre mito e investigación racional en la Grecia antigua?', answer:'Podían coexistir; algunos pensadores buscaron explicaciones basadas en causas naturales y argumentos', distractors:['El pensamiento racional eliminó toda religión de inmediato','Los mitos eran experimentos científicos','Nunca hubo debate sobre la naturaleza'], solution:'La aparición de explicaciones racionales no borró automáticamente las creencias tradicionales.' },
  ],
  G06S03: [
    { level:1, prompt:'¿Qué etapa romana fue anterior al Imperio?', answer:'La República', distractors:['El Imperio bizantino','La Edad Media','El Renacimiento'], solution:'Tras la monarquía tradicional, Roma vivió una larga etapa republicana antes del Principado.' },
    { level:1, prompt:'¿Qué institución tuvo gran importancia política durante la República romana?', answer:'El Senado', distractors:['La asamblea ateniense como única autoridad','El faraón','El parlamento industrial moderno'], solution:'El Senado fue una institución central de la política republicana romana.' },
    { level:2, prompt:'¿Qué eran los cónsules en la República?', answer:'Magistrados superiores elegidos por periodos limitados', distractors:['Emperadores hereditarios','Sacerdotes egipcios','Esclavos públicos'], solution:'Dos cónsules compartían autoridad ejecutiva y su mandato era temporal.' },
    { level:2, prompt:'¿Qué cambió con Augusto?', answer:'Se consolidó un poder personal superior bajo formas republicanas', distractors:['Desapareció Roma','Comenzó la democracia ateniense','Se abolió el ejército'], solution:'Augusto inauguró el Principado concentrando poder sin eliminar de golpe todas las instituciones republicanas.' },
    { level:3, prompt:'¿Por qué la expansión territorial tensionó la República?', answer:'Aumentó riqueza, desigualdades, ejércitos personales y conflictos políticos', distractors:['Hizo innecesario gobernar provincias','Eliminó toda competencia entre élites','Redujo el ejército a cero'], solution:'La conquista transformó economía y política y contribuyó a crisis internas.' },
    { level:3, prompt:'¿Qué diferencia básica existe entre República e Imperio?', answer:'En el Imperio el poder se concentró más claramente en el emperador', distractors:['En la República no existían leyes','En el Imperio no hubo Senado','Roma dejó de tener provincias'], solution:'Las instituciones continuaron en parte, pero el equilibrio de poder cambió profundamente.' },
    { level:4, prompt:'¿Por qué no es exacto decir que la República terminó en un solo día?', answer:'Porque la concentración de poder fue un proceso de guerras civiles y cambios institucionales', distractors:['Porque nunca terminó','Porque Roma no tuvo conflictos','Porque todos los cambios fueron simultáneos'], solution:'La transición política fue gradual y conflictiva, aunque se usen fechas convencionales.' },
    { level:4, prompt:'¿Qué problema plantea gobernar un imperio muy extenso?', answer:'Necesita administración, comunicaciones, ejército y recursos para territorios diversos', distractors:['La distancia deja de importar','No hacen falta impuestos','Todas las provincias tienen idénticas necesidades'], solution:'La escala territorial aumenta costes y complejidad de coordinación.' },
  ],
  G06S04: [
    { level:1, prompt:'¿Qué lengua difundió Roma por gran parte de Occidente?', answer:'El latín', distractors:['El japonés','El náhuatl','El sánscrito'], solution:'El latín se extendió y dio origen a las lenguas romances.' },
    { level:1, prompt:'¿Qué obra pública romana facilitaba transportar agua?', answer:'El acueducto', distractors:['La pirámide','El zigurat','El dolmen'], solution:'Los acueductos conducían agua hacia ciudades y otras instalaciones.' },
    { level:2, prompt:'¿Qué significa romanización?', answer:'Adopción e intercambio de rasgos romanos en territorios incorporados al Imperio', distractors:['Desaparición instantánea de toda cultura local','Construcción exclusiva de murallas','Conversión de cada provincia en Roma ciudad'], solution:'La romanización fue desigual e implicó lengua, derecho, ciudades, costumbres e instituciones.' },
    { level:2, prompt:'¿Por qué las calzadas fueron importantes?', answer:'Facilitaron movimiento de tropas, comercio, administración y viajeros', distractors:['Impidieron la comunicación','Solo servían para ceremonias','Eliminaban la navegación'], solution:'La red viaria conectaba territorios y favorecía control e intercambio.' },
    { level:3, prompt:'Una ciudad provincial adopta foro, termas y derecho romano, pero mantiene cultos locales. ¿Qué muestra?', answer:'La romanización podía combinar adopción y continuidad local', distractors:['Toda cultura local desaparecía automáticamente','No existía influencia romana','La ciudad dejó de pertenecer al Imperio'], solution:'Los procesos culturales suelen mezclar cambios, adaptaciones y permanencias.' },
    { level:3, prompt:'¿Qué legado jurídico romano sigue siendo relevante?', answer:'Conceptos e instituciones del derecho que influyeron en sistemas posteriores', distractors:['La abolición de todas las leyes escritas','Un único código idéntico en todos los países actuales','La desaparición de contratos'], solution:'El derecho romano influyó profundamente en tradiciones jurídicas europeas y posteriores.' },
    { level:4, prompt:'¿Por qué las ciudades eran clave para la romanización?', answer:'Concentraban administración, mercados, infraestructuras y vida pública', distractors:['Porque las zonas rurales no existían','Porque toda la población vivía en Roma','Porque las ciudades impedían intercambios'], solution:'Las ciudades actuaban como nodos de poder, cultura y circulación económica.' },
    { level:4, prompt:'¿Por qué el legado romano es distinto según las regiones?', answer:'Porque la intensidad de conquista, urbanización y mezcla cultural no fue igual en todo el Imperio', distractors:['Porque Roma nunca tuvo provincias','Porque todas las regiones fueron idénticas','Porque no hubo contactos culturales'], solution:'La influencia romana dependió de la historia local y del grado de integración de cada territorio.' },
  ],
}

const FRAMES = [
  (prompt:string) => prompt,
  (prompt:string) => `Interpreta históricamente: ${prompt}`,
  (prompt:string) => `Aplica tus conocimientos de Historia: ${prompt}`,
  (prompt:string) => `Reto de razonamiento histórico: ${prompt}`,
] as const

function rotate<T>(items:T[], shift:number) {
  const offset = ((shift % items.length) + items.length) % items.length
  return items.slice(offset).concat(items.slice(0, offset))
}

export function generateHistoryLongTermVariant(skill: SkillMeta, difficulty: number, seed: number): GeneratedQuestion | null {
  const cards = BANK[skill.id]
  if (!cards?.length) return null
  const eligible = cards.filter((card) => Math.abs(card.level - difficulty) <= 1)
  const pool = eligible.length ? eligible : cards
  const normalized = seed >>> 0
  const card = pool[normalized % pool.length]
  const frame = FRAMES[Math.floor(normalized / pool.length) % FRAMES.length]
  const options = rotate([card.answer, ...card.distractors], normalized + difficulty)
  return {
    skillId: skill.id,
    label: skill.name,
    difficulty,
    seed,
    prompt: frame(card.prompt),
    options,
    answerIndex: options.indexOf(card.answer),
    solution: card.solution,
    tags: [skill.generator_key, 'history', 'history_course_depth'],
  }
}

export function historyLongTermVariantCount(skillId: string) {
  return (BANK[skillId]?.length ?? 0) * FRAMES.length
}

export function historyLongTermVariantSkillIds() {
  return Object.keys(BANK)
}
