import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta={id:string;name:string;generator_key:string}
type Card={prompt:string;answer:string;distractors:[string,string,string];why:string}
const c=(prompt:string,answer:string,distractors:[string,string,string],why:string):Card=>({prompt,answer,distractors,why})

const BANK:Record<string,Card[]>={
G04S01:[
c('¿Qué fecha es anterior?','1200 a. C.',['800 a. C.','200 a. C.','50 d. C.'],'En las fechas a. C., cuanto mayor es el número, más antigua es la fecha.'),
c('¿Qué ocurrió primero?','El año 500 a. C.',['El año 200 a. C.','El año 100 d. C.','El año 500 d. C.'],'500 a. C. está más alejado del presente que 200 a. C. y que las fechas d. C.'),
c('El siglo V a. C. comprende aproximadamente…','Los años 500-401 a. C.',['Los años 400-301 a. C.','Los años 1-100 d. C.','Los años 500-401 d. C.'],'Los siglos a. C. se cuentan hacia atrás: el V a. C. va de 500 a 401 a. C.'),
c('¿A qué siglo pertenece el año 44 a. C.?','Al siglo I a. C.',['Al siglo II a. C.','Al siglo IV a. C.','Al siglo I d. C.'],'Los años 100 a 1 a. C. forman el siglo I a. C.'),
c('Ordena mentalmente 3000 a. C., 1200 a. C., 500 a. C. y 100 d. C. ¿Cuál es la más antigua?','3000 a. C.',['1200 a. C.','500 a. C.','100 d. C.'],'En a. C., los números mayores corresponden a momentos más antiguos.'),
c('Una década equivale a…','10 años',['100 años','1000 años','5 años'],'La década es una unidad cronológica de diez años.'),
c('Un milenio equivale a…','1000 años',['100 años','10 años','500 años'],'Un milenio reúne mil años.'),
c('¿Qué instrumento ayuda mejor a representar acontecimientos en orden temporal?','Una línea del tiempo',['Una escala cartográfica','Un climograma','Una pirámide de población'],'La línea del tiempo sitúa hechos y periodos según su cronología.')],
G04S02:[
c('La economía paleolítica se basaba principalmente en…','Caza, pesca y recolección',['Agricultura intensiva','Industria mecanizada','Comercio transoceánico'],'Las comunidades paleolíticas obtenían alimentos mediante caza, pesca y recolección.'),
c('¿Por qué muchos grupos paleolíticos eran nómadas?','Se desplazaban buscando alimentos y recursos',['Poseían ferrocarriles','Cultivaban siempre la misma parcela','Vivían solo en ciudades'],'Dependían de recursos silvestres que variaban según lugar y estación.'),
c('¿Qué material se asocia especialmente a muchas herramientas paleolíticas?','Piedra tallada',['Acero industrial','Plástico','Hormigón armado'],'La talla de piedra permitió fabricar útiles como bifaces y raspadores.'),
c('¿Qué actividad artística aparece en el Paleolítico superior?','Pinturas rupestres',['Fotografía','Imprenta','Cine'],'Las pinturas y grabados rupestres son manifestaciones artísticas prehistóricas.'),
c('El dominio del fuego ayudó a los grupos paleolíticos a…','Calentarse, cocinar y protegerse',['Inventar la escritura','Construir autopistas','Crear monedas'],'El fuego aportó calor, protección y permitió cocinar alimentos.'),
c('¿Qué describe mejor un campamento paleolítico?','Un asentamiento generalmente temporal',['Una capital imperial permanente','Una fábrica moderna','Una polis griega'],'La movilidad de los cazadores-recolectores favorecía asentamientos temporales.'),
c('¿Qué evidencia permite conocer la dieta paleolítica?','Restos de huesos, semillas y hogares',['Un periódico actual','Una ley romana','Un mapa meteorológico'],'Los restos arqueológicos permiten reconstruir alimentos y prácticas de subsistencia.'),
c('¿Qué afirmación encaja con una sociedad cazadora-recolectora?','Obtiene recursos directamente del medio',['Produce alimentos mediante agricultura estable','Usa maquinaria de vapor','Depende de supermercados'],'Caza y recolección son formas de economía depredadora, no productora.')],
G04S03:[
c('¿Qué cambio caracteriza la revolución neolítica?','Agricultura y sedentarización',['Invención del motor','Abandono de poblados','Desaparición de herramientas'],'La producción de alimentos favoreció comunidades sedentarias.'),
c('La domesticación consiste en…','Criar y seleccionar especies para aprovecharlas',['Extinguir todas las especies silvestres','Construir templos','Inventar la moneda'],'Las sociedades neolíticas controlaron reproducción y uso de plantas y animales.'),
c('¿Por qué aparecieron poblados más permanentes en el Neolítico?','Los cultivos exigían cuidar tierras y cosechas',['La caza obligaba siempre a viajar','Existían automóviles','Se prohibió vivir al aire libre'],'La agricultura vinculó a las comunidades con campos y reservas.'),
c('¿Qué consecuencia favoreció el excedente agrícola?','Intercambios y especialización de tareas',['Desaparición del comercio','Nomadismo obligatorio','Fin de toda artesanía'],'Producir más de lo necesario permitió intercambiar y dedicar tiempo a otros oficios.'),
c('¿Qué técnica se relaciona especialmente con el Neolítico?','Piedra pulida',['Motor de combustión','Imprenta','Acero inoxidable'],'Junto a otras innovaciones, se generalizaron útiles de piedra pulida.'),
c('La cerámica fue útil sobre todo para…','Almacenar y cocinar alimentos',['Navegar por océanos','Escribir libros impresos','Fabricar motores'],'Los recipientes cerámicos facilitaron conservación, transporte y cocción.'),
c('¿Qué relación existe entre agricultura y crecimiento demográfico neolítico?','Una alimentación más estable pudo sostener más población',['La agricultura eliminó los alimentos','No existe relación posible','La población desapareció'],'Una producción alimentaria más previsible favoreció poblaciones mayores.'),
c('¿Qué diferencia básica separa Paleolítico y Neolítico?','Del aprovechamiento de recursos se pasa a producir alimentos',['Del hierro se pasa al plástico','De ciudades a cuevas exclusivamente','De escritura a ausencia de lenguaje'],'Agricultura y ganadería transformaron la base económica neolítica.')],
G04S04:[
c('Una herramienta de piedra hallada en una excavación es…','Una fuente arqueológica material',['Una fuente oral contemporánea','Una ley moderna','Una fotografía medieval'],'Los objetos materiales son evidencias arqueológicas del pasado.'),
c('¿Qué puede indicar un hogar con cenizas y huesos?','Actividades de alimentación y uso del fuego',['La existencia de internet','Una elección política','El clima de mañana'],'El contexto arqueológico permite interpretar actividades humanas pasadas.'),
c('¿Por qué es importante registrar la capa donde aparece un objeto?','Porque su contexto ayuda a datarlo e interpretarlo',['Porque cambia su color','Porque elimina la necesidad de analizarlo','Porque demuestra quién lo fabricó con certeza'],'La estratigrafía relaciona los restos con capas y otros hallazgos.'),
c('¿Qué estudia principalmente la arqueología?','Restos materiales y sus contextos',['Solo novelas históricas','Únicamente mapas actuales','Predicciones del futuro'],'La arqueología reconstruye sociedades mediante evidencias materiales.'),
c('Un enterramiento prehistórico puede informar sobre…','Ritos, sociedad y condiciones de vida',['Resultados deportivos modernos','Tráfico aéreo','Cotizaciones bursátiles'],'Restos humanos y ajuar ofrecen información biológica, social y cultural.'),
c('¿Qué hace más fiable una interpretación arqueológica?','Comparar varias evidencias y documentar su contexto',['Basarse en un único rumor','Ignorar dónde apareció el objeto','Elegir la explicación más espectacular'],'Las conclusiones sólidas relacionan múltiples evidencias contextualizadas.'),
c('¿Qué es un yacimiento arqueológico?','Un lugar con restos de actividad humana del pasado',['Un archivo digital moderno','Una estación meteorológica','Una frontera política'],'Los yacimientos conservan restos y contextos de ocupaciones antiguas.'),
c('Si dos objetos aparecen en capas distintas, ¿qué debe hacer el arqueólogo?','Estudiar su posición antes de afirmar cuál es anterior',['Mezclarlos y olvidar la capa','Suponer que son de la misma fecha','Desechar el más profundo'],'La posición estratigráfica es una evidencia clave para establecer secuencias.')],
G05S01:[
c('Las primeras ciudades mesopotámicas se desarrollaron entre los ríos…','Tigris y Éufrates',['Nilo y Congo','Danubio y Rin','Tajo y Ebro'],'Mesopotamia se desarrolló en las cuencas del Tigris y el Éufrates.'),
c('¿Por qué era importante el regadío en Mesopotamia?','Permitía controlar agua para los cultivos',['Impedía cultivar cereales','Sustituía toda organización social','Eliminaba los ríos'],'Canales y diques ayudaron a aprovechar unas aguas irregulares.'),
c('Una ciudad-Estado mesopotámica era…','Una ciudad con territorio e instituciones propias',['Una provincia romana','Un país industrial moderno','Una aldea sin autoridad'],'Ciudades como Ur o Uruk organizaron su propio poder y territorio.'),
c('¿Qué escritura surgió en Mesopotamia?','La cuneiforme',['La imprenta','El alfabeto cirílico moderno','El código binario'],'La escritura cuneiforme se realizaba mediante signos en forma de cuña.'),
c('¿Sobre qué soporte se escribía frecuentemente en Mesopotamia?','Tablillas de arcilla',['Papel industrial','Pantallas digitales','Pergamino medieval exclusivamente'],'La arcilla húmeda permitía marcar signos y conservar registros.'),
c('¿Qué función podía tener un zigurat?','Religiosa y monumental',['Ser una fábrica de automóviles','Servir de aeropuerto','Cultivar arroz en terrazas'],'Los zigurats eran grandes construcciones vinculadas al culto urbano.'),
c('¿Qué necesidad impulsó registros escritos en las ciudades?','Administrar bienes, tributos e intercambios',['Evitar cualquier comercio','Eliminar los impuestos','Sustituir la agricultura por caza'],'La administración compleja necesitaba contabilizar recursos y obligaciones.'),
c('¿Qué relación hubo entre ríos y poder político mesopotámico?','Gestionar agua y excedentes exigía organización colectiva',['Los ríos hicieron innecesario gobernar','No hubo agricultura','Las ciudades evitaban el agua'],'Obras hidráulicas y almacenamiento requirieron coordinación y autoridad.')],
G05S02:[
c('¿Qué río fue esencial para la agricultura del antiguo Egipto?','El Nilo',['El Indo','El Tíber','El Sena'],'Las crecidas del Nilo aportaban agua y limos fértiles.'),
c('El faraón era…','La máxima autoridad política y religiosa',['Un ciudadano sin poder','Un cónsul romano','Un campesino elegido cada año'],'El faraón concentraba poder y tenía una dimensión religiosa.'),
c('¿Por qué las crecidas del Nilo eran valiosas?','Fertilizaban las tierras agrícolas',['Destruían siempre toda agricultura','Convertían el valle en desierto','Impedían almacenar grano'],'El limo depositado por el río renovaba la fertilidad del valle.'),
c('¿Qué función principal tenían las pirámides de Guiza?','Funeraria',['Industrial','Deportiva','Ferroviaria'],'Fueron monumentales complejos funerarios vinculados a faraones.'),
c('¿Qué tipo de escritura emplearon los egipcios en monumentos?','Jeroglífica',['Cuneiforme exclusivamente','Código Morse','Imprenta de tipos móviles'],'Los jeroglíficos combinaron signos figurativos en textos religiosos y monumentales.'),
c('¿Por qué la momificación era importante?','Se relacionaba con creencias sobre la vida después de la muerte',['Servía para cultivar','Era un sistema monetario','Sustituía la escritura'],'La conservación del cuerpo formaba parte de prácticas funerarias y religiosas.'),
c('¿Dónde se concentraba gran parte de la población egipcia?','En el valle y delta del Nilo',['En el centro del Sahara','En los Alpes','En islas del Pacífico'],'El agua y las tierras fértiles del Nilo concentraban agricultura y asentamientos.'),
c('¿Qué podían registrar los escribas egipcios?','Impuestos, cosechas y asuntos administrativos',['Solo cuentos infantiles','Únicamente mapas modernos','Resultados de fútbol'],'La escritura fue esencial para administrar recursos y el Estado.')],
G05S03:[
c('¿Por qué fue importante la escritura para los primeros Estados?','Permitió registrar impuestos, leyes y administración',['Eliminó la agricultura','Hizo innecesarias las ciudades','Sustituyó todos los intercambios'],'La escritura facilitó gestionar territorios, recursos y normas.'),
c('¿Qué caracteriza a un Estado antiguo frente a una pequeña aldea?','Instituciones capaces de organizar territorio y población',['Ausencia total de normas','Ninguna especialización','Solo familias aisladas'],'Los Estados articulan autoridad, administración y normas sobre comunidades amplias.'),
c('¿Para qué servían los tributos?','Para reunir recursos destinados al poder y obras colectivas',['Para eliminar toda producción','Para impedir el comercio','Para sustituir la escritura'],'Los tributos sostenían administración, ejércitos y obras públicas.'),
c('¿Qué favoreció la especialización del trabajo?','Los excedentes alimentarios',['La desaparición de la agricultura','La ausencia de ciudades','El nomadismo permanente'],'Los excedentes permitieron que parte de la población realizara tareas no agrícolas.'),
c('Una ley escrita permite…','Fijar normas y hacerlas consultables',['Eliminar todos los conflictos automáticamente','Evitar cualquier autoridad','Borrar la administración'],'La escritura ayuda a conservar y comunicar normas de forma estable.'),
c('¿Qué papel podían tener los ejércitos en los primeros Estados?','Defender y ampliar territorios y poder',['Cultivar exclusivamente','Sustituir a todos los artesanos','Eliminar fronteras por definición'],'La fuerza militar protegía recursos y también podía apoyar expansión política.'),
c('¿Por qué eran importantes los almacenes de grano?','Permitían gestionar excedentes y afrontar periodos difíciles',['Hacían imposible cobrar tributos','Eliminaban la necesidad de cosechar','Solo tenían función decorativa'],'Almacenar excedentes ayudaba a redistribuir recursos y sostener instituciones.'),
c('¿Qué relación hay entre ciudades y administración?','La concentración de población y recursos exige coordinación',['Las ciudades no necesitan normas','Administrar solo es posible en aldeas','La escritura impide gobernar ciudades'],'La vida urbana compleja requiere organizar obras, recursos y población.')],
G05S04:[
c('¿Qué rasgo compartieron Egipto y Mesopotamia?','Se desarrollaron vinculados a grandes ríos',['Fueron democracias modernas','Carecieron de agricultura','Nacieron en América'],'Ambas civilizaciones aprovecharon sistemas fluviales para agricultura y organización.'),
c('¿Qué diferencia geográfica básica existía?','Egipto se articuló en torno al Nilo y Mesopotamia al Tigris-Éufrates',['Ambas estaban en el mismo río','Egipto estaba en América','Mesopotamia estaba en Oceanía'],'Sus espacios fluviales fueron distintos y condicionaron su desarrollo.'),
c('Egipto y Mesopotamia compartieron…','Sociedades jerarquizadas y administración',['Industria digital','Sufragio universal moderno','Ferrocarriles'],'Ambas desarrollaron poderes organizados y grupos sociales diferenciados.'),
c('¿Qué comparación sobre escritura es correcta?','Ambas desarrollaron sistemas de escritura',['Ninguna conoció la escritura','Usaron exclusivamente el mismo alfabeto moderno','Solo escribían en papel'],'Jeroglíficos y cuneiforme fueron sistemas distintos usados para múltiples funciones.'),
c('¿Qué actividad dependía especialmente del control del agua en ambas regiones?','La agricultura',['La aviación','La industria automovilística','La minería espacial'],'El regadío y el ciclo de los ríos fueron fundamentales para producir alimentos.'),
c('¿Qué comparación religiosa es razonable?','Ambas sociedades tuvieron cultos y especialistas religiosos',['Ambas fueron sociedades sin religión','Practicaron exactamente los mismos cultos','Solo Roma tuvo templos'],'La religión ocupó un lugar relevante aunque dioses y prácticas fueran diferentes.'),
c('¿Por qué comparar civilizaciones requiere atender a semejanzas y diferencias?','Para evitar afirmar que sociedades distintas fueron idénticas',['Para memorizar una única fecha','Para ignorar el contexto','Para eliminar las fuentes'],'Comparar históricamente implica identificar rasgos comunes sin borrar particularidades.'),
c('¿Qué evidencia serviría para comparar sus administraciones?','Textos, sellos y registros conservados',['Predicciones meteorológicas actuales','Novelas de ciencia ficción','Fotografías por satélite antiguas inexistentes'],'Los documentos y objetos administrativos permiten estudiar cómo se organizaban.')],
G06S01:[
c('En la antigua Grecia, una polis era…','Una ciudad-Estado con instituciones propias',['Una provincia romana','Un templo egipcio','Una ruta oceánica'],'Las polis eran comunidades políticas independientes como Atenas o Esparta.'),
c('¿Qué espacio de la polis concentraba actividades públicas y comerciales?','El ágora',['El zigurat','El foro romano exclusivamente','La pirámide'],'El ágora era una plaza central de encuentro, mercado y vida cívica.'),
c('Atenas y Esparta eran…','Polis griegas con organizaciones diferentes',['Provincias egipcias','Emperadores romanos','Ríos mesopotámicos'],'El mundo griego estaba formado por numerosas polis autónomas.'),
c('¿Qué favoreció la formación de polis independientes?','Un relieve fragmentado y comunidades separadas',['Una llanura totalmente uniforme','Una única capital mundial','La red ferroviaria'],'Montañas, valles e islas contribuyeron a la fragmentación política.'),
c('¿Qué significa que una polis fuera autónoma?','Que tenía sus propias leyes e instituciones',['Que dependía de un faraón','Que no tenía habitantes','Que era una colonia romana'],'Cada polis organizaba su gobierno y ciudadanía.'),
c('¿Quiénes quedaban excluidos de la ciudadanía política ateniense clásica?','Mujeres, esclavos y extranjeros residentes',['Todos los varones ciudadanos','Los magistrados','Los participantes de la asamblea'],'La ciudadanía ateniense era restringida y no incluía a toda la población.'),
c('¿Qué era una colonia griega?','Un asentamiento fundado por griegos fuera de su polis de origen',['Una legión romana','Una tumba egipcia','Una tribu paleolítica'],'La colonización extendió asentamientos y contactos griegos por el Mediterráneo.'),
c('¿Qué elemento unía culturalmente a muchas polis pese a su independencia?','Lengua y prácticas religiosas compartidas',['Un único rey permanente','Las mismas leyes exactas','Una sola moneda obligatoria universal'],'Existían rasgos culturales comunes aunque no hubiera un Estado griego unificado.')],
G06S02:[
c('¿Qué legado se asocia especialmente a la Grecia clásica?','Filosofía, teatro y reflexión política',['Escritura cuneiforme','Pirámides faraónicas','Feudalismo medieval'],'La cultura griega dejó una influencia duradera en pensamiento, artes y política.'),
c('¿Qué buscaba la filosofía griega?','Explicar cuestiones mediante reflexión y argumentación',['Sustituir toda observación por rumores','Construir pirámides','Administrar el Nilo'],'Los filósofos desarrollaron formas racionales de preguntar y argumentar.'),
c('¿Dónde se representaban tragedias y comedias?','En teatros',['En zigurats','En acueductos','En pirámides funerarias'],'El teatro fue una manifestación central de la cultura cívica griega.'),
c('¿Qué característica destaca en parte de la escultura clásica?','Búsqueda de proporción y representación idealizada',['Uso exclusivo de plástico','Ausencia total de figura humana','Fotografía digital'],'Los artistas clásicos exploraron proporciones, movimiento e idealización del cuerpo.'),
c('¿Qué competición religiosa y deportiva nació en Grecia?','Los Juegos Olímpicos',['El Tour de Francia','La NBA','La Fórmula 1'],'Los juegos de Olimpia reunían competiciones vinculadas al culto de Zeus.'),
c('¿Qué aporta estudiar mitos griegos?','Información sobre valores, dioses y relatos culturales',['Una transcripción literal de todos los hechos','Datos meteorológicos exactos','Leyes romanas medievales'],'Los mitos son fuentes culturales que requieren interpretación, no crónicas literales.'),
c('¿Por qué la democracia ateniense no equivale a una democracia actual?','La participación política estaba restringida a una parte de la población',['No existían debates','Todos los habitantes votaban exactamente igual que hoy','Atenas era un imperio moderno'],'El sistema ateniense introdujo participación ciudadana pero con exclusiones importantes.'),
c('¿Qué legado arquitectónico griego sigue siendo reconocible?','Órdenes de columnas como dórico, jónico y corintio',['Rascacielos de acero','Catedrales góticas como creación griega','Zigurats cuneiformes'],'Los órdenes arquitectónicos griegos influyeron en edificios de épocas posteriores.')],
G06S03:[
c('¿Qué etapa de Roma fue posterior a la República?','El Imperio',['El Paleolítico','La polis','El Neolítico'],'La secuencia tradicional es Monarquía, República e Imperio.'),
c('¿Qué etapa precedió a la República romana?','La Monarquía',['El Imperio','La Edad Media','El Neolítico'],'Según la periodización tradicional, Roma pasó de Monarquía a República.'),
c('Durante la República, ¿qué institución tuvo gran importancia política?','El Senado',['El faraón','La ecclesia ateniense como órgano romano','El zigurat'],'El Senado fue una institución central de la vida política republicana.'),
c('¿Qué cambio marca convencionalmente el inicio del Imperio?','La concentración del poder en Augusto',['La fundación de Egipto','La revolución neolítica','La caída de Constantinopla'],'Augusto inauguró el Principado tras las guerras civiles del final republicano.'),
c('¿Qué permitió a Roma controlar un territorio tan amplio?','Ejército, administración y red de comunicaciones',['Ausencia de instituciones','Solo navegación aérea','No construir caminos'],'La organización militar y administrativa conectó provincias muy extensas.'),
c('¿Qué era una provincia romana?','Un territorio conquistado administrado por Roma',['Una polis independiente griega','Una tumba faraónica','Un campamento paleolítico'],'Roma organizó buena parte de sus conquistas en provincias.'),
c('¿Qué problema afectó al Imperio romano en sus últimos siglos occidentales?','Inestabilidad política, presiones externas y dificultades económicas',['Descubrimiento de América','Revolución industrial','Invención de internet'],'La crisis occidental tuvo causas múltiples internas y externas.'),
c('¿Qué fecha se usa convencionalmente para el fin del Imperio romano de Occidente?','476 d. C.',['476 a. C.','1492 d. C.','3000 a. C.'],'En 476 fue depuesto el último emperador romano de Occidente, una fecha convencional de periodización.')],
G06S04:[
c('La romanización fue…','La difusión de formas de vida, lengua e instituciones romanas',['La retirada total de Roma','La invención de la agricultura','La división de Grecia en polis'],'La integración provincial extendió elementos culturales y políticos romanos.'),
c('¿Qué infraestructura favoreció la romanización?','La red de calzadas',['Las pirámides egipcias','Los zigurats','Los castillos medievales'],'Las vías facilitaron movilidad de personas, ejércitos, mercancías e ideas.'),
c('¿Qué lengua difundió Roma ampliamente en Occidente?','El latín',['El sumerio','El egipcio jeroglífico','El japonés'],'El latín se extendió y está en el origen de las lenguas romances.'),
c('¿Qué muestra la presencia de foros, termas y anfiteatros en provincias?','La difusión de modelos urbanos romanos',['La ausencia de ciudades','El regreso al Paleolítico','La desaparición del comercio'],'Edificios públicos reflejan prácticas sociales y urbanísticas romanas.'),
c('¿Fue la romanización idéntica en todos los territorios?','No, varió según regiones y poblaciones',['Sí, eliminó instantáneamente toda cultura local','Solo ocurrió en Roma capital','No tuvo ningún efecto fuera de Italia'],'La integración fue desigual y convivió con tradiciones locales.'),
c('¿Qué institución jurídica romana dejó una influencia duradera?','El derecho romano',['La escritura cuneiforme','La momificación','El feudalismo como ley romana'],'Conceptos y tradiciones jurídicas romanas influyeron en sistemas posteriores.'),
c('¿Qué evidencia ayuda a estudiar la romanización de una ciudad?','Inscripciones, edificios, monedas y cerámicas',['Solo rumores actuales','Predicciones del futuro','Únicamente fotografías modernas'],'Fuentes escritas y materiales permiten observar cambios y continuidades.'),
c('¿Qué legado romano permanece en muchas ciudades europeas?','Trazados, obras públicas, lengua y derecho',['Zigurats mesopotámicos en todas ellas','Pirámides faraónicas como ayuntamientos','Ausencia completa de huellas'],'La presencia romana dejó legados materiales e institucionales diversos.')]
}

function rotate<T>(items:T[],shift:number){const n=((shift%items.length)+items.length)%items.length;return [...items.slice(n),...items.slice(0,n)]}
export function generateHistoryAncientQuestion(skill:SkillMeta,difficulty:number,seed:number):GeneratedQuestion|null{const cards=BANK[skill.id];if(!cards?.length)return null;const safe=Math.abs(seed);const card=cards[safe%cards.length];const answerIndex=(safe+difficulty)%4;const wrong=rotate(card.distractors,safe+difficulty);const options=wrong.slice(0,answerIndex).concat(card.answer,wrong.slice(answerIndex));return{skillId:skill.id,label:skill.name,difficulty,seed,prompt:card.prompt,options,answerIndex,solution:card.why,tags:[skill.generator_key,'geography_history','history_ancient_variety']}}
export function historyAncientQuestionCounts(){return Object.fromEntries(Object.entries(BANK).map(([id,cards])=>[id,cards.length]))}
