import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta = { id: string; name: string; generator_key: string }
type Card = { prompt: string; answer: string; distractors: [string,string,string]; why: string }

const BANK: Record<string, Card[]> = {
  gh_orientation: [{prompt:'¿Qué coordenada indica la distancia al norte o al sur del ecuador?',answer:'La latitud',distractors:['La longitud','La altitud','La escala'],why:'La latitud mide la posición norte-sur respecto al ecuador.'}],
  gh_scale: [{prompt:'En un mapa a escala 1:100 000, 1 cm representa…',answer:'1 km',distractors:['100 m','10 km','100 km'],why:'100 000 cm reales equivalen a 1 km.'}],
  gh_map_types: [{prompt:'¿Qué mapa representa principalmente montañas, ríos y relieve?',answer:'Un mapa físico',distractors:['Un mapa político','Un mapa electoral','Un plano urbano'],why:'El mapa físico representa elementos naturales y relieve.'}],
  gh_map_legend: [{prompt:'¿Para qué sirve la leyenda de un mapa?',answer:'Para explicar el significado de símbolos y colores',distractors:['Para indicar únicamente el norte','Para calcular la edad del mapa','Para sustituir la escala'],why:'La leyenda permite interpretar la simbología cartográfica.'}],
  gh_relief: [{prompt:'¿Qué forma del relieve es una extensión amplia y relativamente llana a poca altitud?',answer:'Llanura',distractors:['Valle','Cordillera','Acantilado'],why:'Una llanura es una superficie extensa con poco desnivel.'}],
  gh_world_location: [{prompt:'¿Qué océano se encuentra entre América y Europa-África?',answer:'Atlántico',distractors:['Índico','Ártico','Pacífico'],why:'El Atlántico separa América de Europa y África.'}],
  gh_rivers: [{prompt:'¿Cómo se llama el territorio cuyas aguas desembocan en un mismo río principal?',answer:'Cuenca hidrográfica',distractors:['Delta','Acuífero','Península'],why:'La cuenca reúne las aguas que drenan hacia un mismo sistema fluvial.'}],
  gh_relief_humans: [{prompt:'¿Por qué los grandes valles fluviales han favorecido históricamente el poblamiento?',answer:'Por el acceso al agua y a suelos fértiles',distractors:['Porque siempre tienen clima polar','Porque impiden la agricultura','Porque carecen de vías naturales'],why:'Agua, suelos y comunicaciones han favorecido asentamientos y agricultura.'}],
  gh_weather_climate: [{prompt:'“Hoy llueve y hay 9 °C” describe principalmente…',answer:'El tiempo atmosférico',distractors:['El clima','La latitud','Una estación climática'],why:'El tiempo describe condiciones atmosféricas en un momento concreto.'}],
  gh_climate_factors: [{prompt:'A igual latitud, ¿qué suele ocurrir con la temperatura al aumentar la altitud?',answer:'Disminuye',distractors:['Aumenta siempre','No cambia nunca','Se duplica'],why:'En general, la temperatura desciende con la altitud.'}],
  gh_climate_graphs: [{prompt:'En un climograma, las barras suelen representar…',answer:'Las precipitaciones',distractors:['La longitud','La población','La presión política'],why:'Habitualmente las barras muestran precipitación y la línea, temperatura.'}],
  gh_climate_impact: [{prompt:'¿Qué medida reduce la vulnerabilidad ante una sequía prolongada?',answer:'Ahorrar y gestionar eficientemente el agua',distractors:['Aumentar las fugas de la red','Eliminar toda vegetación','Impermeabilizar todos los suelos'],why:'La gestión eficiente reduce presión sobre reservas limitadas.'}],
  gh_chronology: [{prompt:'¿Qué fecha es anterior?',answer:'1200 a. C.',distractors:['800 a. C.','200 a. C.','50 d. C.'],why:'En fechas a. C., un número mayor está más alejado del presente.'}],
  gh_palaeolithic: [{prompt:'La economía paleolítica se basaba principalmente en…',answer:'Caza, pesca y recolección',distractors:['Industria mecanizada','Agricultura intensiva','Comercio transoceánico'],why:'Las sociedades paleolíticas eran esencialmente cazadoras-recolectoras.'}],
  gh_neolithic: [{prompt:'¿Qué cambio caracteriza la revolución neolítica?',answer:'La agricultura y la sedentarización',distractors:['La invención del motor','La desaparición de herramientas','El abandono de poblados'],why:'Producción de alimentos y vida sedentaria transformaron las sociedades.'}],
  gh_prehistory_sources: [{prompt:'Una herramienta de piedra hallada en una excavación es…',answer:'Una fuente arqueológica material',distractors:['Una fuente oral contemporánea','Una ley moderna','Una fotografía medieval'],why:'Los objetos materiales son evidencias arqueológicas del pasado.'}],
  gh_mesopotamia: [{prompt:'Las primeras ciudades mesopotámicas se desarrollaron entre los ríos…',answer:'Tigris y Éufrates',distractors:['Nilo y Congo','Danubio y Rin','Tajo y Ebro'],why:'Mesopotamia significa región entre ríos, Tigris y Éufrates.'}],
  gh_egypt: [{prompt:'¿Qué río fue esencial para la agricultura del antiguo Egipto?',answer:'El Nilo',distractors:['El Indo','El Tíber','El Sena'],why:'Las crecidas del Nilo aportaban agua y limos fértiles.'}],
  gh_early_states: [{prompt:'¿Por qué fue importante la escritura para los primeros Estados?',answer:'Permitió registrar impuestos, leyes y administración',distractors:['Eliminó la agricultura','Hizo innecesarias las ciudades','Sustituyó todos los intercambios'],why:'La escritura facilitó gestionar territorios, recursos y normas.'}],
  gh_compare_civilisations: [{prompt:'¿Qué rasgo compartieron Egipto y Mesopotamia?',answer:'Se desarrollaron vinculados a grandes ríos',distractors:['Fueron democracias modernas','Carecieron de agricultura','Nacieron en América'],why:'Ambas civilizaciones aprovecharon sistemas fluviales para agricultura y organización.'}],
  gh_greece_polis: [{prompt:'En la antigua Grecia, una polis era…',answer:'Una ciudad-Estado con instituciones propias',distractors:['Una provincia romana','Un templo egipcio','Una ruta comercial oceánica'],why:'Las polis eran comunidades políticas independientes como Atenas o Esparta.'}],
  gh_greece_culture: [{prompt:'¿Qué legado se asocia especialmente a la Grecia clásica?',answer:'Filosofía, teatro y reflexión política',distractors:['Escritura cuneiforme','Pirámides faraónicas','Feudalismo medieval'],why:'La cultura griega dejó una influencia duradera en filosofía, artes y política.'}],
  gh_rome_stages: [{prompt:'¿Qué etapa de Roma fue posterior a la República?',answer:'El Imperio',distractors:['El Paleolítico','La polis','El Neolítico'],why:'La secuencia tradicional es Monarquía, República e Imperio.'}],
  gh_romanisation: [{prompt:'La romanización fue…',answer:'La difusión de formas de vida, lengua e instituciones romanas',distractors:['La retirada total de Roma de sus provincias','La invención de la agricultura','La división de Grecia en polis'],why:'La integración provincial extendió elementos culturales y políticos romanos.'}],

  bg_hypotheses: [{prompt:'¿Cuál es una hipótesis científica comprobable?',answer:'Si una planta recibe menos luz, crecerá menos en dos semanas',distractors:['Las plantas son bonitas','La naturaleza es perfecta','Me gusta más la luz azul'],why:'Una hipótesis científica debe poder contrastarse con observaciones o experimentos.'}],
  bg_variables: [{prompt:'Al probar cómo afecta la luz al crecimiento, ¿qué variable debemos cambiar deliberadamente?',answer:'La cantidad de luz',distractors:['Todas las condiciones a la vez','La conclusión','El nombre de la planta'],why:'La variable independiente es la que se modifica para estudiar su efecto.'}],
  bg_data_evidence: [{prompt:'Tres plantas con abono crecen 12, 11 y 13 cm; tres sin abono, 5, 6 y 5 cm. ¿Qué apoyan estos datos?',answer:'En estas condiciones, el grupo con abono creció más',distractors:['El abono siempre duplica cualquier planta','No existe diferencia alguna','Todas las plantas crecerán 13 cm'],why:'La conclusión debe limitarse a lo que muestran los datos observados.'}],
  bg_science_sources: [{prompt:'¿Qué fuente ofrece mejor respaldo para una afirmación científica?',answer:'Un estudio revisado con método y datos descritos',distractors:['Un rumor sin fuente','Un anuncio sin evidencias','Una opinión anónima'],why:'La evidencia científica debe ser trazable y evaluable.'}],
  bg_earth_systems: [{prompt:'¿A qué sistema terrestre pertenece el agua de océanos, ríos y lagos?',answer:'Hidrosfera',distractors:['Geosfera','Atmósfera','Biosfera únicamente'],why:'La hidrosfera reúne el agua del planeta.'}],
  bg_rocks_minerals: [{prompt:'¿Qué diferencia básica hay entre mineral y roca?',answer:'Una roca puede estar formada por uno o varios minerales',distractors:['Toda roca es un único elemento químico','Los minerales están hechos de animales','No existe diferencia'],why:'Los minerales son sustancias naturales con propiedades definidas; las rocas son agregados.'}],
  bg_rock_cycle: [{prompt:'Una roca sometida a alta presión y temperatura sin fundirse puede transformarse en…',answer:'Roca metamórfica',distractors:['Roca sedimentaria por evaporación','Magma directamente siempre','Suelo orgánico'],why:'Presión y temperatura producen metamorfismo sin necesidad de fusión.'}],
  bg_geological_processes: [{prompt:'¿Qué proceso transporta sedimentos después de la erosión?',answer:'El transporte',distractors:['La fotosíntesis','La digestión','La reproducción'],why:'Tras erosionarse, los materiales pueden ser transportados y luego sedimentados.'}],
  bg_cell_theory: [{prompt:'Según la teoría celular, la unidad básica de los seres vivos es…',answer:'La célula',distractors:['El mineral','El átomo de hierro','El río'],why:'Todos los seres vivos están constituidos por una o más células.'}],
  bg_cell_parts: [{prompt:'¿Qué estructura celular contiene principalmente el material genético en una célula eucariota?',answer:'El núcleo',distractors:['La pared de un edificio','El cloroplasto en todas las células','El suelo'],why:'El núcleo alberga la mayor parte del ADN eucariota.'}],
  bg_plant_animal_cells: [{prompt:'¿Qué estructura es característica de las células vegetales y participa en la fotosíntesis?',answer:'El cloroplasto',distractors:['El centríolo como regla universal','La neurona','El glóbulo rojo'],why:'Los cloroplastos contienen la maquinaria fotosintética de células vegetales.'}],
  bg_levels_organisation: [{prompt:'¿Cuál es el orden correcto de menor a mayor organización?',answer:'Célula → tejido → órgano → sistema → organismo',distractors:['Órgano → célula → organismo → tejido → sistema','Tejido → planeta → célula → órgano → organismo','Sistema → órgano → tejido → célula → organismo'],why:'Las células forman tejidos; estos, órganos; los órganos, sistemas.'}],
  bg_life_characteristics: [{prompt:'¿Cuál es una característica común de los seres vivos?',answer:'Realizan funciones vitales y mantienen organización celular',distractors:['Todos pueden volar','Todos producen su propio alimento','Todos viven en tierra'],why:'La organización celular y las funciones vitales son rasgos generales de la vida.'}],
  bg_classification: [{prompt:'Una clave de clasificación sirve para…',answer:'Identificar organismos mediante características observables',distractors:['Medir solo su masa','Cambiar su ADN','Decidir cuál es más bonito'],why:'Las claves usan rasgos para distinguir e identificar organismos.'}],
  bg_living_groups: [{prompt:'¿Cuál de estos organismos es un vertebrado?',answer:'Una trucha',distractors:['Una medusa','Una lombriz','Un caracol'],why:'Los peces, como la trucha, poseen columna vertebral.'}],
  bg_biodiversity: [{prompt:'Biodiversidad se refiere a…',answer:'La variedad de seres vivos, genes y ecosistemas',distractors:['Solo al número de árboles','Solo a animales domésticos','A la temperatura media'],why:'La biodiversidad incluye diversidad genética, de especies y ecosistemas.'}],
  bg_ecosystem_factors: [{prompt:'¿Cuál es un factor abiótico de un ecosistema?',answer:'La temperatura',distractors:['Un roble','Un lobo','Una bacteria'],why:'Los factores abióticos son componentes no vivos del medio.'}],
  bg_food_webs: [{prompt:'En una cadena alimentaria, un productor es normalmente…',answer:'Un organismo fotosintético como una planta',distractors:['Un depredador superior','Un hongo descomponedor siempre','Un consumidor secundario'],why:'Los productores fabrican materia orgánica a partir de fuentes inorgánicas de energía.'}],
  bg_ecological_interactions: [{prompt:'Si disminuye mucho una presa, ¿qué puede ocurrir con un depredador que depende de ella?',answer:'Puede disminuir por falta de alimento',distractors:['Aumentará necesariamente sin límite','Se convertirá en planta','No puede verse afectado'],why:'Las poblaciones están conectadas por relaciones alimentarias.'}],
  bg_ecosystem_impact: [{prompt:'¿Qué acción favorece directamente la conservación de un hábitat?',answer:'Proteger y restaurar sus zonas degradadas',distractors:['Aumentar vertidos','Fragmentarlo con barreras innecesarias','Eliminar especies autóctonas'],why:'La protección y restauración mantienen funciones y biodiversidad.'}],
  bg_healthy_habits: [{prompt:'¿Qué combinación favorece la salud en la adolescencia?',answer:'Dormir suficiente, moverse con regularidad y mantener higiene',distractors:['Dormir muy poco cada día','Eliminar toda actividad física','Sustituir agua por bebidas azucaradas'],why:'Sueño, actividad e higiene son pilares básicos de salud.'}],
  bg_nutrition: [{prompt:'¿Qué nutriente tiene como función principal aportar energía rápida al organismo?',answer:'Los hidratos de carbono',distractors:['El agua como única fuente energética','Las vitaminas como combustible principal','Las sales minerales como única energía'],why:'Los carbohidratos son una fuente energética principal.'}],
  bg_environmental_health: [{prompt:'Reducir la contaminación del aire puede beneficiar…',answer:'A la salud humana y a los ecosistemas',distractors:['Solo a las rocas','Únicamente a vehículos','A ningún ser vivo'],why:'La calidad ambiental influye en organismos y salud pública.'}],
  bg_sustainable_choices: [{prompt:'¿Qué opción suele ser más sostenible para un trayecto urbano corto?',answer:'Caminar o ir en bicicleta cuando sea seguro',distractors:['Usar un coche vacío siempre','Dejar el motor encendido sin necesidad','Elegir la ruta con mayor consumo'],why:'La movilidad activa reduce consumo de energía y emisiones.'}],
}

function hash(seed:number, salt:string) { let x=seed>>>0; for(const c of salt){x=Math.imul(x^c.charCodeAt(0),16777619)>>>0} return x>>>0 }
function make(skill:SkillMeta,difficulty:number,seed:number,card:Card):GeneratedQuestion {
  const options=[card.answer,...card.distractors]
  const shift=hash(seed,skill.generator_key)%4
  const rotated=options.slice(shift).concat(options.slice(0,shift))
  return { skillId:skill.id,label:skill.name,difficulty,seed,prompt:card.prompt,options:rotated,answerIndex:rotated.indexOf(card.answer),solution:card.why,tags:[skill.generator_key,skill.id.startsWith('G')?'geography_history':'biology_geology'] }
}

export function knowledgeGeneratorKeys(){ return Object.keys(BANK) }
export function generateKnowledgeSubjectQuestion(skill:SkillMeta,difficulty:number,seed:number):GeneratedQuestion|null {
  const cards=BANK[skill.generator_key]
  if(!cards?.length) return null
  const card=cards[hash(seed+Math.max(1,difficulty),skill.id)%cards.length]
  return make(skill,difficulty,seed,card)
}
