import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta = { id: string; name: string; generator_key: string }
type Card = { prompt: string; answer: string; distractors: [string,string,string]; solution: string; level: number }

const BANK: Record<string, Card[]> = {
  B03S01: [
    { level:1, prompt:'¿Qué idea resume mejor la teoría celular?', answer:'Todos los seres vivos están formados por una o más células', distractors:['Todos los seres vivos tienen exactamente el mismo tipo de célula','Solo los animales están formados por células','Las células aparecen únicamente en organismos microscópicos'], solution:'La teoría celular establece que la célula es la unidad básica de los seres vivos.' },
    { level:1, prompt:'Una bacteria está formada por una sola célula. ¿Sigue siendo un ser vivo según la teoría celular?', answer:'Sí, porque una sola célula puede constituir un organismo', distractors:['No, porque todo ser vivo necesita al menos dos células','Solo si tiene tejidos y órganos','Solo si puede verse a simple vista'], solution:'Los organismos unicelulares son seres vivos completos formados por una sola célula.' },
    { level:2, prompt:'¿Qué observación apoyaría mejor que la célula es la unidad básica de la vida?', answer:'Encontrar células en tejidos de organismos muy diferentes', distractors:['Encontrar minerales dentro de una roca','Observar que todos los animales tienen el mismo tamaño','Comprobar que todos los seres vivos viven en agua'], solution:'La presencia generalizada de células en distintos organismos apoya su papel como unidad básica.' },
    { level:2, prompt:'Si una herida de la piel cicatriza mediante división de células cercanas, ¿qué principio celular ilustra?', answer:'Las células proceden de otras células preexistentes', distractors:['Todas las células tienen cloroplastos','Todas las células son idénticas','Las células solo se forman a partir de minerales'], solution:'La cicatrización implica proliferación de células ya existentes.' },
    { level:3, prompt:'Un investigador afirma que un nuevo organismo no contiene células. ¿Qué sería necesario comprobar primero?', answer:'Examinar muestras del organismo con técnicas microscópicas adecuadas', distractors:['Medir únicamente su masa','Comparar su color con otros organismos','Contar solo cuántas extremidades tiene'], solution:'La afirmación contradice un principio central y debe contrastarse observando su estructura.' },
    { level:3, prompt:'¿Por qué el descubrimiento de células mediante microscopía fue importante para la biología?', answer:'Permitió observar una estructura común a todos los seres vivos', distractors:['Demostró que todos los seres vivos son macroscópicos','Eliminó la necesidad de estudiar tejidos','Probó que todas las células cumplen exactamente la misma función'], solution:'La microscopía permitió reconocer la organización celular compartida por la vida.' },
    { level:4, prompt:'Un tejido aumenta de tamaño durante el crecimiento. ¿Qué explicación encaja mejor con la teoría celular?', answer:'Aumenta el número de células y, en algunos casos, también su tamaño', distractors:['El tejido crece sin intervención de células','Las células desaparecen y son sustituidas por minerales','El crecimiento solo puede deberse a acumulación de agua'], solution:'El crecimiento de tejidos depende de procesos celulares, especialmente división y aumento celular.' },
    { level:4, prompt:'¿Qué conclusión sería demasiado fuerte a partir de la teoría celular?', answer:'Todas las células de todos los organismos son iguales en estructura y función', distractors:['Las células son unidades fundamentales de los seres vivos','Las nuevas células proceden de células anteriores','Los organismos pueden estar formados por una o muchas células'], solution:'La teoría celular no afirma que todas las células sean idénticas; existe gran especialización.' },
  ],
  B03S02: [
    { level:1, prompt:'¿Qué estructura controla qué sustancias entran y salen de la célula?', answer:'La membrana plasmática', distractors:['El núcleo','El citoplasma','El ribosoma'], solution:'La membrana regula el intercambio entre la célula y el medio.' },
    { level:1, prompt:'¿Dónde se encuentra la mayor parte del material genético de una célula eucariota?', answer:'En el núcleo', distractors:['En la membrana plasmática','En la pared celular','En el vacuolo'], solution:'El núcleo contiene la mayor parte del ADN de las células eucariotas.' },
    { level:2, prompt:'¿Qué orgánulo está especialmente relacionado con la obtención de energía utilizable mediante respiración celular?', answer:'La mitocondria', distractors:['El ribosoma','El lisosoma','El aparato de Golgi'], solution:'Las mitocondrias realizan etapas clave de la respiración celular.' },
    { level:2, prompt:'Una célula fabrica muchas proteínas. ¿Qué estructuras deben ser especialmente activas?', answer:'Los ribosomas', distractors:['Los cloroplastos','Las paredes celulares','Los centríolos'], solution:'Los ribosomas son los lugares donde se sintetizan proteínas.' },
    { level:3, prompt:'Una sustancia bloquea el paso selectivo de nutrientes hacia una célula. ¿Qué estructura se ha visto afectada de forma más directa?', answer:'La membrana plasmática', distractors:['El nucléolo','El citoesqueleto únicamente','La cromatina únicamente'], solution:'El transporte selectivo hacia el interior depende de la membrana plasmática.' },
    { level:3, prompt:'¿Qué relación estructura-función es correcta?', answer:'Núcleo — contiene información genética y participa en el control celular', distractors:['Ribosoma — almacena toda el agua de la célula','Mitocondria — fabrica la pared celular','Membrana — contiene todo el ADN eucariota'], solution:'El núcleo alberga el ADN y participa en la regulación de la actividad celular.' },
    { level:4, prompt:'Una célula muscular necesita mucha energía para contraerse repetidamente. ¿Qué adaptación sería razonable?', answer:'Tener numerosas mitocondrias', distractors:['Carecer de membrana plasmática','Perder todos sus ribosomas','No contener citoplasma'], solution:'Un mayor número de mitocondrias favorece una elevada demanda energética.' },
    { level:4, prompt:'Si una célula no pudiera fabricar proteínas nuevas, ¿qué estructura estaría fallando de manera más directa?', answer:'Los ribosomas', distractors:['La membrana nuclear exclusivamente','El vacuolo central','La pared celular'], solution:'La síntesis de proteínas ocurre en los ribosomas.' },
  ],
  B03S03: [
    { level:1, prompt:'¿Qué estructura aparece en células vegetales y no en las animales típicas?', answer:'La pared celular', distractors:['La membrana plasmática','El citoplasma','Los ribosomas'], solution:'La pared celular es característica de células vegetales; membrana, citoplasma y ribosomas aparecen en ambos tipos.' },
    { level:1, prompt:'¿Qué orgánulo permite a muchas células vegetales realizar fotosíntesis?', answer:'El cloroplasto', distractors:['La mitocondria','El ribosoma','El núcleo'], solution:'Los cloroplastos contienen la maquinaria fotosintética.' },
    { level:2, prompt:'¿Qué estructura comparten una célula animal y una vegetal?', answer:'La membrana plasmática', distractors:['La pared celular','El cloroplasto','El gran vacuolo central como rasgo universal'], solution:'Ambas poseen membrana plasmática, además de otras estructuras comunes.' },
    { level:2, prompt:'Una célula observada tiene pared celular, cloroplastos y una gran vacuola. ¿De qué tipo es probablemente?', answer:'Vegetal', distractors:['Animal','Bacteriana sin más datos','Un glóbulo rojo'], solution:'La combinación de pared, cloroplastos y gran vacuola es típica de células vegetales.' },
    { level:3, prompt:'¿Por qué una célula de raíz puede ser vegetal aunque no tenga cloroplastos desarrollados?', answer:'Porque no todas las células vegetales fotosintetizan y puede conservar otros rasgos vegetales', distractors:['Porque todas las células sin cloroplastos son animales','Porque las raíces no están formadas por células','Porque la pared celular solo existe en animales'], solution:'La presencia de cloroplastos depende de la función y exposición a la luz; no define por sí sola toda célula vegetal.' },
    { level:3, prompt:'¿Qué comparación es correcta?', answer:'Las células vegetales y animales tienen mitocondrias, pero las vegetales suelen poseer además pared celular', distractors:['Solo las células animales tienen membrana','Solo las células vegetales tienen ADN','Las células animales realizan fotosíntesis en cloroplastos'], solution:'Ambos tipos eucariotas comparten muchas estructuras; pared y cloroplastos distinguen a muchas vegetales.' },
    { level:4, prompt:'Una célula necesita mantener una forma rígida frente a cambios de agua. ¿Qué estructura vegetal contribuye especialmente?', answer:'La pared celular', distractors:['El núcleo','El ribosoma','El nucléolo'], solution:'La pared celular aporta soporte mecánico y resistencia.' },
    { level:4, prompt:'¿Qué inferencia es válida al observar cloroplastos en una célula?', answer:'Probablemente pertenece a un tejido fotosintético de una planta o alga', distractors:['Seguro pertenece a un animal','No contiene ADN','No puede realizar respiración celular'], solution:'Los cloroplastos indican capacidad fotosintética, pero la célula también puede respirar y contener ADN.' },
  ],
  B03S04: [
    { level:1, prompt:'Ordena de menor a mayor nivel de organización.', answer:'Célula → tejido → órgano → sistema → organismo', distractors:['Tejido → célula → sistema → órgano → organismo','Órgano → tejido → célula → organismo → sistema','Sistema → órgano → organismo → tejido → célula'], solution:'Las células forman tejidos, los tejidos órganos, los órganos sistemas y los sistemas organismos.' },
    { level:1, prompt:'Un conjunto de células similares que realizan una función común forma un…', answer:'Tejido', distractors:['Órgano','Sistema','Organismo'], solution:'Un tejido es un conjunto organizado de células semejantes o coordinadas.' },
    { level:2, prompt:'El corazón contiene distintos tejidos que trabajan juntos. ¿Qué nivel de organización representa?', answer:'Órgano', distractors:['Célula','Tejido','Sistema'], solution:'Un órgano está formado por varios tejidos que colaboran en una función.' },
    { level:2, prompt:'El aparato digestivo incluye varios órganos coordinados. ¿Qué nivel representa?', answer:'Sistema o aparato', distractors:['Tejido','Célula','Orgánulo'], solution:'Un sistema o aparato integra varios órganos relacionados funcionalmente.' },
    { level:3, prompt:'¿Qué ejemplo muestra correctamente una relación entre niveles?', answer:'Células musculares → tejido muscular → corazón', distractors:['Corazón → célula muscular → tejido muscular','Tejido nervioso → neurona → cerebro','Organismo → órgano → tejido → célula como formación ascendente'], solution:'Las células se integran en tejidos y estos contribuyen a formar órganos.' },
    { level:3, prompt:'Una lesión afecta a muchas células de un mismo tipo organizadas en una capa. ¿Qué nivel está afectado directamente?', answer:'Un tejido', distractors:['Un sistema completo necesariamente','Un organismo completo necesariamente','Una molécula únicamente'], solution:'Una capa organizada de células similares corresponde a un tejido.' },
    { level:4, prompt:'¿Por qué un órgano no puede describirse simplemente como muchas células juntas?', answer:'Porque contiene tejidos distintos organizados para una función concreta', distractors:['Porque los órganos no contienen células','Porque un órgano siempre es una sola célula gigante','Porque todos los tejidos de un órgano son idénticos'], solution:'La organización y cooperación de diferentes tejidos define al órgano.' },
    { level:4, prompt:'Si falla un órgano clave dentro de un sistema, ¿qué consecuencia es más razonable?', answer:'Puede alterarse el funcionamiento del sistema y del organismo', distractors:['Solo cambia el color de sus células','No puede afectar a ningún otro nivel','El órgano se convierte automáticamente en tejido'], solution:'Los niveles de organización están conectados funcionalmente.' },
  ],
  B04S01: [
    { level:1, prompt:'¿Cuál es una característica común a todos los seres vivos?', answer:'Están formados por células y realizan funciones vitales', distractors:['Todos se desplazan de un lugar a otro','Todos realizan fotosíntesis','Todos tienen órganos'], solution:'La organización celular y las funciones vitales son rasgos generales de la vida.' },
    { level:1, prompt:'Una planta no camina. ¿Por qué sigue siendo un ser vivo?', answer:'Porque está formada por células y realiza nutrición, relación y reproducción', distractors:['Porque todo lo verde es un ser vivo','Porque no necesita intercambiar materia','Porque las plantas no responden al ambiente'], solution:'El movimiento locomotor no es requisito para estar vivo.' },
    { level:2, prompt:'¿Qué proceso pertenece a la función de nutrición?', answer:'Obtener y transformar materia y energía', distractors:['Producir descendencia','Detectar exclusivamente sonidos','Clasificar otros organismos'], solution:'La nutrición incluye incorporación y transformación de materia y energía.' },
    { level:2, prompt:'Una planta orienta su crecimiento hacia la luz. ¿Qué función vital demuestra?', answer:'Relación', distractors:['Reproducción','Nutrición exclusivamente','Clasificación'], solution:'Responder a un estímulo ambiental forma parte de la función de relación.' },
    { level:3, prompt:'Un organismo unicelular detecta alimento y se desplaza hacia él. ¿Qué demuestra?', answer:'Que una sola célula puede realizar funciones vitales completas', distractors:['Que solo los organismos con órganos responden al entorno','Que la nutrición no requiere células','Que los unicelulares no son seres vivos'], solution:'Los organismos unicelulares realizan por sí mismos las funciones necesarias para vivir.' },
    { level:3, prompt:'¿Cuál de estas observaciones sería mejor evidencia de que una estructura desconocida está viva?', answer:'Mantiene organización celular y realiza intercambios y respuestas reguladas', distractors:['Tiene forma redondeada','Es de color verde','Se encuentra cerca de otros organismos'], solution:'La vida se reconoce por procesos y organización, no por un color o una forma concreta.' },
    { level:4, prompt:'¿Por qué crecer no basta por sí solo para demostrar que algo está vivo?', answer:'Porque estructuras no vivas, como cristales, también pueden aumentar de tamaño', distractors:['Porque los seres vivos nunca crecen','Porque solo los animales crecen','Porque el crecimiento no implica cambios de materia'], solution:'Hay que considerar un conjunto de características vitales, no una sola.' },
    { level:4, prompt:'¿Qué afirmación distingue mejor reproducción de crecimiento?', answer:'La reproducción origina nuevos individuos; el crecimiento aumenta tamaño o masa del individuo', distractors:['Ambos procesos son exactamente lo mismo','El crecimiento siempre produce descendencia','La reproducción solo ocurre en organismos unicelulares'], solution:'Son procesos diferentes aunque ambos formen parte del ciclo vital.' },
  ],
  B04S02: [
    { level:1, prompt:'¿Para qué sirve una clave de clasificación?', answer:'Para identificar organismos usando características observables', distractors:['Para cambiar sus características','Para medir únicamente su masa','Para ordenar organismos por preferencia personal'], solution:'Las claves guían la identificación mediante rasgos comparables.' },
    { level:1, prompt:'¿Qué rasgo es útil para clasificar animales de forma científica?', answer:'Presencia o ausencia de columna vertebral', distractors:['Que nos parezcan bonitos','El nombre que les ponga cada persona','El lugar donde los vimos una sola vez'], solution:'Los criterios de clasificación deben ser observables y consistentes.' },
    { level:2, prompt:'Una clave pregunta primero “¿tiene plumas?”. ¿Qué tipo de criterio usa?', answer:'Un rasgo observable del organismo', distractors:['Una opinión sobre su comportamiento','Una medida del clima únicamente','Un criterio sin relación con el organismo'], solution:'Las plumas son una característica física observable.' },
    { level:2, prompt:'Dos organismos se parecen en color pero difieren en estructura corporal. ¿Qué criterio suele ser más fiable?', answer:'Comparar varios rasgos estructurales y funcionales', distractors:['Usar solo el color','Elegir el organismo más grande','Clasificarlos según el día de observación'], solution:'La clasificación robusta se apoya en varios caracteres relevantes.' },
    { level:3, prompt:'¿Por qué una clave dicotómica ofrece dos opciones en cada paso?', answer:'Para ir reduciendo posibilidades mediante decisiones sucesivas', distractors:['Porque todos los organismos tienen exactamente dos rasgos','Porque solo existen dos grupos de seres vivos','Para evitar observar características'], solution:'Cada bifurcación descarta alternativas y acerca a una identificación.' },
    { level:3, prompt:'Si dos especies comparten muchas características, ¿qué conclusión es prudente?', answer:'Pueden estar más relacionadas que especies con menos rasgos compartidos', distractors:['Son necesariamente la misma especie','No pueden pertenecer al mismo grupo','La clasificación deja de ser útil'], solution:'Los rasgos compartidos ayudan a establecer semejanzas y relaciones, aunque no bastan solos para afirmar identidad.' },
    { level:4, prompt:'Una clave basada solo en “vive en agua / vive en tierra” falla con una rana adulta. ¿Qué mejora sería adecuada?', answer:'Añadir rasgos anatómicos y del ciclo vital además del hábitat', distractors:['Eliminar todos los criterios menos el color','Clasificar cada individuo en un grupo distinto','Usar únicamente el tamaño corporal'], solution:'Los organismos pueden usar varios hábitats; conviene combinar criterios independientes.' },
    { level:4, prompt:'¿Qué hace científico a un criterio de clasificación escolar?', answer:'Que sea definido, observable y aplicable de forma consistente', distractors:['Que dependa del gusto de quien clasifica','Que cambie para obtener el resultado deseado','Que solo funcione con un individuo concreto'], solution:'La reproducibilidad y claridad del criterio son esenciales.' },
  ],
  B04S03: [
    { level:1, prompt:'¿Cuál de estos animales es vertebrado?', answer:'Una trucha', distractors:['Una medusa','Una lombriz','Un pulpo'], solution:'La trucha es un pez y posee columna vertebral.' },
    { level:1, prompt:'¿Cuál de estos organismos es un hongo?', answer:'Una seta', distractors:['Un pino','Una bacteria','Una mariposa'], solution:'Las setas son estructuras reproductoras de ciertos hongos.' },
    { level:2, prompt:'¿Qué rasgo distingue de forma general a las plantas de los animales?', answer:'Muchas plantas realizan fotosíntesis gracias a cloroplastos', distractors:['Todas las plantas se desplazan activamente','Todos los animales tienen pared celular','Las plantas carecen de células'], solution:'La fotosíntesis es característica de muchos vegetales y depende de cloroplastos.' },
    { level:2, prompt:'Una levadura es unicelular y no realiza fotosíntesis. ¿A qué gran grupo pertenece?', answer:'Hongos', distractors:['Plantas','Animales vertebrados','Algas necesariamente'], solution:'Las levaduras son hongos unicelulares.' },
    { level:3, prompt:'Un organismo microscópico carece de núcleo definido. ¿Qué grupo encaja mejor?', answer:'Bacterias', distractors:['Animales','Plantas','Hongos eucariotas'], solution:'Las bacterias son procariotas y no poseen núcleo delimitado por membrana.' },
    { level:3, prompt:'¿Qué combinación corresponde mejor a un insecto?', answer:'Invertebrado con seis patas y cuerpo dividido en regiones', distractors:['Vertebrado con plumas','Invertebrado con ocho patas como rasgo del grupo','Vertebrado acuático con branquias'], solution:'Los insectos son artrópodos invertebrados con seis patas.' },
    { level:4, prompt:'¿Por qué “microorganismo” no equivale a un único gran grupo biológico?', answer:'Porque incluye organismos microscópicos de grupos diferentes', distractors:['Porque todos los microorganismos son bacterias','Porque ningún microorganismo está vivo','Porque solo describe organismos acuáticos'], solution:'El tamaño microscópico agrupa por escala, no por parentesco o estructura.' },
    { level:4, prompt:'Un organismo tiene células con pared, no posee cloroplastos y absorbe nutrientes del medio. ¿Qué grupo es probable?', answer:'Hongos', distractors:['Animales','Plantas fotosintéticas típicas','Vertebrados'], solution:'Los hongos tienen pared celular, carecen de cloroplastos y obtienen nutrientes por absorción.' },
  ],
  B04S04: [
    { level:1, prompt:'¿Qué significa biodiversidad?', answer:'Variedad de genes, especies y ecosistemas', distractors:['Cantidad de agua de una región','Número de edificios de una ciudad','Solo el número de animales domésticos'], solution:'La biodiversidad incluye varios niveles de variedad biológica.' },
    { level:1, prompt:'¿Qué lugar tendría normalmente mayor biodiversidad?', answer:'Un bosque con muchas especies y hábitats', distractors:['Un monocultivo de una sola especie','Una superficie asfaltada sin vegetación','Un recipiente con una única bacteria'], solution:'Más variedad de especies y ambientes suele implicar mayor biodiversidad.' },
    { level:2, prompt:'¿Por qué clasificar especies ayuda a estudiar la biodiversidad?', answer:'Permite identificarlas, compararlas y registrar su presencia de forma ordenada', distractors:['Hace que aparezcan nuevas especies','Evita tener que observar organismos','Convierte especies distintas en una sola'], solution:'La clasificación organiza la información biológica y facilita comparaciones.' },
    { level:2, prompt:'Si desaparece una población local de una especie, ¿qué componente de biodiversidad se reduce directamente?', answer:'La diversidad de organismos presentes en esa comunidad', distractors:['La altitud del ecosistema','La cantidad de luz solar','La longitud del día'], solution:'La pérdida de poblaciones disminuye la diversidad biológica local.' },
    { level:3, prompt:'Dos bosques tienen el mismo número de especies, pero uno contiene poblaciones muy pequeñas y aisladas. ¿Qué preocupación adicional existe?', answer:'Mayor vulnerabilidad a pérdida de diversidad genética y extinciones locales', distractors:['Seguro tiene más agua','La clasificación deja de funcionar','El número de especies aumenta automáticamente'], solution:'Poblaciones pequeñas y aisladas pueden perder variabilidad genética y ser más frágiles.' },
    { level:3, prompt:'¿Qué acción protege mejor la biodiversidad de un humedal?', answer:'Conservar el hábitat y reducir contaminación y alteraciones', distractors:['Drenarlo por completo','Introducir especies exóticas sin control','Eliminar toda la vegetación de ribera'], solution:'La protección del hábitat y la reducción de presiones favorecen la biodiversidad.' },
    { level:4, prompt:'¿Por qué una alta biodiversidad puede aumentar la resiliencia de un ecosistema?', answer:'Porque distintas especies pueden cumplir funciones complementarias ante cambios', distractors:['Porque impide cualquier cambio ambiental','Porque todas las especies reaccionan igual','Porque elimina la competencia por completo'], solution:'La diversidad funcional puede amortiguar perturbaciones, aunque no hace invulnerable al ecosistema.' },
    { level:4, prompt:'¿Qué dato describe mejor biodiversidad que simple abundancia?', answer:'Número de especies y distribución de individuos entre ellas', distractors:['Número total de individuos sin distinguir especies','Temperatura máxima del día','Masa total del suelo'], solution:'La biodiversidad considera variedad y composición, no solo cantidad total de individuos.' },
  ],
  B05S01: [
    { level:1, prompt:'¿Cuál es un factor abiótico de un ecosistema?', answer:'La temperatura', distractors:['Un roble','Un zorro','Una bacteria'], solution:'Los factores abióticos son componentes no vivos del ambiente.' },
    { level:1, prompt:'¿Cuál es un factor biótico?', answer:'Una población de conejos', distractors:['La humedad','La luz solar','El tipo de suelo'], solution:'Los factores bióticos corresponden a organismos vivos y sus interacciones.' },
    { level:2, prompt:'En una charca baja mucho el nivel de agua. ¿Qué tipo de factor ha cambiado primero?', answer:'Un factor abiótico', distractors:['Un factor biótico exclusivamente','Una especie nueva necesariamente','La clasificación taxonómica'], solution:'La cantidad de agua es una condición física no viva.' },
    { level:2, prompt:'La presencia de depredadores influye en una población de presas. ¿Qué tipo de factor representa?', answer:'Biótico', distractors:['Abiótico','Geológico exclusivamente','Climático exclusivamente'], solution:'Un depredador es un ser vivo, por lo que su influencia es biótica.' },
    { level:3, prompt:'Un cactus sobrevive mejor que una planta de sombra en un ambiente seco. ¿Qué explica la diferencia?', answer:'Sus adaptaciones responden de forma distinta a factores abióticos como disponibilidad de agua', distractors:['Los factores abióticos no afectan a seres vivos','Todas las plantas necesitan exactamente la misma humedad','El cactus no realiza funciones vitales'], solution:'Las especies toleran de forma diferente las condiciones físicas del medio.' },
    { level:3, prompt:'Si aumenta la salinidad de una laguna y disminuyen algunas especies, ¿qué relación se observa?', answer:'Un cambio abiótico puede modificar componentes bióticos', distractors:['Los factores bióticos nunca dependen del medio','La salinidad es un organismo vivo','Las especies no responden a cambios ambientales'], solution:'Las condiciones físicas condicionan supervivencia y distribución de organismos.' },
    { level:4, prompt:'¿Por qué es incorrecto estudiar factores bióticos y abióticos como si fueran independientes?', answer:'Porque se influyen mutuamente dentro del ecosistema', distractors:['Porque todos son seres vivos','Porque todos son variables climáticas','Porque solo importan los factores abióticos'], solution:'Los organismos modifican su ambiente y a la vez responden a él.' },
    { level:4, prompt:'Una cubierta vegetal densa reduce temperatura del suelo y pérdida de agua. ¿Qué muestra?', answer:'Un componente biótico puede modificar condiciones abióticas', distractors:['Los factores bióticos solo reciben efectos','La vegetación es un factor abiótico','La temperatura no forma parte del ecosistema'], solution:'Los seres vivos también alteran condiciones físicas del medio.' },
  ],
  B05S02: [
    { level:1, prompt:'En una cadena alimentaria, ¿qué organismo suele ser productor?', answer:'Una planta verde', distractors:['Un zorro','Un hongo descomponedor','Un halcón'], solution:'Los productores elaboran materia orgánica, normalmente mediante fotosíntesis.' },
    { level:1, prompt:'Hierba → conejo → zorro. ¿Qué papel tiene el conejo?', answer:'Consumidor primario', distractors:['Productor','Consumidor secundario','Descomponedor'], solution:'El conejo se alimenta del productor y por ello es consumidor primario.' },
    { level:2, prompt:'¿Qué función cumplen los descomponedores?', answer:'Transforman materia orgánica muerta y reciclan nutrientes', distractors:['Producen luz solar','Eliminan todos los nutrientes del suelo','Ocupan siempre el nivel de depredador superior'], solution:'Hongos y bacterias descomponen restos y devuelven nutrientes al sistema.' },
    { level:2, prompt:'¿Por qué una red trófica representa mejor un ecosistema que una cadena única?', answer:'Porque una especie puede tener varias fuentes de alimento y varios consumidores', distractors:['Porque elimina a los productores','Porque todas las especies comen exactamente lo mismo','Porque solo incluye factores abióticos'], solution:'Las relaciones alimentarias reales forman redes con múltiples conexiones.' },
    { level:3, prompt:'Si disminuye mucho una población de insectos herbívoros, ¿qué podría ocurrir con aves que dependen de ellos?', answer:'Podrían disminuir por falta de alimento', distractors:['Aumentarían necesariamente sin límite','Se convertirían en productores','No podrían verse afectadas'], solution:'Las poblaciones conectadas tróficamente pueden responder a cambios en sus recursos.' },
    { level:3, prompt:'En una red, un ave come semillas e insectos. ¿Qué muestra esto?', answer:'Puede ocupar más de una relación trófica según el alimento', distractors:['Es siempre productor','No forma parte de ninguna red','Solo puede pertenecer a una cadena'], solution:'Las dietas variadas conectan a una especie con distintos niveles y cadenas.' },
    { level:4, prompt:'¿Por qué hay menos energía disponible en niveles tróficos superiores?', answer:'Porque en cada transferencia parte de la energía se usa y se disipa', distractors:['Porque la energía aumenta al subir de nivel','Porque los productores no contienen energía','Porque los consumidores no respiran'], solution:'Solo una fracción de la energía pasa de un nivel trófico al siguiente.' },
    { level:4, prompt:'Si desaparecen los descomponedores de un ecosistema, ¿qué consecuencia sería probable?', answer:'Se acumularían restos y disminuiría el reciclaje de nutrientes', distractors:['Aumentaría indefinidamente la fertilidad sin cambios','Los productores dejarían de necesitar nutrientes','La materia muerta desaparecería más rápido'], solution:'Los descomponedores son esenciales para devolver nutrientes al medio.' },
  ],
  B05S03: [
    { level:1, prompt:'Un lobo caza un ciervo. ¿Qué interacción es?', answer:'Depredación', distractors:['Mutualismo','Competencia','Comensalismo'], solution:'En la depredación un organismo captura y consume a otro.' },
    { level:1, prompt:'Dos plantas cercanas utilizan la misma luz y agua limitadas. ¿Qué interacción puede darse?', answer:'Competencia', distractors:['Depredación','Mutualismo obligado necesariamente','Descomposición'], solution:'Cuando comparten recursos limitados pueden competir por ellos.' },
    { level:2, prompt:'Una abeja obtiene néctar y una flor recibe polinización. ¿Qué relación representa?', answer:'Mutualismo', distractors:['Depredación','Parasitismo','Competencia'], solution:'Ambas especies pueden obtener beneficio de la interacción.' },
    { level:2, prompt:'Una garrapata obtiene alimento de un mamífero al que perjudica. ¿Qué relación es?', answer:'Parasitismo', distractors:['Mutualismo','Competencia','Productividad primaria'], solution:'El parásito se beneficia mientras el hospedador resulta perjudicado.' },
    { level:3, prompt:'Si aumenta mucho un depredador, ¿qué efecto inicial es razonable sobre su presa?', answer:'La población de presas puede disminuir', distractors:['La presa aumentará siempre','La presa se convertirá en productor','No puede existir ningún efecto'], solution:'Una mayor presión de depredación puede reducir la población de presas.' },
    { level:3, prompt:'Tras caer la población de depredadores, aumenta mucho un herbívoro y disminuye la vegetación. ¿Qué describe mejor el proceso?', answer:'Un cambio en una población puede propagarse por la red ecológica', distractors:['Cada población funciona de forma aislada','La vegetación no depende de consumidores','Los depredadores son factores abióticos'], solution:'Las interacciones conectan poblaciones y permiten efectos en cascada.' },
    { level:4, prompt:'¿Por qué una población no suele crecer indefinidamente aunque tenga alta reproducción?', answer:'Porque recursos, competencia, enfermedades y depredación pueden limitarla', distractors:['Porque toda población deja de reproducirse al crecer','Porque los recursos son siempre infinitos','Porque solo la temperatura controla poblaciones'], solution:'Diversos factores dependientes e independientes de la densidad limitan el crecimiento.' },
    { level:4, prompt:'Dos especies compiten por el mismo recurso. ¿Qué cambio podría reducir la competencia?', answer:'Usar recursos distintos o utilizarlos en momentos diferentes', distractors:['Aumentar exactamente la misma demanda','Eliminar toda variación ambiental','Ocupar siempre el mismo espacio y horario'], solution:'La partición de recursos reduce solapamiento entre nichos.' },
  ],
  B05S04: [
    { level:1, prompt:'¿Qué acción causa pérdida directa de hábitat?', answer:'Talar un bosque para urbanizarlo', distractors:['Restaurar una ribera','Crear un corredor ecológico','Reducir vertidos'], solution:'La transformación del bosque elimina o fragmenta el hábitat original.' },
    { level:1, prompt:'¿Qué medida favorece la conservación de un ecosistema?', answer:'Restaurar zonas degradadas con especies autóctonas', distractors:['Introducir especies invasoras','Aumentar residuos sin tratamiento','Eliminar toda vegetación ribereña'], solution:'La restauración con especies propias del lugar ayuda a recuperar funciones ecológicas.' },
    { level:2, prompt:'¿Cómo puede afectar un vertido contaminante a un río?', answer:'Puede perjudicar organismos y alterar la calidad del agua', distractors:['Mejora siempre la biodiversidad','No puede afectar a cadenas alimentarias','Solo cambia el color sin efectos biológicos'], solution:'Los contaminantes pueden ser tóxicos y modificar condiciones ambientales.' },
    { level:2, prompt:'¿Por qué un corredor ecológico puede ser útil?', answer:'Conecta hábitats y facilita desplazamiento e intercambio entre poblaciones', distractors:['Aísla aún más las poblaciones','Sustituye todos los hábitats naturales','Impide el movimiento de animales'], solution:'La conectividad reduce efectos de fragmentación.' },
    { level:3, prompt:'Una especie exótica introducida se expande y desplaza a especies locales. ¿Qué problema representa?', answer:'Una invasión biológica que puede reducir biodiversidad local', distractors:['Una restauración automática del ecosistema','Un factor abiótico sin efecto en otras especies','Una mejora garantizada de todas las redes tróficas'], solution:'Las especies invasoras pueden competir, depredar o transmitir enfermedades a especies nativas.' },
    { level:3, prompt:'¿Qué estrategia combina mejor uso humano y conservación de un bosque?', answer:'Aprovechamiento regulado, protección de zonas sensibles y regeneración', distractors:['Tala total sin regeneración','Prohibir cualquier seguimiento científico','Eliminar especies autóctonas para simplificar el sistema'], solution:'La gestión sostenible busca compatibilizar uso y mantenimiento de funciones ecológicas.' },
    { level:4, prompt:'Un humedal pierde superficie, recibe nutrientes agrícolas y queda aislado de otros humedales. ¿Qué presiones actúan a la vez?', answer:'Pérdida de hábitat, contaminación y fragmentación', distractors:['Solo un cambio de temperatura','Únicamente depredación natural','Solo competencia entre plantas'], solution:'El escenario combina tres presiones humanas diferentes.' },
    { level:4, prompt:'¿Por qué reducir una presión humana no siempre recupera inmediatamente un ecosistema?', answer:'Porque pueden existir daños acumulados y procesos de recuperación lentos', distractors:['Porque los ecosistemas nunca cambian','Porque toda restauración ocurre en un día','Porque las especies no responden al ambiente'], solution:'La recuperación ecológica depende de tiempo, conectividad, poblaciones remanentes y estado del hábitat.' },
  ],
}

const FRAMES = [
  (prompt: string) => prompt,
  (prompt: string) => `Analiza la situación: ${prompt}`,
  (prompt: string) => `Aplica lo que sabes de biología: ${prompt}`,
  (prompt: string) => `Reto de ciencias: ${prompt}`,
] as const

function rotate<T>(items: T[], shift: number) {
  const offset = ((shift % items.length) + items.length) % items.length
  return items.slice(offset).concat(items.slice(0, offset))
}

export function generateScienceLifeLongTermVariant(skill: SkillMeta, difficulty: number, seed: number): GeneratedQuestion | null {
  const cards = BANK[skill.id]
  if (!cards?.length) return null
  const eligible = cards.filter((card) => Math.abs(card.level - difficulty) <= 1)
  const pool = eligible.length ? eligible : cards
  const normalized = seed >>> 0
  const card = pool[normalized % pool.length]
  const frame = FRAMES[Math.floor(normalized / pool.length) % FRAMES.length]
  const options = rotate([card.answer, ...card.distractors], normalized + difficulty)
  return {
    skillId: skill.id,
    label: skill.name,
    difficulty,
    seed,
    prompt: frame(card.prompt),
    options,
    answerIndex: options.indexOf(card.answer),
    solution: card.solution,
    tags: [skill.generator_key, 'biology', 'science_life_long_term'],
  }
}

export function scienceLifeVariantCount(skillId: string) {
  return (BANK[skillId]?.length ?? 0) * FRAMES.length
}

export function scienceLifeVariantSkillIds() {
  return Object.keys(BANK)
}
