type Card = { prompt: string; answer: string; distractors: [string, string, string]; why: string }

const EXTRA: Record<string, Card[]> = {
  B01S01: [
    { prompt:'Quieres saber si el tipo de suelo afecta a la retención de agua. ¿Qué pregunta es investigable?', answer:'¿Cuánta agua retienen masas iguales de distintos suelos tras el mismo drenaje?', distractors:['¿Qué suelo parece más bonito?','¿Cuál es el mejor suelo del mundo?','¿Por qué algunos suelos son buenos?'], why:'Define una variable que cambia y un resultado medible.' },
    { prompt:'¿Cuál es una hipótesis comprobable sobre sonido?', answer:'Si aumenta la distancia a una fuente sonora, disminuirá la intensidad medida', distractors:['Los sonidos lejanos son peores','La música fuerte es molesta','Todo sonido desaparece a diez metros'], why:'Relaciona distancia e intensidad, dos variables medibles.' },
    { prompt:'Un grupo quiere estudiar evaporación. ¿Qué predicción deriva de “más superficie expuesta aumenta la evaporación”?', answer:'La misma cantidad de agua perderá más masa en un recipiente ancho que en uno estrecho', distractors:['El recipiente ancho tendrá siempre menor temperatura','El agua del recipiente estrecho hervirá primero','Toda el agua se evaporará en una hora'], why:'La predicción traduce la hipótesis a un resultado observable.' },
    { prompt:'¿Qué pregunta permite estudiar el efecto del tamaño de partícula en la disolución?', answer:'¿Tarda menos en disolverse la misma masa de azúcar triturada que en terrones?', distractors:['¿Es más dulce el azúcar triturada?','¿Qué forma de azúcar gusta más?','¿Es bonito un terrón de azúcar?'], why:'Compara una condición concreta usando una medida de tiempo.' },
    { prompt:'Para estudiar si el color de una superficie afecta al calentamiento, ¿qué hipótesis está mejor formulada?', answer:'Bajo la misma luz, una superficie negra alcanzará mayor temperatura que una blanca en diez minutos', distractors:['El negro da más calor','Las superficies oscuras son mejores','Una superficie negra siempre estará caliente'], why:'Es específica, medible y contrastable.' },
    { prompt:'Observas moho antes en unas rebanadas que en otras. ¿Qué pregunta inicial evita asumir la causa?', answer:'¿Qué condiciones ambientales difieren entre las rebanadas?', distractors:['¿La humedad causó el moho?','¿El pan viejo siempre tiene más moho?','¿La luz impide todo crecimiento de moho?'], why:'Primero conviene identificar factores comparables antes de atribuir causalidad.' },
    { prompt:'¿Cuál es una hipótesis falsable sobre péndulos?', answer:'A mayor longitud del hilo, mayor será el tiempo de una oscilación completa', distractors:['Los péndulos largos son más interesantes','Todos los péndulos se mueven bien','El péndulo perfecto existe'], why:'Puede ponerse a prueba variando longitud y midiendo tiempo.' },
    { prompt:'Quieres investigar memoria y sueño. ¿Qué pregunta es más científica para una actividad escolar sencilla?', answer:'¿Recuerdan más palabras al día siguiente quienes durmieron al menos ocho horas en esta muestra?', distractors:['¿Dormir es bueno?','¿Quién tiene mejor memoria?','¿Por qué dormir mucho hace inteligente?'], why:'Define población, medida y comparación sin dar por hecha la causa.' },
    { prompt:'¿Qué mejora convierte “las plantas crecen mejor con música” en una hipótesis útil?', answer:'Plantas iguales expuestas a música una hora diaria mostrarán una altura media distinta a plantas sin música tras tres semanas', distractors:['Las plantas aman la música','La música clásica es mejor para todo','Las plantas con música serán bonitas'], why:'Introduce grupos comparables, duración y una medida.' },
    { prompt:'Una observación muestra más insectos cerca de una lámpara. ¿Qué predicción podrías probar?', answer:'Con dos trampas iguales, la iluminada atraerá más insectos que la no iluminada durante el mismo tiempo', distractors:['Todos los insectos prefieren la luz','La lámpara crea insectos','Los insectos nunca aparecen de día'], why:'La predicción establece una comparación medible.' },
    { prompt:'¿Qué pregunta sobre corrosión puede responderse experimentalmente?', answer:'¿Cambia la masa perdida por clavos iguales al variar la salinidad del agua durante una semana?', distractors:['¿El óxido es feo?','¿Por qué el hierro envejece?','¿Cuál es el metal más útil?'], why:'Especifica material, variable, tiempo y resultado medible.' },
    { prompt:'Para estudiar cómo influye la pendiente en el movimiento, ¿qué hipótesis es adecuada?', answer:'Al aumentar el ángulo de una rampa, un carrito recorrerá una distancia fija en menos tiempo', distractors:['Las rampas inclinadas son rápidas','Un carrito siempre baja igual','La gravedad hace todo más veloz'], why:'Relaciona una variable controlable con una medida concreta.' },
    { prompt:'¿Cuál de estas preguntas puede generar datos cuantitativos?', answer:'¿Cuántos centímetros crece una raíz en cinco días con cada concentración de sal?', distractors:['¿Qué raíz parece más sana?','¿Qué planta te gusta más?','¿Es mala la sal para las plantas?'], why:'Pide una medida numérica bajo condiciones comparables.' },
    { prompt:'Una hipótesis no coincide con los datos obtenidos. ¿Qué debe hacer el grupo?', answer:'Revisar la hipótesis y el método a la luz de la evidencia', distractors:['Cambiar los datos para que coincidan','Ignorar el ensayo','Mantener la hipótesis porque era la idea inicial'], why:'Las hipótesis se evalúan con evidencia y pueden revisarse.' },
    { prompt:'¿Qué formulación distingue mejor observación de hipótesis?', answer:'“La muestra A está más caliente” es observación; “se calentó más por su color” es hipótesis', distractors:['Ambas son observaciones','Ambas son hipótesis','La primera es opinión y la segunda un hecho'], why:'La observación describe; la hipótesis propone una explicación comprobable.' },
    { prompt:'¿Qué hace más fuerte una predicción científica?', answer:'Que indique qué resultado esperar bajo condiciones definidas', distractors:['Que use palabras muy técnicas','Que sea imposible de contradecir','Que coincida con la opinión del grupo'], why:'Una buena predicción permite contrastar claramente la hipótesis.' },
  ],
  B01S02: [
    { prompt:'Estudias cómo afecta la temperatura a la disolución. ¿Qué debe mantenerse constante?', answer:'La masa de soluto, el volumen de agua y la agitación', distractors:['La temperatura','El tiempo de disolución','La variable que se quiere medir'], why:'Solo debe cambiar deliberadamente la temperatura.' },
    { prompt:'En una prueba de filtros de agua, ¿cuál es la variable dependiente?', answer:'La turbidez del agua después del filtrado', distractors:['El tipo de filtro','El volumen inicial de agua','El recipiente usado'], why:'Es el resultado que se mide tras aplicar el tratamiento.' },
    { prompt:'Dos rampas tienen distinto ángulo y distinto material. ¿Por qué el diseño es débil?', answer:'Cambian dos factores a la vez', distractors:['Porque hacen falta tres rampas','Porque el carrito debería ser distinto','Porque no puede medirse el tiempo'], why:'No permite separar el efecto del ángulo del efecto del material.' },
    { prompt:'Para comparar detergentes, ¿qué control mejora la prueba?', answer:'Usar manchas iguales, misma cantidad de agua y misma temperatura', distractors:['Usar prendas distintas','Cambiar detergente y temperatura juntos','Lavar cada muestra durante un tiempo diferente'], why:'Mantener constantes las demás condiciones permite una comparación justa.' },
    { prompt:'Quieres probar el efecto de la cafeína sobre el pulso en un modelo simulado. ¿Qué es la variable independiente?', answer:'La dosis de cafeína simulada', distractors:['El pulso resultante','La media de pulsaciones','El error de medida'], why:'Es la condición que se modifica deliberadamente.' },
    { prompt:'¿Para qué sirve repetir cada condición varias veces?', answer:'Para estimar la variabilidad y reducir el peso de resultados accidentales', distractors:['Para garantizar que todos los datos sean iguales','Para evitar calcular medias','Para eliminar la necesidad de un control'], why:'Las réplicas muestran cuánto varían los resultados.' },
    { prompt:'En un experimento con semillas, un grupo recibe 20 semillas y otro 5. ¿Qué problema introduce?', answer:'Los grupos no son comparables en tamaño de muestra', distractors:['La germinación deja de ser medible','La temperatura ya no importa','Las semillas se convierten en una variable dependiente'], why:'Diferencias de tamaño pueden distorsionar la comparación.' },
    { prompt:'¿Qué grupo de control usarías para estudiar un fertilizante?', answer:'Plantas iguales tratadas igual salvo que no reciben fertilizante', distractors:['Plantas de otra especie','Plantas con el doble de fertilizante','Plantas con menos agua y sin fertilizante'], why:'El control debe diferir únicamente en el tratamiento estudiado.' },
    { prompt:'Si estudias el efecto de horas de luz, ¿cuál es una variable de control razonable?', answer:'La cantidad de agua diaria', distractors:['Las horas de luz','La altura final','El crecimiento medido'], why:'El agua debe mantenerse igual para aislar el efecto de la luz.' },
    { prompt:'¿Qué diseño permite estudiar mejor si el área de una vela afecta al tiempo de fusión de cera?', answer:'Cambiar solo el área expuesta manteniendo masa, material y temperatura ambiente', distractors:['Cambiar área y tipo de cera','Usar masas diferentes','Colocar cada muestra en una habitación distinta'], why:'Una prueba justa modifica un solo factor principal.' },
    { prompt:'Al medir el pulso antes y después de ejercicio, ¿qué comparación es más útil?', answer:'La diferencia de pulso para la misma persona o grupos equivalentes', distractors:['Comparar personas de edades muy distintas sin control','Cambiar también la duración del ejercicio','Medir solo a quienes esperan un aumento'], why:'Reduce diferencias ajenas al factor estudiado.' },
    { prompt:'¿Qué variable dependiente sería adecuada al estudiar aislamiento térmico?', answer:'El descenso de temperatura del agua en un tiempo fijo', distractors:['El material aislante','El grosor que se decide usar','El vaso elegido como control'], why:'El descenso de temperatura es el efecto medido.' },
    { prompt:'Un grupo mide crecimiento con reglas diferentes. ¿Qué mejora metodológica conviene?', answer:'Usar el mismo tipo de instrumento y el mismo procedimiento de medida', distractors:['Cambiar también las plantas','Redondear todos los datos al mismo número','Elegir solo las medidas más parecidas'], why:'Estandarizar la medición reduce sesgos instrumentales.' },
    { prompt:'¿Qué significa aleatorizar la asignación de muestras a grupos?', answer:'Repartirlas sin elegir sistemáticamente cuáles reciben cada tratamiento', distractors:['Cambiar las variables al azar durante el experimento','Medir en cualquier unidad','Eliminar el grupo de control'], why:'Ayuda a evitar que diferencias iniciales sesguen los grupos.' },
    { prompt:'Quieres comparar dos métodos de estudio. ¿Qué condición debería ser equivalente?', answer:'El tiempo total dedicado por ambos grupos', distractors:['El método usado','La puntuación final','La variable que se compara'], why:'El tiempo debe controlarse si se quiere atribuir diferencias al método.' },
    { prompt:'¿Qué diseño reduce mejor el efecto de la posición de macetas junto a una ventana?', answer:'Rotar o distribuir aleatoriamente las posiciones entre grupos', distractors:['Poner todo el grupo tratado más cerca','No registrar la posición','Usar especies diferentes en cada lado'], why:'La posición puede actuar como variable de confusión.' },
  ],
  B01S03: [
    { prompt:'Un grupo obtiene 4, 5, 5, 6 y 5 cm de crecimiento. ¿Qué valor resume bien el centro de estos datos?', answer:'Una media cercana a 5 cm', distractors:['20 cm','0 cm','El valor más grande multiplicado por cinco'], why:'La media resume el valor central cuando no hay valores extremos importantes.' },
    { prompt:'Dos ensayos producen medias parecidas, pero uno tiene resultados mucho más dispersos. ¿Qué indica?', answer:'El segundo ensayo es menos consistente', distractors:['El segundo es necesariamente más correcto','Las medias dejan de poder compararse','La dispersión demuestra causalidad'], why:'Mayor dispersión significa menor consistencia entre repeticiones.' },
    { prompt:'Un gráfico muestra una tendencia, pero solo hay tres puntos. ¿Qué conclusión es prudente?', answer:'La tendencia es provisional y conviene obtener más datos', distractors:['La relación queda demostrada para siempre','Tres puntos bastan para cualquier ley','Debe eliminarse el punto intermedio'], why:'Pocos datos limitan la fuerza de la inferencia.' },
    { prompt:'¿Qué gráfico es adecuado para comparar la media de crecimiento de cuatro tratamientos?', answer:'Un gráfico de barras', distractors:['Un diagrama de sectores del tiempo','Un mapa político','Una línea temporal sin valores'], why:'Las barras permiten comparar categorías discretas.' },
    { prompt:'Una correlación entre horas de sueño y nota no demuestra por sí sola que…', answer:'Dormir más cause directamente una nota mayor', distractors:['Exista una asociación en la muestra','Puedan calcularse medias','Los datos deban representarse'], why:'Correlación no implica causalidad.' },
    { prompt:'Al repetir una medida con el mismo instrumento aparecen 10,1; 10,0; 10,1 y 10,0. ¿Qué sugieren?', answer:'Buena repetibilidad', distractors:['Gran variabilidad','Un error seguro de diez unidades','Que el instrumento mide otra variable'], why:'Valores muy próximos entre repeticiones indican consistencia.' },
    { prompt:'Un resultado contradice los demás. ¿Qué práctica es correcta?', answer:'Comprobar procedimiento e instrumento y conservar registro de lo ocurrido', distractors:['Borrarlo sin explicación','Sustituirlo por la media','Cambiarlo para que siga la tendencia'], why:'Los valores atípicos deben investigarse y documentarse.' },
    { prompt:'¿Qué significa que una conclusión esté “apoyada por los datos”?', answer:'Que es compatible con las medidas obtenidas dentro de las condiciones estudiadas', distractors:['Que ya no puede cambiar','Que demuestra una verdad universal','Que coincide con la hipótesis inicial'], why:'La evidencia respalda conclusiones con un alcance limitado.' },
    { prompt:'Un tratamiento obtiene 70 % de éxito y otro 72 % con muestras pequeñas. ¿Qué conviene afirmar?', answer:'La diferencia es pequeña y hace falta más evidencia antes de atribuir un efecto', distractors:['El segundo es definitivamente mejor','La diferencia del 2 % prueba causalidad','No se pueden calcular porcentajes'], why:'Tamaño de muestra y diferencia pequeña aconsejan cautela.' },
    { prompt:'¿Por qué conviene mostrar unidades en tablas y gráficos?', answer:'Porque dan significado cuantitativo a los valores', distractors:['Porque hacen que el gráfico sea más colorido','Porque sustituyen el título','Porque eliminan errores experimentales'], why:'Un número sin unidad puede ser ambiguo.' },
    { prompt:'Si los datos aumentan aproximadamente de forma constante con el tiempo, ¿qué representación ayuda a verlo?', answer:'Una gráfica de líneas ordenada temporalmente', distractors:['Una lista desordenada','Un diagrama de sectores','Un dibujo sin escala'], why:'Conserva el orden temporal y hace visible la tendencia.' },
    { prompt:'¿Qué aporta calcular el rango máximo-mínimo?', answer:'Una medida sencilla de dispersión', distractors:['La causa del fenómeno','La variable independiente','El número de controles'], why:'El rango indica cuánto se extienden los valores.' },
    { prompt:'Un grupo repite una prueba y obtiene siempre el mismo sesgo por un sensor mal calibrado. ¿Qué ocurre?', answer:'Los resultados pueden ser consistentes pero inexactos', distractors:['La repetición elimina el sesgo','El sensor pasa a ser exacto','La media siempre corrige la calibración'], why:'La precisión o repetibilidad no garantiza exactitud.' },
    { prompt:'¿Qué conclusión es válida si 18 de 20 semillas germinan en A y 10 de 20 en B?', answer:'En este ensayo la proporción de germinación fue mayor en A', distractors:['A siempre germinará mejor en cualquier condición','B nunca puede alcanzar a A','La causa queda demostrada sin conocer el diseño'], why:'Describe directamente lo observado sin generalizar de más.' },
    { prompt:'¿Qué ventaja tiene presentar también datos individuales además de la media?', answer:'Permite ver la variabilidad y posibles valores atípicos', distractors:['Hace innecesario repetir','Convierte correlación en causalidad','Elimina errores de medición'], why:'La media puede ocultar dispersión o anomalías.' },
    { prompt:'Un resultado se obtiene una sola vez. ¿Qué aumenta la confianza en él?', answer:'Que otros grupos puedan repetir el procedimiento y obtener un patrón parecido', distractors:['Que el autor esté muy seguro','Que el resultado sea llamativo','Que no se publiquen los datos'], why:'La reproducibilidad fortalece la evidencia.' },
  ],
  B01S04: [
    { prompt:'Una publicación viral cita “un estudio” sin autor ni enlace. ¿Qué conviene hacer?', answer:'Buscar la fuente original antes de aceptar la afirmación', distractors:['Compartirla si tiene muchos comentarios','Aceptar el resumen del titular','Confiar si usa gráficos'], why:'La trazabilidad permite evaluar método y evidencia.' },
    { prompt:'¿Qué fuente es más apropiada para conocer un riesgo sanitario actual?', answer:'Una institución sanitaria que explica evidencia y fecha de actualización', distractors:['Un vídeo sin referencias','Un comentario anónimo','Un anuncio comercial'], why:'Autoridad competente, evidencia y actualidad son señales relevantes.' },
    { prompt:'Un gráfico empieza el eje vertical muy lejos de cero y exagera una diferencia pequeña. ¿Qué debes revisar?', answer:'La escala y el rango de los ejes', distractors:['Solo el color de las barras','El número de palabras del título','La tipografía'], why:'La escala puede cambiar la impresión visual de una diferencia.' },
    { prompt:'¿Qué pregunta ayuda a detectar un conflicto de interés?', answer:'¿Quién financió el estudio y qué relación tiene con el producto evaluado?', distractors:['¿Es largo el artículo?','¿Tiene fotografías?','¿Está escrito en inglés?'], why:'La financiación puede ser relevante al valorar posibles sesgos.' },
    { prompt:'Una noticia afirma “X duplica el riesgo”, de 1 caso entre 10.000 a 2 entre 10.000. ¿Qué dato falta para interpretar bien?', answer:'El riesgo absoluto además del relativo', distractors:['El color del gráfico','La edad del periodista','El tamaño de letra'], why:'El riesgo relativo puede parecer grande aunque el cambio absoluto sea pequeño.' },
    { prompt:'¿Por qué una muestra de 12 personas limita una afirmación sobre millones?', answer:'Porque puede no representar bien a la población', distractors:['Porque toda muestra pequeña es falsa','Porque no pueden calcularse porcentajes','Porque solo sirven muestras de exactamente mil'], why:'El tamaño y representatividad condicionan la generalización.' },
    { prompt:'Dos estudios llegan a resultados distintos. ¿Qué respuesta es científica?', answer:'Comparar métodos, muestras, incertidumbre y calidad antes de decidir qué peso dar a cada uno', distractors:['Elegir el que confirma tu opinión','Descartar ambos automáticamente','Aceptar el más reciente sin leerlo'], why:'Resultados diferentes pueden explicarse por diseño, azar o contexto.' },
    { prompt:'¿Qué significa que un artículo haya sido revisado por pares?', answer:'Que otros especialistas evaluaron el trabajo antes de publicarse', distractors:['Que el resultado sea necesariamente verdadero','Que todos los científicos estén de acuerdo','Que no pueda contener errores'], why:'La revisión aporta control de calidad, no garantía absoluta.' },
    { prompt:'Una web vende un suplemento y solo enlaza testimonios. ¿Qué evidencia sería más sólida?', answer:'Ensayos bien diseñados publicados con métodos y datos', distractors:['Más testimonios positivos','Una celebridad que lo use','Un eslogan científico'], why:'Los testimonios no controlan placebo, sesgos ni otras variables.' },
    { prompt:'¿Qué diferencia hay entre “no se encontró efecto” y “se demostró que no hay efecto”?', answer:'La primera puede reflejar evidencia insuficiente; no son afirmaciones equivalentes', distractors:['Son exactamente lo mismo','La segunda siempre es correcta','La primera significa que el estudio no midió nada'], why:'Ausencia de evidencia no equivale automáticamente a evidencia de ausencia.' },
    { prompt:'¿Qué señal aumenta la confianza en una gráfica científica?', answer:'Ejes etiquetados, unidades, fuente de datos y escala clara', distractors:['Muchos colores','Un título espectacular','Ausencia de valores numéricos'], why:'Permite interpretar y comprobar lo representado.' },
    { prompt:'Un artículo solo informa de resultados favorables y omite medidas previstas. ¿Qué problema puede existir?', answer:'Sesgo de selección o de publicación de resultados', distractors:['Exceso de replicación','Demasiados grupos de control','Una escala demasiado grande'], why:'Seleccionar solo resultados favorables puede distorsionar la evidencia.' },
    { prompt:'¿Qué conviene comprobar al leer una afirmación sobre causalidad?', answer:'Si el diseño permite separar causalidad de simple asociación', distractors:['Si el titular usa la palabra “causa”','Si el autor tiene muchos seguidores','Si el resultado es sorprendente'], why:'La causalidad requiere un diseño y control adecuados.' },
    { prompt:'Una fuente de 2005 contradice una guía de 2026 basada en revisiones recientes. ¿Qué haces?', answer:'Comparar la evidencia y considerar que el conocimiento puede haberse actualizado', distractors:['Descartar siempre todo lo antiguo','Aceptar siempre lo nuevo sin revisarlo','Promediar ambas afirmaciones'], why:'La fecha importa porque nuevas evidencias pueden cambiar recomendaciones.' },
    { prompt:'¿Por qué conviene distinguir una revisión sistemática de una opinión?', answer:'La revisión usa un método explícito para buscar y valorar múltiples estudios', distractors:['Porque toda revisión es infalible','Porque una opinión nunca puede citar datos','Porque solo las revisiones usan estadísticas'], why:'El método transparente reduce selección arbitraria de evidencia.' },
    { prompt:'¿Qué práctica permite verificar mejor una afirmación científica?', answer:'Acceder a métodos, datos o referencias suficientes para rastrear cómo se obtuvo', distractors:['Confiar en el número de compartidos','Elegir la fuente con mejor diseño visual','Aceptar una frase atribuida a “expertos”'], why:'La verificabilidad depende de poder rastrear la evidencia.' },
  ],
}

export function getScienceInvestigationCourseDepth(skillId: string): Card[] {
  return EXTRA[skillId] ?? []
}

export function scienceInvestigationCourseDepthCounts() {
  return Object.fromEntries(Object.entries(EXTRA).map(([skillId, cards]) => [skillId, cards.length]))
}
