import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta = { id: string; name: string; generator_key: string }
type Card = { prompt: string; answer: string; distractors: [string, string, string]; why: string }

const BANK: Record<string, Card[]> = {
  B01S01: [
    { prompt: '¿Cuál es una hipótesis científica comprobable?', answer: 'Si una planta recibe menos luz, crecerá menos en dos semanas', distractors: ['Si una planta recibe menos luz, sus hojas cambiarán de color en dos semanas', 'Si una planta recibe menos agua, crecerá menos en dos semanas', 'Si una planta recibe más luz, crecerá exactamente el doble en dos semanas'], why: 'Una hipótesis científica debe poder contrastarse mediante observaciones o experimentos.' },
    { prompt: 'Quieres estudiar si la temperatura influye en la germinación. ¿Qué hipótesis es comprobable?', answer: 'Si aumenta la temperatura dentro de un rango seguro, cambiará el número de semillas que germinan', distractors: ['Si aumenta la cantidad de agua, cambiará el número de semillas que germinan', 'Si aumenta la temperatura, todas las semillas germinarán al mismo tiempo', 'Si baja la temperatura, las semillas crecerán más altas después de germinar'], why: 'La hipótesis relaciona variables que pueden medirse.' },
    { prompt: '¿Qué pregunta puede investigarse con datos medibles en clase?', answer: '¿Cambia el tiempo de disolución del azúcar al variar la temperatura del agua?', distractors: ['¿Cambia la cantidad de azúcar disuelta al usar vasos de distinto tamaño?', '¿Cambia la temperatura del agua al añadir la misma cantidad de azúcar?', '¿Cambia el tiempo de disolución al variar la cantidad de azúcar pero mantener la temperatura?'], why: 'Tiempo y temperatura pueden medirse y compararse.' },
    { prompt: 'Un grupo observa que unas hojas están amarillas. ¿Cuál es la mejor pregunta científica inicial?', answer: '¿Qué factor ambiental cambia entre las plantas con hojas verdes y amarillas?', distractors: ['¿Las plantas con hojas amarillas tienen menos clorofila que las verdes?', '¿Las hojas amarillas pertenecen a plantas de mayor edad?', '¿Las plantas con hojas amarillas reciben menos agua que las verdes?'], why: 'Una buena pregunta científica busca factores observables y contrastables antes de asumir una causa concreta.' },
    { prompt: '¿Cuál de estas afirmaciones funciona como predicción derivada de una hipótesis?', answer: 'Si la luz favorece el crecimiento, las plantas con más horas de luz crecerán más en el mismo periodo', distractors: ['Si la luz favorece el crecimiento, las plantas con menos agua crecerán más en el mismo periodo', 'Si la luz favorece el crecimiento, todas las plantas alcanzarán la misma altura', 'Si la luz favorece el crecimiento, las plantas con más horas de luz crecerán más aunque cambie también la temperatura'], why: 'Una predicción concreta indica qué resultado esperar si la hipótesis es correcta.' },
    { prompt: 'Para investigar si el ejercicio cambia la frecuencia cardiaca, ¿qué pregunta está mejor formulada?', answer: '¿Cómo cambia la frecuencia cardiaca tras 3 minutos de ejercicio moderado?', distractors: ['¿Cómo cambia la frecuencia respiratoria tras 3 minutos de ejercicio moderado?', '¿Cómo cambia la frecuencia cardiaca tras 10 minutos de reposo?', '¿Cómo cambia la frecuencia cardiaca tras ejercicios de distinta intensidad y duración a la vez?'], why: 'La pregunta define una variable medible y una condición concreta.' },
    { prompt: '¿Qué característica hace útil una hipótesis científica?', answer: 'Que pueda ponerse a prueba y resultar apoyada o refutada por datos', distractors: ['Que coincida con lo que espera el investigador antes de medir', 'Que explique todos los casos posibles sin necesidad de excepciones', 'Que pueda modificarse después de ver los resultados para que encaje mejor'], why: 'Una hipótesis científica debe ser falsable y contrastable.' },
    { prompt: 'Un alumno dice: “El fertilizante hace crecer más las plantas”. ¿Cómo mejorarías esa hipótesis?', answer: 'Si plantas iguales reciben fertilizante, su crecimiento medio en 14 días será mayor que el de plantas sin fertilizante', distractors: ['Si plantas iguales reciben fertilizante, crecerán más, aunque cada grupo reciba distinta cantidad de agua', 'Si plantas iguales reciben fertilizante, todas alcanzarán la misma altura después de 14 días', 'Si plantas iguales reciben fertilizante, su crecimiento será mayor que antes de empezar, sin compararlas con un grupo sin fertilizante'], why: 'La versión mejorada define comparación, medida y periodo.' },
  ],
  B01S02: [
    { prompt: 'Al probar cómo afecta la luz al crecimiento, ¿qué variable debemos cambiar deliberadamente?', answer: 'La cantidad de luz', distractors: ['La altura final de la planta', 'La cantidad de agua recibida', 'El número de hojas que se cuentan al final'], why: 'La variable independiente es la que se modifica para estudiar su efecto.' },
    { prompt: 'En un experimento sobre fertilizante y crecimiento, ¿qué debería mantenerse igual entre grupos?', answer: 'La especie de planta, el agua y el tiempo de crecimiento', distractors: ['La cantidad de fertilizante y la altura inicial', 'La altura final y el número de hojas', 'La cantidad de fertilizante y el tiempo de crecimiento'], why: 'Controlar las demás condiciones permite atribuir diferencias al factor estudiado.' },
    { prompt: 'Se compara la germinación a 15 °C y 25 °C. ¿Cuál es la variable dependiente?', answer: 'El número o porcentaje de semillas que germinan', distractors: ['La temperatura a la que se mantienen las semillas', 'El número de semillas colocadas en cada grupo', 'El tiempo durante el que se observan los grupos'], why: 'La variable dependiente es el resultado que se mide.' },
    { prompt: '¿Qué diseño constituye una prueba más justa del efecto del agua en una planta?', answer: 'Usar plantas similares y variar solo la cantidad de agua', distractors: ['Usar plantas similares y variar agua y luz a la vez', 'Usar especies distintas y darles la misma cantidad de agua', 'Usar plantas similares y variar la cantidad de agua y el tipo de suelo'], why: 'Una prueba justa modifica una variable principal y controla las demás.' },
    { prompt: 'Para estudiar el efecto del ejercicio sobre el pulso, ¿cuál es la variable independiente?', answer: 'La cantidad o intensidad de ejercicio realizado', distractors: ['La frecuencia cardiaca medida después del ejercicio', 'El tiempo que tarda el pulso en volver al valor inicial', 'El valor medio del pulso calculado al final'], why: 'La variable independiente es la condición que el investigador modifica.' },
    { prompt: 'Dos grupos prueban detergentes distintos, pero uno usa agua caliente y otro fría. ¿Cuál es el problema?', answer: 'Hay más de una variable cambiando y no se puede atribuir el resultado solo al detergente', distractors: ['La temperatura del agua no importa si ambos grupos usan la misma cantidad de detergente', 'La comparación sigue siendo válida porque cada grupo solo usa un detergente', 'El único problema es que habría que repetir el ensayo una vez más'], why: 'Cambiar varias condiciones a la vez introduce variables de confusión.' },
    { prompt: '¿Para qué sirve un grupo de control en un experimento?', answer: 'Para disponer de una referencia con la que comparar el efecto del tratamiento', distractors: ['Para recibir una dosis menor del mismo tratamiento y comparar intensidades', 'Para asegurar que todos los grupos produzcan resultados parecidos', 'Para sustituir las repeticiones cuando el experimento tiene pocos individuos'], why: 'El control ayuda a interpretar qué cambio se debe al tratamiento.' },
    { prompt: 'Quieres saber si la sal cambia el punto de congelación del agua. ¿Qué condición debería ser igual en todos los recipientes?', answer: 'El volumen de agua y el recipiente, salvo la cantidad de sal', distractors: ['La cantidad de sal y el volumen de agua', 'La temperatura final alcanzada y la cantidad de sal', 'El tiempo de congelación y el tipo de recipiente'], why: 'Mantener constantes las condiciones evita confundir el efecto de la sal.' },
  ],
  B01S03: [
    { prompt: 'Tres plantas con abono crecen 12, 11 y 13 cm; tres sin abono, 5, 6 y 5 cm. ¿Qué apoyan estos datos?', answer: 'En estas condiciones, el grupo con abono creció más', distractors: ['El abono hará crecer más cualquier especie en cualquier condición', 'El abono aumentó el crecimiento medio aproximadamente el doble en este ensayo', 'Una de las plantas sin abono pudo crecer tanto como una abonada aunque no aparezca en estos datos'], why: 'La conclusión debe limitarse a lo que muestran los datos observados.' },
    { prompt: 'En cinco ensayos, una reacción tarda 20, 21, 19, 20 y 60 s. ¿Qué conviene hacer antes de concluir?', answer: 'Revisar el valor de 60 s y comprobar si hubo un error o condición distinta', distractors: ['Calcular la media con los cinco valores y aceptar el resultado sin revisar nada', 'Eliminar 60 s porque se aleja del resto y volver a calcular', 'Repetir solo el ensayo de 19 s porque es el más rápido'], why: 'Un dato atípico debe investigarse, no ignorarse automáticamente.' },
    { prompt: 'Un gráfico muestra que al aumentar la temperatura de 10 a 30 °C aumenta la velocidad de una reacción. ¿Qué conclusión es válida?', answer: 'Dentro del rango estudiado, la reacción fue más rápida a temperaturas mayores', distractors: ['La reacción será cada vez más rápida también por encima de 30 °C', 'La temperatura es la única variable capaz de cambiar la velocidad de esa reacción', 'Entre 10 y 30 °C todas las reacciones químicas aumentan su velocidad de la misma manera'], why: 'La evidencia permite concluir solo dentro de las condiciones estudiadas.' },
    { prompt: 'Dos grupos obtienen medias de 8,2 cm y 8,4 cm, pero las medidas varían mucho entre plantas. ¿Qué interpretación es más prudente?', answer: 'La diferencia entre medias es pequeña y hace falta más evidencia para asegurar un efecto', distractors: ['El segundo grupo creció más y eso basta para confirmar el efecto', 'La gran variabilidad demuestra que los tratamientos producen efectos opuestos', 'Como las medias son distintas, la diferencia debe deberse al tratamiento'], why: 'La variabilidad y el tamaño de la diferencia condicionan la fuerza de la conclusión.' },
    { prompt: 'Si repites un experimento tres veces y obtienes resultados parecidos, ¿qué aumenta?', answer: 'La confianza en que el patrón observado es reproducible', distractors: ['La probabilidad de que la hipótesis sea verdadera en cualquier situación', 'La seguridad de que no existe ninguna variable de confusión', 'La validez del resultado aunque las tres repeticiones tengan el mismo sesgo'], why: 'La repetición consistente mejora la fiabilidad de la evidencia.' },
    { prompt: 'Una tabla contiene medidas de temperatura cada minuto. ¿Qué representación ayuda mejor a ver una tendencia temporal?', answer: 'Un gráfico de líneas con tiempo en el eje horizontal', distractors: ['Un gráfico de barras con los minutos como categorías independientes', 'Un diagrama de sectores con el porcentaje de cada temperatura', 'Una tabla ordenada de mayor a menor temperatura, sin conservar el orden temporal'], why: 'Un gráfico de líneas permite visualizar cambios continuos en el tiempo.' },
    { prompt: 'Un experimento apoya una hipótesis en una muestra de 4 plantas. ¿Qué afirmación es científicamente adecuada?', answer: 'Los resultados apoyan la hipótesis en esas condiciones, pero conviene repetir con más muestras', distractors: ['Los resultados permiten generalizar a la especie completa si las cuatro plantas coincidieron', 'La hipótesis queda confirmada mientras ninguna de las cuatro plantas contradiga el patrón', 'La muestra es suficiente si las plantas se midieron con mucha precisión'], why: 'La evidencia limitada debe interpretarse con cautela y replicarse.' },
    { prompt: 'En una investigación, 9 de 10 mediciones siguen un patrón y una no. ¿Qué es lo correcto?', answer: 'Comprobar la medición discordante y documentar si existe una explicación', distractors: ['Eliminarla si hace que la tendencia sea menos clara', 'Sustituirla por una nueva medición sin registrar el cambio', 'Mantenerla sin revisarla porque todos los datos deben aceptarse tal como aparecen'], why: 'La ciencia exige tratar los datos discrepantes de forma transparente.' },
  ],
  B01S04: [
    { prompt: '¿Qué fuente ofrece mejor respaldo para una afirmación científica?', answer: 'Un estudio revisado con método y datos descritos', distractors: ['Un informe técnico de una empresa que resume resultados pero no publica los datos', 'Una noticia que cita a un experto pero no enlaza el estudio original', 'Una revisión divulgativa que menciona varios estudios sin explicar cómo se seleccionaron'], why: 'La evidencia científica debe ser trazable y evaluable.' },
    { prompt: 'Dos páginas web hacen afirmaciones opuestas sobre nutrición. ¿Qué criterio ayuda más a decidir cuál es fiable?', answer: 'Comprobar autores, fuentes citadas, fecha y calidad de la evidencia', distractors: ['Comprobar si ambas páginas coinciden con recomendaciones populares y recientes', 'Elegir la que cite más estudios aunque no se revise su calidad ni actualidad', 'Dar más peso a la página escrita por un profesional aunque no muestre las fuentes usadas'], why: 'La fiabilidad depende de trazabilidad, evidencia y contexto, no de una sola señal superficial.' },
    { prompt: '¿Qué señal hace sospechar de una noticia científica?', answer: 'Promete un resultado absoluto pero no enlaza estudio, datos ni autores', distractors: ['Resume un estudio reciente y enlaza el artículo original, pero usa un titular llamativo', 'Presenta una correlación y advierte que no demuestra causalidad', 'Explica limitaciones del estudio y señala que hacen falta más investigaciones'], why: 'Las afirmaciones extraordinarias sin evidencia verificable requieren cautela.' },
    { prompt: 'Un vídeo afirma que un producto “cura cualquier enfermedad”. ¿Cuál es la mejor respuesta?', answer: 'Buscar evidencia clínica fiable y fuentes sanitarias antes de aceptar la afirmación', distractors: ['Buscar varios testimonios independientes para comprobar si la experiencia se repite', 'Comprobar si quien lo recomienda tiene formación sanitaria y aceptar su conclusión', 'Buscar estudios favorables al producto y valorar solo si coinciden entre sí'], why: 'Popularidad, autoridad aparente y testimonios no sustituyen evidencia clínica de calidad.' },
    { prompt: '¿Por qué es importante conocer la fecha de una fuente científica?', answer: 'Porque el conocimiento y las recomendaciones pueden actualizarse con nueva evidencia', distractors: ['Porque una fuente reciente tiene prioridad aunque use evidencia de peor calidad', 'Porque una fuente antigua deja de ser útil en cuanto aparece otra más nueva', 'Porque la fecha permite saber si los resultados pueden generalizarse a otras poblaciones'], why: 'La actualidad es un criterio relevante, aunque no suficiente por sí solo.' },
    { prompt: '¿Qué diferencia principal hay entre un artículo científico y una opinión personal?', answer: 'El artículo científico presenta métodos, datos y referencias que pueden evaluarse', distractors: ['El artículo científico suele estar escrito por especialistas y por eso sus conclusiones no necesitan revisarse', 'La opinión personal puede ser fiable si coincide con muchos testimonios similares', 'El artículo científico es más fiable principalmente porque utiliza vocabulario técnico'], why: 'La ciencia comunica procedimientos y evidencias revisables.' },
    { prompt: 'Una gráfica viral no indica de dónde salen sus datos. ¿Qué deberías hacer?', answer: 'Buscar la fuente original y comprobar cómo se recogieron los datos', distractors: ['Compararla con otras gráficas parecidas y aceptarla si muestran la misma tendencia', 'Revisar si los ejes y porcentajes parecen coherentes y usarla si no detectas errores', 'Confiar en ella si la comparte una institución conocida aunque no aparezca la fuente original'], why: 'Sin procedencia no se puede evaluar la calidad de los datos.' },
    { prompt: 'Una fuente cita correctamente un estudio, pero el estudio se hizo solo con 12 personas. ¿Qué debes valorar?', answer: 'Que el tamaño y características de la muestra limitan cuánto se puede generalizar', distractors: ['Que una muestra pequeña deja de ser un problema si el efecto observado es grande', 'Que los resultados pueden generalizarse si las 12 personas dieron respuestas parecidas', 'Que citar correctamente el estudio compensa la limitación del tamaño de muestra'], why: 'La calidad de una fuente también depende de las limitaciones de la evidencia que cita.' },
  ],
}

function hash(seed: number, value: string) {
  let h = (seed ^ 0x9e3779b9) >>> 0
  for (let i = 0; i < value.length; i += 1) {
    h ^= value.charCodeAt(i)
    h = Math.imul(h, 16777619) >>> 0
  }
  return h >>> 0
}

function rotate<T>(items: T[], shift: number) {
  const n = ((shift % items.length) + items.length) % items.length
  return items.slice(n).concat(items.slice(0, n))
}

export function generateScienceInvestigationQuestion(skill: SkillMeta, difficulty: number, seed: number): GeneratedQuestion | null {
  const cards = BANK[skill.id]
  if (!cards?.length) return null
  const card = cards[hash(seed + Math.max(1, difficulty), skill.id) % cards.length]
  const options = [card.answer, ...card.distractors]
  const rotated = rotate(options, seed + difficulty)
  return {
    skillId: skill.id,
    label: skill.name,
    difficulty,
    seed,
    prompt: card.prompt,
    options: rotated,
    answerIndex: rotated.indexOf(card.answer),
    solution: card.why,
    tags: [skill.generator_key, 'biology_geology', 'science_investigation_variety'],
  }
}

export function scienceInvestigationCardCounts() {
  return Object.fromEntries(Object.entries(BANK).map(([skillId, cards]) => [skillId, cards.length]))
}
