import type { GeneratedQuestion } from './firstEvaluationGenerators'

type SkillMeta = { id: string; name: string; generator_key: string }
type Scenario = { text: string; answer: string; distractors: [string,string,string]; solution: string }

const MAIN_IDEA: Scenario[] = [
  { text:'En el huerto escolar se recoge agua de lluvia para regar y se fabrica compost con restos vegetales. Así se reduce el consumo de agua y se aprovechan residuos.', answer:'El huerto escolar aplica medidas para aprovechar mejor los recursos', distractors:['El huerto solo sirve para cultivar flores','La lluvia impide trabajar en el huerto','El compost aumenta el desperdicio'], solution:'La idea principal reúne el ahorro de agua y el aprovechamiento de residuos.' },
  { text:'La biblioteca ha creado un rincón de lectura tranquila y otro para trabajos en grupo. Cada espacio responde a una forma distinta de estudiar.', answer:'La biblioteca organiza espacios para diferentes necesidades de estudio', distractors:['La biblioteca solo permite estudiar en grupo','Todos deben trabajar en el mismo lugar','Leer en silencio está prohibido'], solution:'El texto explica que los espacios se adaptan a distintas formas de trabajo.' },
  { text:'Ir al colegio caminando cuando es posible reduce el tráfico cerca de la entrada y añade actividad física a la rutina diaria.', answer:'Caminar al colegio puede beneficiar la movilidad y la salud', distractors:['Caminar siempre tarda menos que cualquier transporte','El tráfico aumenta cuando se camina','La actividad física solo sirve en clase de deporte'], solution:'La idea principal combina menos tráfico y más actividad física.' },
  { text:'Separar papel, vidrio y envases facilita que los materiales puedan tratarse de forma adecuada y volver a utilizarse como materia prima.', answer:'Separar residuos favorece su reciclaje y reutilización', distractors:['Todos los residuos deben mezclarse','Reciclar consiste en guardar basura sin tratarla','El vidrio no puede volver a utilizarse'], solution:'El texto relaciona la separación con el reciclaje posterior.' },
  { text:'Dormir suficientes horas ayuda a mantener la atención durante las clases y favorece la recuperación física después de un día activo.', answer:'Dormir bien beneficia tanto la atención como la recuperación física', distractors:['Dormir solo influye en el deporte','Dormir menos siempre mejora la concentración','La atención no tiene relación con el descanso'], solution:'La frase reúne un beneficio cognitivo y otro físico.' },
  { text:'Los árboles de una ciudad dan sombra en verano, ofrecen refugio a animales y contribuyen a mejorar la calidad del aire.', answer:'El arbolado urbano aporta varios beneficios ambientales', distractors:['Los árboles urbanos solo sirven de decoración','Los animales no utilizan los árboles','La sombra empeora el ambiente de la ciudad'], solution:'La idea principal engloba sombra, biodiversidad y calidad del aire.' },
  { text:'Preparar un esquema antes de redactar ayuda a ordenar las ideas, evitar repeticiones y comprobar que no falta información importante.', answer:'Planificar antes de escribir mejora la organización del texto', distractors:['Un esquema sustituye siempre al texto final','Planificar obliga a repetir ideas','Escribir sin ordenar ideas evita errores'], solution:'Todos los beneficios mencionados proceden de planificar la redacción.' },
  { text:'Consultar varias fuentes sobre un mismo tema permite comparar datos y detectar si una información aparece solo en un sitio poco fiable.', answer:'Comparar varias fuentes ayuda a valorar mejor la fiabilidad de la información', distractors:['La primera fuente encontrada siempre es suficiente','Todas las páginas ofrecen la misma información','Comparar fuentes hace imposible comprobar datos'], solution:'El texto destaca la utilidad de contrastar información.' },
  { text:'Las zonas húmedas almacenan agua, sirven de refugio a numerosas especies y pueden reducir el impacto de algunas inundaciones.', answer:'Las zonas húmedas cumplen varias funciones ecológicas importantes', distractors:['Las zonas húmedas no albergan seres vivos','Su única función es acumular barro','Las inundaciones siempre aumentan por su presencia'], solution:'La idea central reúne las distintas funciones ambientales citadas.' },
  { text:'Un presupuesto sencillo permite anotar ingresos y gastos, prever cuánto se puede ahorrar y evitar gastar más dinero del disponible.', answer:'Un presupuesto ayuda a organizar y controlar el dinero', distractors:['Un presupuesto sirve para gastar sin límite','Ahorrar impide anotar los gastos','Los ingresos no forman parte de un presupuesto'], solution:'El texto explica varias utilidades de organizar ingresos y gastos.' },
  { text:'Practicar una exposición oral varias veces permite ajustar la duración, detectar partes poco claras y hablar con más seguridad.', answer:'Ensayar una exposición ayuda a mejorar su claridad y ejecución', distractors:['Ensayar hace que una exposición sea siempre más larga','La duración no puede ajustarse','Practicar impide hablar con seguridad'], solution:'El texto presenta varias mejoras derivadas del ensayo.' },
  { text:'Los carriles bici separados del tráfico pueden hacer los desplazamientos más seguros y animar a más personas a utilizar la bicicleta.', answer:'Una infraestructura ciclista segura puede favorecer el uso de la bicicleta', distractors:['Los carriles bici impiden desplazarse','La bicicleta solo se usa fuera de las ciudades','Separarse del tráfico aumenta siempre el riesgo'], solution:'La idea central relaciona seguridad e incremento del uso de la bicicleta.' },
]

const INTENT: Scenario[] = [
  { text:'«Mañana la salida será a las nueve en lugar de a las ocho y media».', answer:'Informar de un cambio de horario', distractors:['Pedir permiso para salir','Expresar enfado','Contar una aventura'], solution:'El mensaje comunica un dato nuevo sobre el horario.' },
  { text:'«Por favor, deja los libros en el carro de devoluciones antes de salir».', answer:'Pedir que se realice una acción', distractors:['Describir los libros','Narrar una visita','Expresar sorpresa'], solution:'El emisor solicita una acción concreta.' },
  { text:'«Si te interesa la fotografía, este taller es una oportunidad estupenda para empezar».', answer:'Recomendar o animar a participar', distractors:['Prohibir una actividad','Dar una definición','Pedir una dirección'], solution:'El mensaje valora positivamente el taller y anima al receptor.' },
  { text:'«¿Sabes si todavía quedan entradas para la sesión de las seis?».', answer:'Solicitar información', distractors:['Dar una orden','Expresar agradecimiento','Anunciar una prohibición'], solution:'La pregunta busca obtener un dato.' },
  { text:'«Sentimos no haber podido abrir esta mañana por la avería».', answer:'Disculparse por una situación', distractors:['Amenazar al público','Explicar una receta','Invitar a una fiesta'], solution:'El mensaje expresa una disculpa por una incidencia.' },
  { text:'«¡Qué alegría volver a veros después de tanto tiempo!».', answer:'Expresar alegría', distractors:['Prohibir una conducta','Solicitar un documento','Explicar un experimento'], solution:'La exclamación comunica una emoción positiva.' },
  { text:'«No utilices el ascensor durante el simulacro».', answer:'Prohibir una acción', distractors:['Contar un recuerdo','Hacer una recomendación de lectura','Preguntar una fecha'], solution:'La forma negativa establece una prohibición.' },
  { text:'«Ojalá el tiempo mejore y podamos hacer la excursión».', answer:'Expresar un deseo', distractors:['Dar una orden','Presentar un resultado','Definir un concepto'], solution:'“Ojalá” introduce un deseo.' },
  { text:'«Recuerda cargar la tableta esta noche para poder usarla mañana».', answer:'Recordar una tarea necesaria', distractors:['Describir una tableta','Expresar miedo','Anunciar un premio'], solution:'El propósito es que el receptor no olvide cargar el dispositivo.' },
  { text:'«Gracias por ayudarme a ordenar todo tan rápido».', answer:'Agradecer una ayuda', distractors:['Pedir una explicación','Prohibir una acción','Informar del tiempo'], solution:'El mensaje expresa gratitud.' },
  { text:'«Creo que deberíamos plantar más árboles en el patio porque darían sombra».', answer:'Proponer una idea y justificarla', distractors:['Narrar un accidente','Dar una fecha exacta','Solicitar silencio'], solution:'El emisor plantea una propuesta acompañada de una razón.' },
  { text:'«¿Te importaría bajar un poco la música mientras estudio?».', answer:'Pedir algo de forma cortés', distractors:['Informar de un concierto','Expresar admiración','Definir el volumen'], solution:'La pregunta funciona como una petición cortés.' },
]

const INFERENCE: Scenario[] = [
  { text:'Al entrar, Carla sacudió el paraguas, dejó el impermeable junto a la puerta y se secó las gafas.', answer:'Fuera estaba lloviendo', distractors:['Hacía un calor extremo','Carla venía de nadar','No había agua en el exterior'], solution:'El paraguas mojado, el impermeable y las gafas húmedas apuntan a lluvia.' },
  { text:'David miró el reloj, aceleró el paso hacia el andén y escuchó por megafonía que las puertas estaban a punto de cerrarse.', answer:'David intenta llegar a tiempo a un tren', distractors:['David está empezando una clase','David busca una mesa en un restaurante','David acaba de despertarse'], solution:'El andén, la megafonía y las puertas que cierran son pistas de una estación.' },
  { text:'Sara colocó el vaso medidor sobre la mesa, se puso las gafas de protección y leyó de nuevo el procedimiento.', answer:'Sara va a realizar una práctica o experimento', distractors:['Sara va a jugar un partido','Sara está preparando una novela','Sara va a dormir'], solution:'El material de medida, la protección y el procedimiento son pistas de laboratorio.' },
  { text:'Cuando terminó la última canción, el público se levantó, aplaudió y los músicos regresaron al escenario.', answer:'El público pedía o celebraba un bis', distractors:['El concierto todavía no había empezado','Los músicos estaban haciendo un examen','El público quería guardar silencio'], solution:'Los aplausos tras la última canción y el regreso al escenario sugieren un bis.' },
  { text:'Hugo leyó dos veces la etiqueta, dejó el producto en la estantería y escogió otro que no contenía frutos secos.', answer:'Hugo necesita evitar los frutos secos', distractors:['Hugo busca el producto más pesado','Hugo no sabe leer etiquetas','Hugo quiere comprar dos productos iguales'], solution:'Revisar la etiqueta y elegir un producto sin frutos secos indica que necesita evitarlos.' },
  { text:'La profesora cerró las persianas, encendió el proyector y pidió que todos miraran la pantalla.', answer:'La clase va a ver una presentación o proyección', distractors:['La clase va a salir al recreo','Ha terminado el día escolar','Van a practicar natación'], solution:'Persianas, proyector y pantalla apuntan a una proyección.' },
  { text:'Alicia llevaba dorsal, calentaba junto a otros corredores y comprobó que los cordones estuvieran bien atados.', answer:'Alicia está a punto de participar en una carrera', distractors:['Alicia va a asistir a un concierto','Alicia está cocinando','Alicia va a hacer una entrevista'], solution:'El dorsal, el calentamiento y los corredores son pistas de una carrera.' },
  { text:'El suelo estaba cubierto de confeti, quedaban globos atados a las sillas y alguien recogía platos de tarta.', answer:'Acababa de celebrarse una fiesta', distractors:['Acababa de terminar una clase de matemáticas','Estaban preparando un laboratorio','El lugar llevaba meses cerrado'], solution:'Confeti, globos y restos de tarta son indicios de una celebración.' },
  { text:'Mateo bajó el brillo de la pantalla, activó el modo nocturno y miró la hora antes de cerrar el portátil.', answer:'Era tarde y Mateo se preparaba para dejar de usar el ordenador', distractors:['Acababa de empezar la mañana','Mateo quería aumentar la luz','El portátil no tenía pantalla'], solution:'Modo nocturno, menor brillo y consultar la hora sugieren que era tarde.' },
  { text:'En la mesa había planos desplegados, una regla de escala y varias fotografías del terreno.', answer:'Se está planificando o estudiando un espacio', distractors:['Se está preparando una receta','Se está afinando un instrumento','Se está realizando una carrera'], solution:'Planos, escala y fotos del terreno son herramientas para estudiar o planificar un lugar.' },
  { text:'Nora habló en voz baja, apagó el sonido del móvil y se sentó frente a un escenario todavía vacío.', answer:'Nora está esperando que empiece una función o actuación', distractors:['Nora está en una pista deportiva','Nora está conduciendo','Nora está comprando fruta'], solution:'El escenario vacío y el silencio previo sugieren que espera una actuación.' },
  { text:'Luis comprobó la presión de las ruedas, ajustó el casco y encendió la luz trasera antes de salir.', answer:'Luis se prepara para desplazarse en bicicleta', distractors:['Luis va a nadar','Luis está preparando una comida','Luis va a tocar el piano'], solution:'Ruedas, casco y luz trasera son pistas de ciclismo.' },
]

const CONNECTORS: Scenario[] = [
  { text:'«El autobús llegó con retraso; ___, alcanzamos la conexión porque el segundo también se demoró».', answer:'aun así', distractors:['por eso','porque','además'], solution:'“Aun así” introduce un resultado que contrasta con el retraso inicial.' },
  { text:'«Terminamos de clasificar los datos; ___, empezamos a representarlos en una gráfica».', answer:'después', distractors:['aunque','porque','sin embargo'], solution:'“Después” marca la secuencia temporal entre las dos acciones.' },
  { text:'«La ruta estaba cerrada ___ habían caído varias ramas durante la tormenta».', answer:'porque', distractors:['sin embargo','además','por tanto'], solution:'“Porque” introduce la causa del cierre.' },
  { text:'«El equipo revisó las medidas dos veces; ___, encontró un error en una de ellas».', answer:'así', distractors:['aunque','mientras','o'], solution:'“Así” introduce el resultado de haber revisado las medidas.' },
  { text:'«Podemos presentar el trabajo como vídeo ___ como exposición oral».', answer:'o', distractors:['porque','sin embargo','por tanto'], solution:'“O” presenta dos alternativas.' },
  { text:'«El texto explica el problema; ___, propone dos posibles soluciones».', answer:'además', distractors:['aunque','porque','en cambio'], solution:'“Además” suma una segunda información relacionada.' },
  { text:'«El sendero era empinado; ___, las vistas desde arriba merecieron el esfuerzo».', answer:'sin embargo', distractors:['por eso','porque','así que'], solution:'“Sin embargo” introduce un contraste.' },
  { text:'«No quedaban plazas para el sábado; ___, reservamos para el domingo».', answer:'por tanto', distractors:['aunque','mientras','además'], solution:'“Por tanto” introduce la consecuencia lógica.' },
  { text:'«Mientras una persona anotaba los resultados, ___ otra comprobaba el cronómetro».', answer:'al mismo tiempo', distractors:['por eso','sin embargo','porque'], solution:'La expresión indica simultaneidad entre dos acciones.' },
  { text:'«Primero elegimos las fuentes más fiables; ___, comparamos los datos que ofrecían».', answer:'a continuación', distractors:['aunque','porque','en cambio'], solution:'“A continuación” ordena la segunda fase del proceso.' },
  { text:'«El ordenador funcionaba correctamente, ___ la conexión a internet era muy lenta».', answer:'pero', distractors:['por eso','además','porque'], solution:'“Pero” contrapone el buen funcionamiento del equipo con la lentitud de la conexión.' },
  { text:'«Llevamos una botella reutilizable ___ queremos evitar comprar envases de un solo uso».', answer:'porque', distractors:['aunque','sin embargo','o'], solution:'“Porque” introduce la razón de llevar la botella.' },
]

const LITERARY: Scenario[] = [
  { text:'«La mañana abrió sus ventanas de luz sobre los tejados».', answer:'Personifica la mañana y crea una imagen de comienzo luminoso', distractors:['Da una instrucción literal para abrir ventanas','Explica científicamente el amanecer','Elimina cualquier imagen del texto'], solution:'La mañana recibe una acción humana y la imagen sugiere el inicio del día.' },
  { text:'«Las noticias corrieron por el barrio como una chispa».', answer:'La comparación transmite que la información se difundió muy rápido', distractors:['Afirma que las noticias eran fuego real','Indica que nadie conoció la noticia','Describe una chispa sin relación con la información'], solution:'Comparar la difusión con una chispa intensifica la idea de rapidez.' },
  { text:'«Esperó un minuto, una hora, una eternidad».', answer:'La gradación exagera la sensación de una espera interminable', distractors:['Demuestra que solo pasó un minuto','Reduce la importancia del tiempo','Convierte el texto en una definición'], solution:'La progresión temporal aumenta la percepción subjetiva de la espera.' },
  { text:'«El silencio pesaba en la habitación».', answer:'La metáfora hace que el silencio parezca intenso e incómodo', distractors:['Indica que el silencio tiene masa medible','Explica cómo pesar una habitación','Sugiere que había mucho ruido'], solution:'Atribuir peso al silencio transmite una atmósfera densa o incómoda.' },
  { text:'«Volvió a mirar la puerta. Nada. Miró el teléfono. Nada».', answer:'La repetición de “Nada” refuerza la espera y la frustración', distractors:['Hace que todo ocurra con alegría','Presenta una lista científica','Indica que la persona ya recibió respuesta'], solution:'La repetición subraya que la respuesta esperada no llega.' },
  { text:'«El bosque susurraba alrededor del camino».', answer:'La personificación crea una atmósfera viva y envolvente', distractors:['Afirma que los árboles hablan con palabras','Elimina el ambiente del relato','Describe una norma de circulación'], solution:'“Susurraba” atribuye al bosque una acción humana y construye ambiente.' },
  { text:'«Su decisión fue un puente hacia una vida distinta».', answer:'El puente simboliza el paso hacia una nueva etapa', distractors:['Describe únicamente una construcción real','Indica que la decisión no produjo cambios','Explica cómo fabricar un puente'], solution:'La metáfora del puente representa transición y cambio.' },
  { text:'«La duda le mordía cada vez que intentaba responder».', answer:'La personificación presenta la duda como algo persistente y molesto', distractors:['Afirma que una duda tiene dientes reales','Expresa tranquilidad absoluta','Describe una lesión física concreta'], solution:'“Morder” convierte la duda en una presencia activa e incómoda.' },
  { text:'«El último día de verano se deshizo entre sus dedos».', answer:'La imagen sugiere que el tiempo pasa y no puede retenerse', distractors:['El verano es un objeto que se rompe literalmente','El tiempo se ha detenido','Describe una receta con las manos'], solution:'La imagen de algo que se deshace transmite fugacidad.' },
  { text:'«La plaza despertó poco a poco: primero una persiana, luego una bicicleta, después cien voces».', answer:'La secuencia muestra cómo el lugar pasa de la calma a la actividad', distractors:['La plaza se queda cada vez más vacía','Todo sucede al mismo tiempo sin cambio','Se describe únicamente una bicicleta'], solution:'Los elementos aparecen de forma gradual hasta llenar la plaza de actividad.' },
  { text:'«Sus palabras fueron una brújula cuando no sabía qué hacer».', answer:'La brújula simboliza orientación o guía', distractors:['Las palabras eran un instrumento físico','El personaje se perdió necesariamente en un bosque','Las palabras provocaron más desorientación'], solution:'La metáfora presenta las palabras como una guía para decidir.' },
  { text:'«La derrota dolía, pero debajo de ella ya crecía una nueva determinación».', answer:'La imagen sugiere que de una dificultad puede surgir fuerza para continuar', distractors:['La derrota impide cualquier cambio','Describe literalmente una planta bajo un objeto','El personaje decide abandonar para siempre'], solution:'“Crecer” representa el nacimiento progresivo de una nueva determinación.' },
]

const BANK: Record<string, Scenario[]> = { L01S01: MAIN_IDEA, L01S02: INTENT, L01S03: INFERENCE, L01S04: CONNECTORS, L06S04: LITERARY }
const FRAMES: Record<string, string[]> = {
  L01S01: ['¿Cuál es la idea principal?', '¿Qué resumen recoge mejor el sentido global?', '¿Qué opción sintetiza mejor el texto?', '¿Cuál sería el mejor título-resumen?'],
  L01S02: ['¿Cuál es la intención principal del mensaje?', '¿Qué pretende hacer principalmente el emisor?', '¿Para qué se ha emitido este mensaje?', '¿Qué función cumple sobre todo este mensaje?'],
  L01S03: ['¿Qué podemos inferir?', '¿Qué conclusión está mejor apoyada por las pistas?', '¿Qué es lo más probable a partir de lo leído?', '¿Qué deducción encaja mejor con la escena?'],
  L01S04: ['¿Qué conector completa mejor la oración?', 'Elige la palabra o expresión que relaciona mejor las ideas.', '¿Qué enlace textual encaja por significado?', '¿Qué conector mantiene la relación lógica entre las partes?'],
  L06S04: ['¿Qué efecto produce el recurso expresivo?', '¿Qué aporta esta imagen al sentido del fragmento?', '¿Cómo contribuye el lenguaje figurado al texto?', '¿Qué interpretación explica mejor el recurso utilizado?'],
}

function rotate<T>(items:T[], shift:number){ const n=((shift%items.length)+items.length)%items.length; return items.slice(n).concat(items.slice(0,n)) }

export function generateSpanishReadingGenerated(skill:SkillMeta,difficulty:number,seed:number):GeneratedQuestion|null {
  const scenarios=BANK[skill.id]
  const frames=FRAMES[skill.id]
  if(!scenarios?.length||!frames?.length) return null
  const normalized=seed>>>0
  const scenarioIndex=normalized%scenarios.length
  const frameIndex=Math.floor(normalized/scenarios.length)%frames.length
  const selected=scenarios[scenarioIndex]
  const prompt=`Lee: ${selected.text} ${frames[frameIndex]}`
  const options=rotate([selected.answer,...selected.distractors],normalized+difficulty)
  return { skillId:skill.id,label:skill.name,difficulty,seed,prompt,options,answerIndex:options.indexOf(selected.answer),solution:selected.solution,tags:[skill.generator_key,'spanish','reading_course_depth'] }
}

export function spanishReadingGeneratedSkillIds(){ return Object.keys(BANK) }
export function spanishReadingGeneratedScenarioCount(){ return Object.values(BANK).reduce((sum,items)=>sum+items.length,0) }
export function spanishReadingGeneratedPromptCount(skillId:string){ return (BANK[skillId]?.length??0)*(FRAMES[skillId]?.length??0) }
