export type WorldZoneId = 'language' | 'english' | 'science' | 'geography'
export type WorldDistrictAvailability = 'coming_soon' | 'playable'
export type WorldDistrict = { icon: string; name: string; detail: string; availability: WorldDistrictAvailability; href?: string }
export type WorldZone = { id: WorldZoneId; name: string; icon: string; className: string; tagline: string; description: string; mission: string; districts: WorldDistrict[] }

const comingSoon = (icon: string, name: string, detail: string): WorldDistrict => ({ icon, name, detail, availability: 'coming_soon' })
const playable = (icon: string, name: string, detail: string, href: string): WorldDistrict => ({ icon, name, detail, availability: 'playable', href })

export const WORLD_ZONES: WorldZone[] = [
  { id: 'language', name: 'Biblioteca de Lengua', icon: '📚', className: 'language-zone', tagline: 'Las historias han perdido sus palabras', description: 'Lectura, vocabulario, gramática y escritura se convertirán en expediciones narrativas.', mission: 'Reconstruir relatos y recuperar los archivos de la Gran Biblioteca.', districts: [playable('🔎', 'Galería de lectura', 'Comprensión e inferencias', '/zone/language/reading'), playable('🧩', 'Taller de palabras', 'Gramática y vocabulario', '/zone/language/words'), playable('✍️', 'Sala de cronistas', 'Expresión escrita', '/zone/language/writing')] },
  { id: 'english', name: 'Puerto de Inglés', icon: '🌍', className: 'english-zone', tagline: 'Cada conversación abre una nueva ruta', description: 'Vocabulario, comprensión y comunicación forman una aventura de viajes.', mission: 'Conseguir permisos de navegación hablando con personajes de todo el mundo.', districts: [playable('🎧', 'Muelle de escucha', 'Comprensión oral', '/zone/english/listening'), playable('💬', 'Plaza de conversación', 'Uso práctico del idioma', '/zone/english/conversation'), playable('🧳', 'Terminal de palabras', 'Vocabulario y estructuras', '/zone/english/terminal')] },
  { id: 'science', name: 'Laboratorio de Ciencias', icon: '🔬', className: 'science-zone', tagline: 'Investiga antes de sacar conclusiones', description: 'Biología, geología, ecosistemas y método científico viven en laboratorios interactivos.', mission: 'Resolver anomalías mediante observación, hipótesis y evidencias.', districts: [playable('🧬', 'Cúpula de la vida', 'Células, seres vivos y ecosistemas', '/zone/science/life'), playable('⚗️', 'Cámara de investigación', 'Hipótesis, variables, evidencias y fuentes', '/zone/science/investigation'), playable('🌌', 'Observatorio', 'Tierra, rocas y relieve', '/zone/science/observatory')] },
  { id: 'geography', name: 'Atlas de Geografía e Historia', icon: '🗺️', className: 'creative-zone', tagline: 'Entiende el territorio para reconstruir el pasado', description: 'Mapas, relieve, clima y grandes civilizaciones forman una campaña de exploración del espacio y del tiempo.', mission: 'Reconstruir el Gran Atlas conectando lugares, paisajes, fuentes y civilizaciones.', districts: [playable('🧭', 'Sala de cartografía', 'Orientación, escalas, mapas, leyendas y símbolos', '/zone/geography/maps'), comingSoon('🏔️', 'Expedición terrestre', 'Relieve, aguas, clima y paisajes'), comingSoon('🏛️', 'Archivo del tiempo', 'Prehistoria, primeras civilizaciones, Grecia y Roma')] },
]

export function worldZoneById(value: string) { return WORLD_ZONES.find((zone) => zone.id === value) }
