-- Stage audited v1.24 skills in the database without exposing them to missions yet.
-- Activation is a separate release step after the playable multi-subject flow passes Quality.

insert into public.skills (
  id, name, subject_id, unit_id, goal, generator_key, sort_order, critical, active
) values
  ('L01S01','Idea principal e información relevante','spanish','L01','Identificar tema, idea principal y datos relevantes en textos breves','es_main_idea',1,true,false),
  ('L01S02','Intención comunicativa','spanish','L01','Reconocer intención, emisor, receptor y situación comunicativa','es_communication_intent',2,false,false),
  ('L01S03','Inferencias y contexto','spanish','L01','Deducir información implícita a partir de pistas textuales','es_inference',3,false,false),
  ('L01S04','Coherencia y cohesión básica','spanish','L01','Reconocer relaciones lógicas y conectores en un texto','es_cohesion',4,false,false),
  ('L02S01','Clases de palabras','spanish','L02','Distinguir sustantivos, adjetivos, determinantes, pronombres, verbos, adverbios y nexos','es_word_classes',1,true,false),
  ('L02S02','Sujeto y predicado','spanish','L02','Identificar sujeto, predicado y concordancia','es_subject_predicate',2,false,false),
  ('L02S03','Núcleos y grupos sintácticos básicos','spanish','L02','Reconocer núcleos nominales y verbales en estructuras sencillas','es_phrase_heads',3,false,false),
  ('L02S04','Concordancia gramatical','spanish','L02','Aplicar concordancia de género, número y persona','es_agreement',4,false,false),
  ('L03S01','Sinonimia y antonimia','spanish','L03','Reconocer relaciones básicas de significado','es_syn_ant',1,false,false),
  ('L03S02','Polisemia y contexto','spanish','L03','Interpretar significados de palabras polisémicas según el contexto','es_polysemy',2,true,false),
  ('L03S03','Familias de palabras','spanish','L03','Reconocer lexemas, palabras derivadas y familias léxicas','es_word_families',3,false,false),
  ('L03S04','Formación de palabras','spanish','L03','Identificar prefijos, sufijos y procedimientos básicos de formación','es_word_formation',4,false,false),
  ('L04S01','Acentuación','spanish','L04','Aplicar reglas de acentuación de agudas, llanas y esdrújulas','es_accentuation',1,true,false),
  ('L04S02','B/V, G/J y H','spanish','L04','Aplicar regularidades ortográficas frecuentes','es_spelling_letters',2,false,false),
  ('L04S03','Mayúsculas y signos de puntuación','spanish','L04','Usar mayúsculas, punto, coma, dos puntos e interrogación de forma adecuada','es_punctuation',3,false,false),
  ('L04S04','Corrección ortográfica en contexto','spanish','L04','Detectar y corregir errores ortográficos en frases y textos breves','es_spelling_edit',4,false,false),
  ('L05S01','Narración','spanish','L05','Reconocer estructura, narrador, personajes, espacio y tiempo','es_narrative',1,false,false),
  ('L05S02','Descripción','spanish','L05','Distinguir rasgos objetivos y subjetivos y organizar una descripción','es_description',2,false,false),
  ('L05S03','Exposición y explicación','spanish','L05','Identificar estructura expositiva y relaciones de causa, ejemplo y definición','es_exposition',3,true,false),
  ('L05S04','Planificación y revisión','spanish','L05','Ordenar ideas y revisar claridad, cohesión y corrección de un texto breve','es_writing_revision',4,false,false),
  ('L06S01','Géneros literarios','spanish','L06','Distinguir narrativa, lírica y teatro por sus rasgos básicos','es_literary_genres',1,true,false),
  ('L06S02','Recursos literarios básicos','spanish','L06','Reconocer comparación, metáfora, personificación y repetición','es_literary_devices',2,false,false),
  ('L06S03','Voz, personajes y conflicto','spanish','L06','Interpretar elementos narrativos y dramáticos básicos','es_literary_elements',3,false,false),
  ('L06S04','Interpretación de fragmentos','spanish','L06','Relacionar forma, tema y efecto en fragmentos literarios breves','es_literary_reading',4,false,false),

  ('E01S01','Personal information','english','E01','Understand and produce basic personal information','en_personal_info',1,true,false),
  ('E01S02','Subject pronouns and be','english','E01','Use subject pronouns and present forms of be','en_be_pronouns',2,false,false),
  ('E01S03','Possessives and have got','english','E01','Use possessive adjectives and have got in familiar contexts','en_possessives_have',3,false,false),
  ('E01S04','Classroom instructions','english','E01','Understand common classroom instructions and requests','en_classroom_language',4,false,false),
  ('E02S01','Present simple','english','E02','Use present simple for routines and facts','en_present_simple',1,true,false),
  ('E02S02','Adverbs of frequency','english','E02','Place and interpret common adverbs of frequency','en_frequency',2,false,false),
  ('E02S03','Questions and short answers','english','E02','Form do/does questions and short answers','en_present_questions',3,false,false),
  ('E02S04','Time and routines vocabulary','english','E02','Understand times, routine verbs and sequence markers','en_routines_vocab',4,false,false),
  ('E03S01','Present continuous','english','E03','Use present continuous for actions in progress','en_present_continuous',1,true,false),
  ('E03S02','Present simple vs continuous','english','E03','Choose between routines and actions in progress','en_present_contrast',2,false,false),
  ('E03S03','Describing people and places','english','E03','Use common adjectives and there is/are','en_descriptions',3,false,false),
  ('E03S04','Comparatives','english','E03','Form and interpret basic comparative adjectives','en_comparatives',4,false,false),
  ('E04S01','Past of be','english','E04','Use was/were in affirmative, negative and questions','en_past_be',1,false,false),
  ('E04S02','Past simple regular verbs','english','E04','Form and understand regular past simple','en_past_regular',2,true,false),
  ('E04S03','Common irregular past forms','english','E04','Recognize and use frequent irregular past verbs','en_past_irregular',3,false,false),
  ('E04S04','Sequencing past events','english','E04','Order short narratives with time connectors','en_past_sequence',4,false,false),
  ('E05S01','Can and can’t','english','E05','Express ability, permission and possibility with can','en_can',1,false,false),
  ('E05S02','Must and mustn’t','english','E05','Express basic obligation and prohibition','en_must',2,false,false),
  ('E05S03','Going to','english','E05','Express future intentions and plans','en_going_to',3,true,false),
  ('E05S04','Functional language','english','E05','Choose appropriate expressions for requests, offers and suggestions','en_functional_language',4,false,false),
  ('E06S01','Reading for gist','english','E06','Identify the general meaning of short accessible texts','en_reading_gist',1,true,false),
  ('E06S02','Reading for detail','english','E06','Locate explicit information and infer simple meaning from context','en_reading_detail',2,false,false),
  ('E06S03','Text organisation','english','E06','Use basic connectors and paragraph order in short texts','en_text_organisation',3,false,false),
  ('E06S04','Mediation and paraphrase','english','E06','Restate simple information using accessible English','en_mediation',4,false,false),

  ('G01S01','Cardinal directions and coordinates','geography_history','G01','Locate places using orientation and geographic coordinates','gh_orientation',1,true,false),
  ('G01S02','Scale and distance','geography_history','G01','Interpret simple map scales and estimate real distances','gh_scale',2,false,false),
  ('G01S03','Types of maps','geography_history','G01','Distinguish physical, political and thematic maps','gh_map_types',3,false,false),
  ('G01S04','Reading legends and symbols','geography_history','G01','Interpret legends, conventional symbols and simple thematic data','gh_map_legend',4,false,false),
  ('G02S01','Major relief forms','geography_history','G02','Identify mountains, plains, plateaus, valleys and coastal forms','gh_relief',1,true,false),
  ('G02S02','Continents and oceans','geography_history','G02','Locate major continents, oceans and geographic regions','gh_world_location',2,false,false),
  ('G02S03','Rivers and watersheds','geography_history','G02','Understand basic river elements and drainage basins','gh_rivers',3,false,false),
  ('G02S04','Relief and human settlement','geography_history','G02','Relate physical geography to settlement and activities','gh_relief_humans',4,false,false),
  ('G03S01','Weather vs climate','geography_history','G03','Distinguish weather from climate and identify basic atmospheric variables','gh_weather_climate',1,true,false),
  ('G03S02','Climate factors','geography_history','G03','Relate latitude, altitude, distance from sea and relief to climate','gh_climate_factors',2,false,false),
  ('G03S03','Climate graphs','geography_history','G03','Read simple temperature and precipitation graphs','gh_climate_graphs',3,false,false),
  ('G03S04','Climate and human impact','geography_history','G03','Connect climate patterns, risks and human activities','gh_climate_impact',4,false,false),
  ('G04S01','Historical time and chronology','geography_history','G04','Order events and use basic chronological conventions','gh_chronology',1,true,false),
  ('G04S02','Palaeolithic societies','geography_history','G04','Recognize hunter-gatherer lifeways and technological change','gh_palaeolithic',2,false,false),
  ('G04S03','Neolithic revolution','geography_history','G04','Explain agriculture, sedentism and social change','gh_neolithic',3,false,false),
  ('G04S04','Prehistoric sources','geography_history','G04','Interpret archaeological evidence and distinguish source types','gh_prehistory_sources',4,false,false),
  ('G05S01','Mesopotamia','geography_history','G05','Recognize key features of Mesopotamian urban civilisation','gh_mesopotamia',1,false,false),
  ('G05S02','Ancient Egypt','geography_history','G05','Understand Nile society, political organisation and beliefs','gh_egypt',2,true,false),
  ('G05S03','Writing, law and administration','geography_history','G05','Explain why writing and institutions transformed early states','gh_early_states',3,false,false),
  ('G05S04','Comparing early civilisations','geography_history','G05','Compare environment, economy, society and power in early civilisations','gh_compare_civilisations',4,false,false),
  ('G06S01','Greek polis and democracy','geography_history','G06','Understand the polis and basic features of Athenian democracy','gh_greece_polis',1,true,false),
  ('G06S02','Greek culture and legacy','geography_history','G06','Recognize major cultural contributions of Ancient Greece','gh_greece_culture',2,false,false),
  ('G06S03','Roman Republic and Empire','geography_history','G06','Distinguish major stages and institutions of Roman history','gh_rome_stages',3,false,false),
  ('G06S04','Romanisation and legacy','geography_history','G06','Identify Romanisation and enduring Roman influences','gh_romanisation',4,false,false),

  ('B01S01','Questions and hypotheses','biology_geology','B01','Distinguish testable questions and hypotheses','bg_hypotheses',1,true,false),
  ('B01S02','Variables and fair tests','biology_geology','B01','Identify variables and controls in simple investigations','bg_variables',2,false,false),
  ('B01S03','Data and evidence','biology_geology','B01','Interpret simple tables and graphs and draw evidence-based conclusions','bg_data_evidence',3,false,false),
  ('B01S04','Scientific information','biology_geology','B01','Distinguish scientific evidence from unsupported claims','bg_science_sources',4,false,false),
  ('B02S01','Earth systems','biology_geology','B02','Identify geosphere, hydrosphere, atmosphere and biosphere','bg_earth_systems',1,true,false),
  ('B02S02','Minerals and rocks','biology_geology','B02','Distinguish minerals and main rock groups by basic properties','bg_rocks_minerals',2,false,false),
  ('B02S03','Rock cycle','biology_geology','B02','Relate igneous, sedimentary and metamorphic rocks through the rock cycle','bg_rock_cycle',3,false,false),
  ('B02S04','Geological processes and relief','biology_geology','B02','Connect erosion, transport, sedimentation and internal processes to relief','bg_geological_processes',4,false,false),
  ('B03S01','Cell theory','biology_geology','B03','Understand the cell as the basic unit of life','bg_cell_theory',1,true,false),
  ('B03S02','Cell structures','biology_geology','B03','Identify major cell structures and their basic functions','bg_cell_parts',2,false,false),
  ('B03S03','Plant and animal cells','biology_geology','B03','Compare basic plant and animal cell structures','bg_plant_animal_cells',3,false,false),
  ('B03S04','Levels of organisation','biology_geology','B03','Order cell, tissue, organ, system and organism','bg_levels_organisation',4,false,false),
  ('B04S01','Characteristics of life','biology_geology','B04','Recognize common functions and characteristics of living things','bg_life_characteristics',1,true,false),
  ('B04S02','Classification criteria','biology_geology','B04','Classify organisms using observable traits and simple keys','bg_classification',2,false,false),
  ('B04S03','Major groups of organisms','biology_geology','B04','Recognize broad groups of microorganisms, plants and animals','bg_living_groups',3,false,false),
  ('B04S04','Biodiversity','biology_geology','B04','Explain biodiversity and why classification supports its study','bg_biodiversity',4,false,false),
  ('B05S01','Biotic and abiotic factors','biology_geology','B05','Distinguish living and non-living ecosystem factors','bg_ecosystem_factors',1,true,false),
  ('B05S02','Food chains and webs','biology_geology','B05','Interpret producers, consumers and decomposers in food relationships','bg_food_webs',2,false,false),
  ('B05S03','Interactions and balance','biology_geology','B05','Identify basic ecological interactions and effects of change','bg_ecological_interactions',3,false,false),
  ('B05S04','Human impact on ecosystems','biology_geology','B05','Relate human activities to habitat loss, pollution and conservation','bg_ecosystem_impact',4,false,false),
  ('B06S01','Healthy habits','biology_geology','B06','Relate sleep, activity, hygiene and diet to health','bg_healthy_habits',1,true,false),
  ('B06S02','Nutrition basics','biology_geology','B06','Distinguish nutrients and interpret simple healthy-diet information','bg_nutrition',2,false,false),
  ('B06S03','Environmental health','biology_geology','B06','Connect environmental quality with human and ecosystem health','bg_environmental_health',3,false,false),
  ('B06S04','Sustainable choices','biology_geology','B06','Evaluate simple everyday choices using sustainability criteria','bg_sustainable_choices',4,false,false)
on conflict (id) do update set
  name = excluded.name,
  subject_id = excluded.subject_id,
  unit_id = excluded.unit_id,
  goal = excluded.goal,
  generator_key = excluded.generator_key,
  sort_order = excluded.sort_order,
  critical = excluded.critical,
  active = false;
